### ISSUE TITLE
Problem when user's password contains spaces

### ISSUE THREAD

**Issue by SteffenL** [conan-io/conan-package-tools#1]
When a package is about to be uploaded, the user's password is not quoted when running `conan user`. This is a problem if the password contains spaces.

**Comment by memsharded** [comment]
The offending line is https://github.com/conan-io/conan-package-tools/blob/develop/conan/packager.py#L104

It should also be checked what happen with passwords with quotes, they should probably also be allowed.

**Comment by memsharded** [comment]
I think https://github.com/conan-io/conan-package-tools/pull/2 should fix the issue (both spaces and quotes). But please, when merged, tell me if you have any other problem with it. Cheers
