### ISSUE TITLE
Consider "stable" as a stable branch pattern by default

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#100]
If `CONAN_STABLE_BRANCH_PATTERN` environment variable is not set, then package tools treats `master` as the default stable branch pattern.  This is a request to treat both `master` and `stable` as default stable branch patterns.  `stable` is the currently promoted convention, and we'll be publishing over 100 packages using this as the branch name.  It would be cleaner not to have to add this environment variable to each recipe or each CI project, since there's already default logic in place.

**Comment by lasote** [comment]
`stable`? or `stable*`?

**Comment by solvingj** [comment]
Valid question. `stable*` is probably better.

**Comment by lasote** [comment]
Will be in beta2
