### ISSUE TITLE
Deduce conan reference from conanfile in current directory

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#101]
In writing this ticket, I realized that it would require a change to the `conan upload` command.  I opened a ticket for that here: 
https://github.com/conan-io/conan/issues/1746

If we can get that ticket approved, than it should be trivial to have conan package tools default to the current directory and eliminate another redundant configuration step in the common case for CI.

**Comment by lasote** [comment]
Done in the 0.17.0beta1
