### ISSUE TITLE
Docker image lasote/conangcc52 failing in travis

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-package-tools#102]
Hi!

Don't know if something have been changed for that image (`lasote/conangcc52`) but it has started to fail in my CI jobs some days ago (ej: https://travis-ci.org/jgsogo/conan-postgresql/builds/276202594). It fails when making a `sudo apt-get update`:

```
Running: sudo apt-get update
Ign http://archive.ubuntu.com wily InRelease
Ign http://archive.ubuntu.com wily-updates InRelease
Ign http://archive.ubuntu.com wily-security InRelease
Ign http://archive.ubuntu.com wily Release.gpg
Ign http://archive.ubuntu.com wily-updates Release.gpg
Ign http://archive.ubuntu.com wily-security Release.gpg
Ign http://archive.ubuntu.com wily Release
Ign http://archive.ubuntu.com wily-updates Release
Ign http://archive.ubuntu.com wily-security Release
Err http://archive.ubuntu.com wily/main Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com wily/restricted Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com wily/universe Sources
```

Looking for `wily` instead of `vivid`?

**Comment by memsharded** [comment]
I don't know, may it be related to some upgrade of travis machines? @lasote?

**Comment by Croydon** [comment]
Wily is end of life. you would need to use the respective repositories over at http://old-releases.ubuntu.com/ubuntu/dists/

**Comment by lasote** [comment]
Thanks all! I've pushed the image and dockerfile using the new repositories.
