### ISSUE TITLE
Linux x86 builds - OS dependencies issues

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#106]
Currently, we have a handful of packages which fail for x86 builds on Travis.  Errors look like this: 
```
In file included from /usr/include/curl/curl.h:35:0, from /home/conan/.conan/data/Azure-C-Shared-Utility/1.0.41/bincrafters/stable/build/e77dff23066e0a9b35ee98e3dea7ddca38d50003/azure-c-shared-utility-2017-08-11/adapters/httpapi_curl.c:14:

/usr/include/curl/curlrules.h:142:3: error: size of array '__curl_rule_01__' is negative
   __curl_rule_01__
   ^
CMakeFiles/aziotsharedutil_dll.dir/build.make:1046: recipe for target 'CMakeFiles/aziotsharedutil_dll.dir/adapters/httpapi_curl.c.o' failed
```

@uilianries identified that the problem exists when building for arch=x86 on an x64 machine (such as travis), when the build requires linking to existing OS packages on the build machine.  This is because all the OS packages installed on the VM are the x64 variant, which will cause errors when you try to link to them dynamically during x86 compilation. 

One workaround would be to uninstall any x64 packages and re-install the x86 variant before we try to build. This would be ugly. 

Alternatively, docker should make this relatively easy to fix, since Docker images are already used extensively in conan_package_tools.  We just need any x86 build variants to automatically run on x86 docker images with all x86 OS packages installed. 

At least, this is our current line of thinking.  Does this sound like a good approach?  If so, how hard would it be to create copies of lasotes existing docker images but starting from x86 images?

**Comment by lasote** [comment]
I've been trying to follow that approach, but I can't cover all the x86 alternatives for all the system libraries. This is really a pain. 
The natural approach, is, of course, do not link with system dependencies and use conan ones for everything, but yeah, I understand that sometimes it's just not possible.

If you have the needed packages identified I can try to upgrade the docker images, but updating all of them is a very tedious task.

**Comment by solvingj** [comment]
Got it, makes sense.  

To your point about providing all dependencies via conan, there could be a radical future there worth considering.  Here's an interesting project in that arena:  https://github.com/GoogleCloudPlatform/distroless

**Comment by lasote** [comment]
Since **CONAN_DOCKER_32_IMAGES** will use the "native" 32 bit images, it should be solved.
