### ISSUE TITLE
conan upload_repo address does not change if the address change in CONAN_UPLOAD

### ISSUE THREAD

**Issue by tonka3000** [conan-io/conan-package-tools#107]
Hey,

I have found a strange behaviour in conan-package-tools. If've use my CI servers to produce the prebuild binaries (as most people do). But now i've found the strange problem that when i change the CONAN_UPLOAD variable over time the old address will stay. The expected behaviour is that the value will be always overwrite the existing one, because if it change overtime i have to go to every ci server and remove the upload_repo in the registry.txt  file, which is painful :disappointed: . 

I'm using Windows 7 x64 and no container like docker!

I've use conan 0.27 and pkg-tools 0.5.5

**Comment by lasote** [comment]
So, you are not cleaning the server conan "environment" between builds, right? 
conan package tools is assuming that the registry is empty before the start.
It should be a good practice to have a clean environment every time, have you tried to create a fresh conan home with CONAN_USER_HOME variable and maybe remove old directories with a programmed task in Windows? 
Are there any other specific reason for keeping the conan home configured between builds?

**Comment by tonka3000** [comment]
No, there is no reason.
As i understand switch CONAN_USER_HOME is like pythons virtualenv, when i change the value, my config file and my conan builds are in this dirctory - is that right?
When that is true, it is very easy to isolate my builds, because i set it at the beginning to my ci build dir and remove this directory in the end.

**Comment by memsharded** [comment]
Yes, CONAN_USER_HOME is a clean and isolated instance of conan, with its own remotes, package storage, configuration, profiles....

It might be possible, if not using clean environments, that the old remote is being used, and it is not being properly updated when CONAN_UPLOAD changes.

Just in case, I think there is no need to modify registry.txt manually, it can be fully managed with conan commands. But in any case, it won't be necessary, will it?

**Comment by tonka3000** [comment]
Total aggree, i always try to use conan commands when i change settings etc..

CONAN_USER_HOME works great, but my new problem is the the path-length of my solution (created by cmake) is longer the 260 characters and Visual Studio don't like that. Is there any solution for that in conan f.e. short path's in windows or something like that?

**Comment by memsharded** [comment]
If you are in Win10, I would try to move to latest python 3.6, which can enable the usage of long paths, no limit.

If not, conan helps with long paths in the conan cache, with the ``short_paths`` feature. But only works for the cache, it can't do anything with user projects.

**Comment by tonka3000** [comment]
My problem with the `short_paths` feature is that i have to define a directory, but in the CI system i want to have it in my build directory, so that it is easy to remove it afterwards. Does python 3.6 helps me in any kind or is it only the non-limit options for Win10. I must use Windows 7 at the moment.

**Comment by memsharded** [comment]
I think it has to be Win10 + python 3.6

For CI you can easily use ``CONAN_USER_HOME`` (most likely you have to use this anyway), and also ``CONAN_USER_HOME_SHORT``. Then you will have full control to remove them at the end of tje job.

**Comment by tonka3000** [comment]
I also think that `CONAN_USER_HOME_SHORT` is my only option. I will try it

**Comment by tonka3000** [comment]
Ok. I works.
I've changed the CONAN_USER_HOME like following
`set CONAN_USER_HOME=%USERPROFILE%\_cb`
So the path is shorted.  
The normal `C:\.conan` does not work well because my CI servers always need write access to this directory, which is not nicely portable.
In the cleanup stage of the ci system i call
`conan remove * -f` to remove the package (because the linked binaries will be delete also).

I think you can close this issue.
