### ISSUE TITLE
pip install fail with CFFI 1.11.1 on Windows with python 3.5.2 x64

### ISSUE THREAD

**Issue by tonka3000** [conan-io/conan-package-tools#109]
Hello,

the release of CFFI version 1.11.1 (http://cffi.readthedocs.io/en/latest/whatsnew.html#v1-11-1) today breaks the build in windows with python 3.5.2 x64 (i've not tested other python version) => so it's not possible to install conan-package-tools on windows with python 3.5.x at the moment.

I've created an issue on the CFFI bitbucket issue tracker => https://bitbucket.org/cffi/cffi/issues/338/cffi-1111-fails-on-windows-7-with-python

I install conan-package-tools via `pip install conan-package-tools --upgrade`

Tonka

**Comment by memsharded** [comment]
Thanks for reporting this.

But I guess it might be a conan issue, or is it just a conan-package-tools issue? Who is depending (transitively, I cannot see cffi as a direct conan dependency) on it?

**Comment by tonka3000** [comment]
It's a conan-package-tools problem. cffi is an indirect dependency! On the linked issue above you can see that this also happens on ubuntu.

**Comment by memsharded** [comment]
I have just tried, and it is a dependency of conan, too, not only conan-package-tools.

Do you think @lasote that we should fix the previous CFFI release because of this?

**Comment by tonka3000** [comment]
It seems that cffi 1.11.1 is fixed now.

**Comment by memsharded** [comment]
It seems they have released the wheels for 1.11.1 now. If you confirm that it is working, this can be closed. Thanks!

**Comment by tonka3000** [comment]
I confirm it, you can close this issue.
