### ISSUE TITLE
Write basic documentation of how conan-package-tools works

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#113]
I've been working with this project for months, and have had many discussions about how things work. I've even gotten other people started using it.  Unfortunately, I still cannot use a lot of the cool features built into it because I don't actually understand what happens under the hood.  Currently I am capable of using  `add_common_builds()`, filtering out selected builds, and using `builder.add()` for special circumstances. I'm not sure what effect the environment variables have, or what other utilities exist if we're not using `add_common_builds()` (if any).  In the end, I'm mostly pointing out that this project could really use some further documentation because I think myself and others might be using it very inefficiently.

**Comment by lasote** [comment]
I've tried to improve the README in this branch. Please tell me if now it's more clear how/what/why you can use conan package tools. Any help would be welcome.

https://github.com/conan-io/conan-package-tools/blob/feature/better_readme/README.md

**Comment by solvingj** [comment]
That document is absolutely amazing.  Definitely can close this ticket now.  Really great work, you should share it in slack :)

**Comment by solvingj** [comment]
The following is still unclear to me. 

For scenarios where `add_common_builds()` cannot be used, are the `CONAN_XYZ` environment  variables still used?  How about the `ConanMultiPackager` constructor arguments?  It seems to be that these are only used if `add_common_builds()` is used, otherwise they're discarded, correct?

I had hoped/tried to set `CONAN_ARCHS=x86` and `CONAN_ARCHS=x64` in travis and appveyor, and then add 4 manual builds in `build.py` hoping that the environment variables would be automatically combined with my builds.  And, also thinking that maybe if I specified two (as in, `x86, x86_64`), that conan multipackager would "multiply" my 4 manual builds to 8, creating a matrix based on the environment variable.  This did not seem to happen. 

A common scenario seems to be when we have 2 or 3+ custom options, and want to generate our own matrix, but also get the multiplying behavior of the environment variables.  We can do any matrix today manually, but compared to the convenience of `add_common_builds`, it just seems tedious.  The logic to take a list of options and create a matrix of them doesn't seem terribly difficult to be honest (although, not trivial if they're not all simple booleans).   

Both questions and suggestions here I guess.

**Comment by solvingj** [comment]
I just noticed that the docker does not print out this information as we see it in the output for mac builds. This information helped us detect we made some significant mistakes in our CI configuration, would be helpful to see it in the docker container build output: 
```
INFO: ******** RUNNING BUILD ********** 
conan create bincrafters/testing --profile /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/tmpU9d5bYconan_package_tools_profiles/profile 
[build_requires]
[settings]
[options]
icu:shared=True
icu:with_data=True
[scopes]
[env]
 ```

**Comment by lasote** [comment]
About the env vars and the `add_common_builds()`, yes, same as the constructor parameters, they only affect when used with `add_common_builds()`.  It is a very good point because it's not intuitive at all. The origin of this behavior is that the conan package tools started like a monolith script just for testing purposes and then it has been refactored, so some things are not clear enough. I'll add to the README an observation. 

About generating a custom matrix with custom options, sure, we could do it. Please open a new issue and we can study it.

**Comment by lasote** [comment]
About the docker traces, open a new one.
