### ISSUE TITLE
Unable to disable clang_versions without CONAN_GCC_VERSIONS

### ISSUE THREAD

**Issue by kolis** [conan-io/conan-package-tools#114]
I specify gcc versions using the `gcc_versions` argument, not the environment variable. This makes it impossible to disable the clang build configurations for linux. I tried setting `clang_versions = []`, but this does not work due to
```python
        self.clang_versions = clang_versions or list(filter(None, os.getenv("CONAN_CLANG_VERSIONS", "").split(",")))\

        # If there are some GCC versions declared in the environment then we don't default the clang versions
        if not self.clang_versions and not os.getenv("CONAN_GCC_VERSIONS", False):
            self.clang_versions = self.default_clang_versions
```
The gcc test should not only test the environment variable, but also the API argument

**Comment by lasote** [comment]
@kolis I've release 0.5.7. It should fix it. Please, reopen if you still find any problem.
