### ISSUE TITLE
Specified profile 'default' doesn't exist

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan-package-tools#121]
Hi,

I've installed the latest version of conan-package-tools, and ran into an issue when running `build.py`:

>Traceback (most recent call last):
  File "C:\Users\Theo\AppData\Roaming\Python\Python35\site-packages\conans\client\profile_loader.py", line 109, in read_profile
    text = load(profile_path)
  File "C:\Users\Theo\AppData\Roaming\Python\Python35\site-packages\conans\util\files.py", line 128, in load
    with open(path, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Theo\\.conan\\profiles\\default'
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "build.py", line 21, in <module>
    builder.run()
  File "C:\Users\Theo\AppData\Roaming\Python\Python35\site-packages\conan\packager.py", line 311, in run
    self.run_builds()
  File "C:\Users\Theo\AppData\Roaming\Python\Python35\site-packages\conan\packager.py", line 350, in run_builds
    self.mingw_installer_reference, self.runner, self.args)
  File "C:\Users\Theo\AppData\Roaming\Python\Python35\site-packages\conan\create_runner.py", line 38, in __init__
    self.client_cache.profiles_path)
  File "C:\Users\Theo\AppData\Roaming\Python\Python35\site-packages\conans\client\profile_loader.py", line 140, in _load_profile
    profile, declared_vars = read_profile(include, cwd, default_folder)
  File "C:\Users\Theo\AppData\Roaming\Python\Python35\site-packages\conans\client\profile_loader.py", line 118, in read_profile
    "%s" % (profile_name, current_profiles))
conans.errors.ConanException: Specified profile 'default' doesn't exist.
Existing profiles: win32, win64

Indeed, I do not have a `default` profile per se, I defined the default in `conan.conf` instead:

`default_profile = win32`

Still, I do not understand why it tries to load my default profile, shouldn't it generate temporary profiles instead?

It used to work fine, although I had to filter VS builds myself (including DLL with MT, and compiler version, which are now handled by default thanks a lot for that)

**Comment by theodelrieu** [comment]
I symlinked a `default` profile to an existing one, everything works as before.

**Comment by memsharded** [comment]
I think the error is in ``create_runner.py -> TestPackageRunner.__init__``:

```python

        if not os.path.exists(self.client_cache.default_profile_path):
            self.conan_api.create_profile("default", detect=True)

...
        self.profile, _ = _load_profile(self._profile_text, os.path.dirname(self.abs_profile_path),
                                        self.client_cache.profiles_path)
```
Is it possible that your ``win32`` profile si created after? How and when do you create your profiles?

In any case, there is something wrong with that "default" magic string, when the default profile can be named differently (and the question is if we want to automatically create it, with autodetection)

**Comment by theodelrieu** [comment]
I'm on my local machine, so my profiles were created a long time ago. I'm not very familiar with conan-package-tools, so I might be missing your point completely...

**Comment by memsharded** [comment]
Lets wait for @lasote to have a look.

**Comment by lasote** [comment]
Ok, it's a bug. I'll try to solve it and release a patch

**Comment by lasote** [comment]
I've released a new version, please, remove the symlink and try again.

**Comment by theodelrieu** [comment]
Hi, just tried the newest release, everything works fine, thanks!
