### ISSUE TITLE
Ability set package name and version

### ISSUE THREAD

**Issue by birsoyo** [conan-io/conan-package-tools#122]
I would like to able to set the package name and version from ConanMultiPackager.

Basically I would like to able to call `conan create Hello/0.1@username/channel` from ConanMultiPackager.

It would be nice if I could at least set the version from the `build` function so that I can build multiple version in one go. The package name could be specified in ConanMultiPackager's constructor.

**Comment by lasote** [comment]
It was already relased, now the full reference is used.
