### ISSUE TITLE
Print currently built profile to stdout by default

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan-package-tools#125]
Currently, the profile being built is only printed to the logger with INFO logging level. In some cases it's not desirable to see all info log messages, but seeing the current profiles would be important by default. Otherwise it's just a stream of builds being started and when there is an error in a single profile it's hard to figure out which one it is.

**Comment by lasote** [comment]
Which level do you suggest?

**Comment by sztomi** [comment]
I'm suggesting that it should be printed to the stdout, bypassing the logger (i.e. it is visible without raising the log level).

**Comment by lasote** [comment]
Fixed and released in 0.5.28

**Comment by sztomi** [comment]
wow, that was fast, thanks!
