### ISSUE TITLE
Support toolsets for Visual Studio

### ISSUE THREAD

**Issue by wizardsd** [conan-io/conan-package-tools#127]
Hi,
I would expect `ConanMultiPackager` to have Visual Studio toolset option.
Something like this:
```python
builder = ConanMultiPackager(username="username",
  channel="stable",
  visual_versions=["15"],
  visual_toolsets=["v140", "v140_clang_c2"])
```
Could you suggest a workaround or implement this option?

**Comment by lasote** [comment]
We could introduce it and generate the corresponding builds because conan supports the visual toolsets from 0.29, but it only makes sense to specify toolsets for a specific visual version. So probably the parameter should be a dictionary: 

``visual_toolsets={"15": ["v140", "v140_clang_c2"]}``

And for the corresponding environment variable, we could think in a text representation.

**Comment by wizardsd** [comment]
OK, it looks reasonable.

**Comment by ktonon** [comment]
Is this in the works?

**Comment by lasote** [comment]
Not yet, but you could create the builds configurations manually, something like this (not tested):

```
import copy

if __name__ == "__main__":
    builder = ConanMultiPackager(username="myuser")
    builder.add_common_builds()
    all_builds = []
    for settings, options, env_vars, build_requires, reference in builder.items:
        if settings["compiler"] == "Visual Studio" and settings["compiler.version"] == "15":
             # Repeat the below 3 lines for any other toolset
             settings2 = copy.copy(settings)
             settings2["compiler.toolset"] = "v140_clang_c2"
             all_builds.append([settings2, options, env_vars, build_requires])
        all_builds.append([settings, options, env_vars, build_requires])
    builder.builds = all_builds
    builder.run()
```

**Comment by Lnk2past** [comment]
Any progress on getting #157 merged? Would be super useful on my end =) the workaround here is fine, but it would be great to have something cleaner and standard within the tool.

**Comment by lasote** [comment]
No, sorry, I would need some more time to stabilize the 0.17.0 and then to introduce new features.

**Comment by Lnk2past** [comment]
No worries, thanks for the update!

**Comment by luckielordie** [comment]
I'm eager for this functionality :)
