### ISSUE TITLE
Specifying a base profile does not work as I expected

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#138]
https://github.com/conan-io/conan-package-tools#specifying-a-different-base-profile

My particular goal was to "inject" a profile with nothing more than a `build_requires`, which I expected `conan-package-tools` to "merge/include/add" to the profiles it generates and uses.  Instead of merge behavior, I got "overwrite" behavior, where the profile I provided was used as-is, ignoring whatever `conan-packge-tools` generated. 

```
 Using specified default base profile: bazel_installer
**************************************************
******** RUNNING BUILD **********
conan create . abseil/20171101@bincrafters/testing --profile c:\users\jerry\appdata\local\temp\tmpcmadx3conan_package_tools_profiles\profile
include(bazel_installer)
[settings]
[options]
[env]
[build_requires]
```

Is this a bug or am I misunderstanding the original design intention?

**Comment by lasote** [comment]
It should replace the "default" profile with the passed one. But the values corresponding to the generated build should be kept. 

Maybe if you pass a profile containing an "include(default)" could work, but I'm not sure if Conan < 1.0.0.beta4 will generate the default profile automatically. If you install the desired conan version in you CI script, the package tools will use that even for docker: "pip install conan==1.0.0b4".

Could you try what happens?

**Comment by solvingj** [comment]
I found a diff method to achieve my goal, but will try to test this later today.

**Comment by solvingj** [comment]
This has been an obsolete issue for a while now.
