### ISSUE TITLE
Need clarification of purpose for `pure_c` option

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#145]
The description of this option is here: 

> pure_c: (Default True) If your project is C++, pass the pure_c=False, it will add new build combinations using libstdc and libstdc++11 in the `setting compiler.libcxx`.

By default, `setting compiler.libcxx` is not used for hashing/ABI compatibility, so binaries built with `setting compiler.libcxx=libstdc` and `setting compiler.libcxx=libstdc++11` are identical, correct? 

I believe the primary purpose of conan-package-tools is to build the wide range of *different* binaries, so that users don't have to re-build themselves.  Since setting `pure_c=False` effectively doubles the number of builds on Linux and OSX, but half of the binaries are identical by default, then it would seem to be a bit redundant/wasteful to use this option. 

I can see one possible value proposition for this however, which is testing.  If someone wants to build their packages against both `stdc++` libraries under various compilers to make sure it works, then this makes sense.  Is this the primary purpose of exposing this option in conan-package-tools, or have I got something else wrong?

**Comment by solvingj** [comment]
After further testing I believe I was mistaken.  I've rebuilt level8group without `pure_c=False` and now tried building `boost_math` with `pure_c=True` and get the error below.  This indicates fairly clearly that the `libcxx` IS included in the compatibility calculation. 
```
boost_level8group/1.66.0@bincrafters/stable: WARN: Can't find a 'boost_level8group/1.66.0@bincrafters/stable' package for the specified options and settings:
- Settings: arch=x86, build_type=Release, compiler=clang, compiler.libcxx=libstdc++, compiler.version=4.0, os=Linux
- Options: shared=True, boost_atomic:shared=True, boost_container:shared=True

```

**Comment by lasote** [comment]
yes, all settings are included in the SHA unless you tell the opposite in the `package_id()` method.

**Comment by solvingj** [comment]
The request here is to add a much more clear explanation of the implications and use cases of this feature to the readme.  4 experienced packagers went back and forth for 2 days on how it behaves.  In particular, the implications with respect to Conan’s per-compiler defaults. The name of the flag implies that perhaps a value of None is passed for compiler.libcxx if pure_c is left default. This is not the case, Conan’s default libcxx for the compiler is used. So, it seems important to explain.

**Comment by lasote** [comment]
Added new explanation to the readme. Thanks!
