### ISSUE TITLE
Pip using python2 even if running build script with python3

### ISSUE THREAD

**Issue by koliyo** [conan-io/conan-package-tools#147]
If I start my build script like this
```
python3 build.py --build outdated
```
It will still use pip2 to install the conan packages, see `packager.py`

https://github.com/conan-io/conan-package-tools/blob/60ed0b215e704092beb2bead7d0fe3933a30a6c4/conan/packager.py#L406

Assuming pip == pip2, which it normally is

**Comment by lasote** [comment]
I assume that it is hard to know which one to execute, I could add a parameter to specify the "pip" command to run. WDYT?

**Comment by koliyo** [comment]
Yes, a parameter/environment variable would be helpful. Even better would be automatic detection, but that might be a bit tricky if the naming of python/pip binaries are not standardized across platforms.

To detect the running environment you can use `sys.version_info`, and if that is version 3, then try using `pip3`, otherwise `pip2`. Maybe you need something like [this](https://stackoverflow.com/questions/9079036/detect-python-version-at-runtime) to check if the those binares are available. If not, fall back to `pip`.

**Comment by Croydon** [comment]
Since we started moving the build tools slowly to Python 3 this might become obsolete.

**Comment by jgsogo** [comment]
What about...?

```python
import pip

pip.main(['install', 'whatever'])
```

or ``pip._internal.main`` depending on python version.

or running ``<path/to/python> -m pip ...`` where ``<path/to/python> = sys.executable``.
