### ISSUE TITLE
Travis - MacOS PIP not found - xcode 8.3 and 9.2 images

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#148]
Apparently this was reported a while ago, but today is the first day I'm experiencing it.  Anyone else running into it?  The workaround would be to change the `.travis/install.sh` script i guess... so I'm surprised nobody else has raised it. 

https://github.com/travis-ci/travis-ci/issues/8829

Example: 
https://travis-ci.org/bincrafters/conan-glog/jobs/335646463#L1776

**Comment by lasote** [comment]
Is this solved? it was related with the `pyenv` installing? Please comment if it's not solved.
