### ISSUE TITLE
Restrict upload to built packages

### ISSUE THREAD

**Issue by wpalfi** [conan-io/conan-package-tools#149]
ConanMultiPackager uses `conan upload --all`, which uploads all existing packages with matching reference. The expected behaviour would be to upload only the packages built in this run.

v0.10.4

**Comment by memsharded** [comment]
This is reasonable, yes, but just to clarify: packages are not being re-uploaded. Uploads are done only for new or modified packages, hash-check and deduplication checks are done to avoid unnecessary transfers.

**Comment by wpalfi** [comment]
I know. I guess it works perfect for most usecases. But in cases when you change parameters it can easily lead to unwanted uploads of preexisting binary packages.

**Comment by lasote** [comment]
To accomplish that we need to improve the Conan python API to avoid crazy parsing things about the generated IDS. Related to https://github.com/conan-io/conan/issues/1998

**Comment by wpalfi** [comment]
Our workaround is now to remove all packages from the local cache before running build.py:

```
conan remove myref --force
python build.py
```
This works for now but its bad: 
- What if some concurrent build is using the same cache and downloads myref while build.py is running?
- What if build.py fails? We would need to catch errors and restore the old packages...

**Comment by lasote** [comment]
This is still not solved in the released `0.17.0.beta1` beta, but once we improve the output of the conan upload command in 1.3 it now can be solved in conan package tools easily.

Take a look at the changelog, maybe you are interested in any of the new features: https://github.com/conan-io/conan-package-tools/releases/tag/0.17.0-beta1


Please try it and report. `pip install conan-package-tools==0.17.0b1`

**Comment by wpalfi** [comment]
Would still be nice to have this fixed.

**Comment by wpalfi** [comment]
If someone has the same issue: I created a custom build script (without cpt) now:

```python
...
r = api.create(".", user=username, channel=channel, settings=settings, update=True)
id = r['installed'][0]['packages'][0]['id']
api.upload(pattern=fullRef, package=id, remote_name=uploadName)
```

2nd line is quite hacky. Is there a better solution?

**Comment by spiderkeys** [comment]
I'm running into the same issue. 

It's not really a problem that it tries to upload things for a second time. As you mentioned, re-uploads will already match the uploaded packages and will be skipped. The main issue is that it re-compresses the recipe multiple times, and in some of my projects, the compression step can take quite a long time.

For a project that has four build configurations, it looks like it properly calls conan create four times, but then calls conan upload --all on each step, which tries to compress and upload 1, 2, 3, and 4 packages for each conan create call, respectively.

**Comment by lasote** [comment]
@wpalfi is not very hacky, the format is documented here: https://docs.conan.io/en/latest/reference/commands/output/install.html
The only counterpoint is that it is experimental.
I'll incorporate it into the CPT, if something changes in Conan is under control ;)

**Comment by wpalfi** [comment]
> @wpalfi is not very hacky, the format is documented here: ...

Yes, but I was not sure about order of the packages. Is the first package in the list always the installed/created one?

**Comment by danimtb** [comment]
@wpalfi Yes, first recipe installed is the first one of the json output as this is the first node of the dependency graph that is processed.
