### ISSUE TITLE
system_requirements() and docker doesn't play well

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-package-tools#150]
conan package tools has a feature to run builds inside docker.
note that docker invocation always mounts conan cache folder, see https://github.com/conan-io/conan-package-tools/blob/e4be5af6d8a5fb34f3ffc7273166e44bf8b97ba2/conan/create_runner.py#L161
if recipe is using system_requirements() that causes problems.
e.g. first build runs in Docker container, and installs system requirements, leaving record in cache.
then second build runs in the fresh Docker container (which obviously has no dependencies installed), but conan thinks that requirements are installed, because of leftover in cache from the previous run.
/cc @lasote @memsharded

**Comment by memsharded** [comment]
Is this related to https://github.com/conan-io/conan/issues/2332?
Could deserve another option for the env-var that configures that system-requirements shouldn't be cached?

**Comment by lasote** [comment]
Could be a workaround, but the root problem is that I have to clean it between docker builds.

**Comment by SSE4** [comment]
@memsharded  unrelated to https://github.com/conan-io/conan/issues/2332

**Comment by SSE4** [comment]
@lasote do you know workaround which can help?

**Comment by lasote** [comment]
I've released a fix, could you try?

**Comment by SSE4** [comment]
still doesn't work :(

**Comment by lasote** [comment]
Do you have a link to take a look?

**Comment by SSE4** [comment]
https://travis-ci.org/bincrafters/conan-sdl2/builds/338579109

**Comment by lasote** [comment]
Thanks. Nothing obvious. I need some time to revisit it carefully. By the way. There is already a package for libalsa in Conan center, and I think Jack and maybe others are tools of alsa that I could package easily I think. At lease for alsa you shouldn't need the system package. Would be also nice if you try with the alsa package and give feedback.

**Comment by SSE4** [comment]
good idea, I'll try today and let you know

**Comment by SSE4** [comment]
@lasote could you point me to the revision with fix please?

**Comment by lasote** [comment]
https://github.com/conan-io/conan-package-tools/commit/375e3214cc3d241675c129dca11b764ff1b40146

**Comment by lasote** [comment]
I'm debugging it. Will keep updated.

**Comment by lasote** [comment]
I spotted the bug in my implementation. I've seen that you have removed the `global_system_requirements`, Should it work as a workaround, right? I'll release asap again.

**Comment by SSE4** [comment]
nope, global_system_requirements had no effect on this

**Comment by lasote** [comment]
There is something I don't understand, the version I released should fix the global system requirements deleting the shared file for the conanfile. The system requirements at package level should not fail unless you are building the same package more than once. 
What it the latest travis build where you reproduced this bug?

**Comment by SSE4** [comment]
this one https://travis-ci.org/bincrafters/conan-sdl2/jobs/342707021

**Comment by lasote** [comment]
As I suspected there is one package repeated, don't know why. It could be another bug in the package tools.

**Comment by SSE4** [comment]
There is no repeated package, only 4:
x86 release shared
x86 debug shared
x86 release static
x85 debug static

**Comment by lasote** [comment]
search for `RUNNING BUILD **` there are 5

**Comment by lasote** [comment]
builder.run()


    builder.run()

**Comment by SSE4** [comment]
oops xD

**Comment by SSE4** [comment]
I confirm problem is solved. thanks a lot for the help! sorry for the inconvenience caused by mistake in my build.py.
