### ISSUE TITLE
Add support for x86 docker images

### ISSUE THREAD

**Issue by lasote** [conan-io/conan-package-tools#152]
Opt-in, to activate the usage of the great contribution of @uilianries ;)

**Comment by lasote** [comment]
Released with 0.11.0 , but spotted a Conan issue that detects x86_64 as a default profile in the 32 bit images.  Extracted from the README:

```
If you want to run the arch="x86" build inside a docker container of 32 bits you can set the parameter docker_32_images in the ConanMultiPackager constructor or set the environment variable CONAN_DOCKER_32_IMAGES. In this case, the docker image name to use will be appended with -i386.
```

**Comment by lasote** [comment]
Conan package tools now uses `arch_build=x86` when using the 32b images. As a workaround of the detect issue that it is only spotted when using docker, for having a kernel (host kernel) of 64b.

**Comment by uilianries** [comment]
Great! You fixed that problem! Thanks man!
