### ISSUE TITLE
Suddenly getting docker: invalid reference format on travis linux builds

### ISSUE THREAD

**Issue by dimi309** [conan-io/conan-package-tools#155]
Hi everyone,

I've suddenly started receiving this error without having changed much on [my project](https://github.com/dimi309/small3d) since the [last successful build](https://travis-ci.org/dimi309/small3d/builds/334054702?utm_source=github_status&utm_medium=notification):

https://travis-ci.org/dimi309/small3d/jobs/341273789

It only happens on travis linux builds (macos is fine). Any ideas?

Thanks!

**Comment by uilianries** [comment]
```
conan_runner
docker: invalid reference format.
See 'docker run --help'.
Traceback (most recent call last):
  File "build.py", line 16, in <module>
    builder.run()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/conan/packager.py", line 418, in run
    self.run_builds(profile_name=profile_name)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/conan/packager.py", line 465, in run_builds
    docker_entry_script=self.docker_entry_script)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/conan/create_runner.py", line 177, in run
    raise Exception("Error building: %s" % command)
Exception: Error building: sudo docker run --rm -v /home/travis/build/dimi309/small3d:/home/conan/project -v /home/travis/.conan:/home/conan/.conan -e CONAN_RUNNER_ENCODED='{"args": "--build missing", "username": "dimi309", "channel": "stable", "profile": "\ninclude(default)\n\n[settings]\narch=x86_64\nbuild_type=Release\ncompiler=gcc\ncompiler.libcxx=libstdc++11\ncompiler.version=7\n[options]\n\n[env]\n\n[build_requires]\n\n", "conan_pip_package": "conan==1.0.4", "reference": "small3d/master@dimi309/stable"}' -e CONAN_USERNAME=dimi309 -e CONAN_CHANNEL=stable -e CONAN_REMOTES=https://api.bintray.com/conan/dimi309/conan-packages, https://api.bintray.com/conan/bincrafters/public-conan -e CONAN_GCC_VERSIONS=7 -e CONAN_REFERENCE=small3d/master -e CONAN_DOCKER_IMAGE=lasote/conangcc7 lasote/conangcc7 /bin/sh -c "rm -f /home/conan/.conan/conan.conf && cd project && rm -f /home/conan/.conan/profiles/default && (conan profile new default --detect || true) && run_create_in_docker"
```

I didn't understand the error. Docker pointed an invalid reference, however `lasote/conangcc7` is totally valid.

**Comment by dimi309** [comment]
Is the image the only thing that would be called a "reference" in docker terminology? I am beginning to think that I am having a sort of freak accident here. Maybe some combination of parameters that only get put together in my project is causing it.

**Comment by uilianries** [comment]
the only possible problem that I see, could be as you said, a combination of arguments causing the error.

Docker reference is about the image name, in this case is `lasote/conangcc7` but maybe Docker see another name.

I could help you later, running the same command on my machine the checking the exit.

**Comment by lasote** [comment]
I got it, the problem is the `CONAN_REMOTES` with 2 values, not quoted, as environment variable.
I will release asap a fix.

**Comment by lasote** [comment]
@dimi309 relaunch the builds and see what happen.

**Comment by dimi309** [comment]
Now it works. Thank you very much!
