### ISSUE TITLE
upload_repo

### ISSUE THREAD

**Issue by db4** [conan-io/conan-package-tools#156]
I have a private repo among my remotes:
local: http://conan.local:9300 [Verify SSL: True]
 
If I set `CONAN_UPLOAD=http://conan.local:9300` and then build & upload a package via ConanMultiPackager() it gets renamed from `local` to `upload_repo`. Can I avoid that?

**Comment by lasote** [comment]
Sorry, currently it is not possible. I'm labeling this issue and we will take a look if we can do something.

**Comment by lasote** [comment]
I upvote myself to this issue, if we can name the upload repo we can use a `CONAN_PASSWORD_{REPO_NAME}` env var and have multiple credentials stored in CI depending on the remote to be used.

**Comment by wpalfi** [comment]
An existing remote is not only renamed. It is removed and then added as `upload_repo`. This leads to broken associations of all packages from this remote. 

Btw. this is also a problem when I want to rename a remote locally. What about adding a `conan remote rename` command that updates all associations in the registry?

**Comment by lasote** [comment]
The conan package tools were intended to run in a clean environment (CI mostly), This is one of the things should be changed to adapt to a non-clean environment.

**Comment by memsharded** [comment]
Yes, a ``conan remote rename`` makes sense, is doable and not difficult. But please open an issue for that in the main conan repo. Thanks!

**Comment by wpalfi** [comment]
> The conan package tools were intended to run in a clean environment (CI mostly), This is one of the things should be changed to adapt to a non-clean environment.

Yes, I'm talking about our CI server. We dont want to create a separate conan cache for each project. That would require a lot of disk space and slow down everything. So the restrictions for a shared cache are:
- There can be only one remote used for uploading
- It must be called `upload_repo`

Correct? I just wanted to understand. Thats ok for us.

**Comment by lasote** [comment]
Yes, I think these are the restrictions right now.

**Comment by sourcedelica** [comment]
What about, as an alternative to `CONAN_UPLOAD`/`CONAN_LOGIN_USERNAME`/`CONAN_PASSWORD` have an environment variable `CONAN_UPLOAD_REMOTE` that selects the remote to upload to, and assumes that you have already run `conan user` in the user that CI uses.  I would like this because it means I don't need to have the remote password in a script or in the CI plan.

**Comment by lasote** [comment]
I'm in the middle of a very big refactor that includes improvements for this too. Stay tuned.

**Comment by lasote** [comment]
I relased the `0.17.0.beta1` with better remote management, now you can specify the name and ssl flag in the remotes and also if the remote exists, the name (and the registry) will be kept.
Take a look at the changelog: https://github.com/conan-io/conan-package-tools/releases/tag/0.17.0-beta1

Please try it and report. pip install conan-package-tools==0.17.0b1

**Comment by sourcedelica** [comment]
Looks good!

**Comment by solvingj** [comment]
@db4  @lasote ping to close this.
