### ISSUE TITLE
Support os.subsystem 

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan-package-tools#162]
In order for code like `if self.settings.os.subsystem == "msys2"` to work the subsystem needs to be set in the profile.  Currently Conan Package Tools does not add subsystem to profiles.  This means that recipes need to continue to rely on `if self.settings.os == "Windows" and self.settings.compiler == "gcc"`.

**Comment by lasote** [comment]
The goal of the subsetting `os.subsystem` is not to let Conan/recipes know if you have to build it with a subsystem. This subsetting is used to model if you are building native `cygwin` or native `msys2` (depending on its own runtime dll).

A recipe itself has to know `if self.settings.os == "Windows" and self.settings.compiler == "gcc"` if they need a subsystem to be compiled or not.

Clarified that, you can customize the settings of the builds that will be run in conan_package_tools, that is only translating the "build" objects to a profile, but I think you don't want to to this:

```
from conan.packager import ConanMultiPackager

if __name__ == "__main__":
    builder = ConanMultiPackager(username="myuser")
    builder.add_common_builds()
    filtered_builds = []
    for settings, options, env_vars, build_requires, reference in builder.items:
        if settings["os"] == "Windows" and settings["compiler"] == "gcc":
             settings["os.subsystem"] = "msys2"
             filtered_builds.append([settings, options, env_vars, build_requires])
    builder.builds = filtered_builds
    builder.run()
```

**Comment by lasote** [comment]
I recently reviewd a Bincrafters recipe using subsystems, you can take a look here: https://github.com/bincrafters/conan-giflib/blob/stable/5.1.3/conanfile.py

**Comment by sourcedelica** [comment]
Ok - thanks.  I definitely had the wrong idea.

**Comment by sourcedelica** [comment]
The linked recipe did not use `os.subsystem`.  I'm interested to know which use cases where that be used.

**Comment by lasote** [comment]
Only to model the native subsystems apps. Definitely not a common use case.
