### ISSUE TITLE
CONAN_DOCKER_USE_SUDO is used to start container

### ISSUE THREAD

**Issue by leugenea** [conan-io/conan-package-tools#163]
When I've run build in docker, script prompted for password for sudo.
That looks strange because my user can execute docker commands (like `docker run …`) without sudo.
I've looked into code and found that in `DockerTestPackageRunner.run` variable `self.sudo_command` is used 
According to docs `CONAN_DOCKER_USE_SUDO` env variable setted to `False` must disable running conan with sudo, but it does the opposite: it disables running of container with sudo but commands inside docker container don't depend on this variable.

**Comment by lasote** [comment]
You mean the `sudo pip install`? or any other command to?

**Comment by leugenea** [comment]
I've read docs and source code again. Looks like I've "parsed" `CONAN_DOCKER_USE_SUDO` wrongfully. Variable does what it should do.
Anyway, docs say:

**CONAN_DOCKER_USE_SUDO** Force to use "sudo" when invoking conan. By default, only with Windows. "False" to deactivate.

What command is run with "sudo" according to docs?

**Comment by lasote** [comment]
The "docker" itself I think.

**Comment by leugenea** [comment]
Looks like the behavior is OK, but documentation is completely wrong.

**Comment by lasote** [comment]
I changed the README and slightly changed the behavior. In the `0.17.0b1` I kept the old option but now exists ``CONAN_USE_SUDO``, it will affect both the docker launch and the `pip install` commands. 
Let me know if it works better for you.

Please try it and report. `pip install conan-package-tools==0.17.0b1`

**Comment by leugenea** [comment]
Looks OK, thanks!
