### ISSUE TITLE
LXD images

### ISSUE THREAD

**Issue by jeremy-coulon** [conan-io/conan-package-tools#164]
Hello!
My use case is that I am running latest Ubuntu LTS as a dev machine but I want to build packages that will be executed on RedHat 6 distribution. I cannot use my default toolchain because of glibc ABI issues (RH6 has a very old glibc).
I saw that conan-package-tools has support for Docker images and I thought that it may be a good idea to add support for LXD images too. That would allow users to build package across-distrib.
What do you think?

**Comment by lasote** [comment]
Hi Jeremy, thanks for the info. Unfortunately, I have no experience with LXD images. I don't understand how it could help better than docker regarding the glibc?

**Comment by jeremy-coulon** [comment]
I am not an expert in LXD or Docker either.
As far as I understand docker allows you to package apps (with their dependencies) into an image. Whereas LXC/LXD allows you to package an entire Linux distribution into an image but it has less overhead than a VM.

**Comment by lasote** [comment]
But for the scope of conan, if you build packages using a glibc X won't be either compatible with a glibc Y, right? So other containers won't help with that.

**Comment by jeremy-coulon** [comment]
glibc is mostly backward compatible.
I can compile code with glibc 2.12 (RH6) and execute it with glibc 2.23 (Ubuntu 16.04) without any problem.

**Comment by lasote** [comment]
So, you could use a docker image with a very old glibc to build your packages, right?

**Comment by jeremy-coulon** [comment]
If that's possible, yes!

**Comment by lasote** [comment]
Which GCC version comes with the redhat 6?

**Comment by jeremy-coulon** [comment]
gcc 4.4

**Comment by lasote** [comment]
Wow, we currently only have gcc 4.6 image that comes with glibc 2.15. 
We have all the dockerfiles here: https://github.com/conan-io/conan-docker-tools
The way is to write a Dockerfile with a gcc 4.4 / glibc 2.12.

**Comment by uilianries** [comment]
Hi @jeremy-coulon !

Conan Docker Tools now offers images based on Centos 6:

- https://hub.docker.com/r/conanio/gcc7-centos6-x86
- https://hub.docker.com/r/conanio/gcc7-centos6

Both images are using glibc 2.12.

Also, we have a package to override the glibc if you are interested:
https://github.com/bincrafters/conan-glibc_version_header

Is it enough for you case?

**Comment by jeremy-coulon** [comment]
Hi @uilianries 

Thank you for getting back to my use case.

Unfortunately, I can't use docker in my company.

But glibc_version_header package seems promising. I will try it out.

Thanks.
