### ISSUE TITLE
Support non-git repositories

### ISSUE THREAD

**Issue by fedterzi** [conan-io/conan-package-tools#171]
I'd like to be able to use conan-package-tools using perforce and jenkins (and storing packages in artifactory), in the current release (correct me if I'm wrong) this is not possible because `ci_manager` tries to call `git log`:

```
fatal: Not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    builder = ConanMultiPackager(visual_versions=["15"], gcc_versions=["6"], clang_versions=["9.0"], archs=["x86_64"])
  File "/Library/Python/2.7/site-packages/conan/packager.py", line 106, in __init__
    self.ci_manager.get_commit_build_policy() or \
  File "/Library/Python/2.7/site-packages/conan/ci_manager.py", line 54, in get_commit_build_policy
    matches = prog.match(msg)
```

**Comment by lasote** [comment]
Hi! Thanks for reporting. I've released `0.15.3` catching any kind of error with git. 
git was used only to try to detect the commit message, but it is not very important, just to be able to use the [special commit tags](https://github.com/conan-io/conan-package-tools#commit-messages-reference). 
Please try now and tell me if it works!

**Comment by fedterzi** [comment]
Thank you for your support, it seems to catch a few git fatals, but it fails in the `conan create` step because it doesn't  resolve the path of the conanfile (it is in the same folder, so it should be `.`):

```
 >> conan create  mypackage/0.1.0@mychannel/stable --profile /tmp/tmpdKMv9Vconan_package_tools_profiles/profile

****************************************************************************************************
+----------------------+
| Profile              |
|----------------------|
| include(default)     |
|                      |
| [settings]           |
| arch=x86_64          |
| build_type=Release   |
| compiler=apple-clang |
| compiler.version=9.0 |
| [options]            |
| zlib:shared=True     |
| [env]                |
|                      |
| [build_requires]     |
+----------------------+

[conan_create]
WARN: Migration: This conan installation doesn't have settings yet
WARN: Nothing to migrate here, settings will be generated automatically
WARN: Migration: Removing old lock files
WARN: Migration: Removing old lock files finished

usage: conan create [-h] [-ne] [-tf TEST_FOLDER] [-tbf TEST_BUILD_FOLDER] [-k]
                    [-kb] [-j JSON] [-m [MANIFESTS]]
                    [-mi [MANIFESTS_INTERACTIVE]] [-v [VERIFY]] [-u]
                    [-pr PROFILE] [-r REMOTE] [-o OPTIONS] [-s SETTINGS]
                    [-e ENV] [-b [BUILD]]
                    path reference
conan create: error: too few arguments
ERROR: Exiting with code: 2
Error while executing:
         conan create  mypackage/0.1.0@mychannel/stable --profile /tmp/tmpdKMv9Vconan_package_tools_profiles/profile
```

**Comment by memsharded** [comment]
Yes, you always need to specify the ".": ``conan create <path> <pkg-reference>`` => ``conan create . user/channel``, from conan 1.0. Is it possible that you had an older conan version (<1.0) installed?

**Comment by lasote** [comment]
This is weird, Conan package tools always specify the "." for Conan >=1.0.
Could be something wrong with your setup, yes. Let us know if we can assist.

**Comment by fedterzi** [comment]
@memsharded Yes that was the case, I had 2 different versions of conan, 0.30.0 on ~/Library/Python/ and 1.2.1 on /Library/Python.

I uninstalled 0.30.0 and now everything works fine!
Thank you @lasote and @memsharded for all your help 🥇
