### ISSUE TITLE
CONAN_DOCKER_IMAGE_SKIP_UPDATE doesn't work with conan docker tools

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#178]
None of the images in conan_docker_tools install `conan_package_tools` by default.  So, if one uses `CONAN_DOCKER_IMAGE_SKIP_UPDATE` or the constructor parameter of the same name, builds will fail because there will be no script named `run_create_in_docker` in the container.  

Let me know if i've missed something.  If not, I can understand why one would skip installing `conan_package_tools` in the container, but since you do install `conan` in the container... it makes less sense.

**Comment by lasote** [comment]
You are right. Let me check how it should behave.

**Comment by lasote** [comment]
Well, the use case why I introduce that is people using their own images, where, as you very well explained, should have the CPT installed. What is your use case? Why is it needed for you avoid the upgrade? I need to know to provide a better approach.

**Comment by solvingj** [comment]
It's not a big deal.  I was doing development on a PR for conan package tools, re-running `python build.py` repeatedly.  This was just a surprising discovery, and felt it violated the principle of least-astonishment.  It takes at least 30 seconds extra to do all the install of CPT, plus there's an ugly flood of warnings in the logs.  It was easily streamlined by creating a separate container locally which simply adds CPT to your images.  However, I was testing with your containers specifically because I needed to make sure it works with them "as-is".  Once I get it working with my image, I still need to go back and test with your images to be sure I didn't break anything else.

**Comment by lasote** [comment]
I added a parameter `always_update_conan_in_docker`/`CONAN_ALWAYS_UPDATE_CONAN_DOCKER` in the `0.17.0beta1` to always installs conan and cpt in the docker images, so the update+commit process is skipped because it is not necessary. Let me know if it helps.

**Comment by lasote** [comment]
Yes, if you specify `CONAN_ALWAYS_UPDATE_CONAN_DOCKER`, the docker container, before running the create, will always install conan and cpt. And the process of committing the image is avoided because it is useless.

**Comment by solvingj** [comment]
That seems like it should work, will reopen if it doesn't.
