### ISSUE TITLE
builds against libstdc++11 not being generated?

### ISSUE THREAD

**Issue by DEGoodmanWilson** [conan-io/conan-package-tools#181]
Hello! I'm trying to understand why, for this Travis build, `ConanMultiPackager.add_common_builds()` seems only to be generating builds with `libstdc++` and not also for `libstdc++11`. It seems that `get_linux_gcc_builds()` should be generating builds for both, but that is not happening here:

https://travis-ci.org/DEGoodmanWilson/conan-mongocxx/jobs/367842153

Can you advise what I might be doing to cause this?

**Comment by uilianries** [comment]
you need to add `pure_c=False` to generate builds with *libstdc++11*

https://github.com/conan-io/conan-package-tools#generating-the-build-configurations-automatically

**Comment by DEGoodmanWilson** [comment]
OMG kill me now. Of course. So sorry.

**Comment by uilianries** [comment]
![](https://media.giphy.com/media/NFPIJcCMoUs5q/giphy.gif)
