### ISSUE TITLE
Need two CONAN_DOCKER_SUDO variables

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#185]
There are two places where `sudo` might be used in Conan Package Tools:
1. When invoking docker commands:  `sudo docker run ...`
2. When invoking pip commands inside the container:  `sudo pip install conan_package_tools...`

These are fundamentally different and we need separate handling, so please start by defining a separate variable for inside the container.  In particular, Linux containers on Windows will need `sudo` inside the container, but not outside.

**Comment by lasote** [comment]
to be released in beta2
