### ISSUE TITLE
Travis GCC 5.2, 5.3 builds not scheduled correctly

### ISSUE THREAD

**Issue by bilke** [conan-io/conan-package-tools#19]
In [my package](https://github.com/bilke/conan-vtk) I set up two pages in the [Travis-config](https://github.com/bilke/conan-vtk/blob/master/.travis.yml) so that for every gcc version there is one build job for debug and one for release builds (I am just building for x86_64). This works fine for all gcc versions except [5.2](https://travis-ci.org/bilke/conan-vtk/jobs/121675790) and [5.3](https://travis-ci.org/bilke/conan-vtk/jobs/121675792) where each of the two Travis builds builds debug **and* release and therefore hit the build timeout limit.

Is there anything I am doing wrong? Thanks a lot!

**Comment by lasote** [comment]
So sorry for the delay, the builds are longer because for gcc > 5 different conan package tools by default add a new settings with 2 different configurations compiler.libcxx="libstdc++" and compiler.libcxx="libstdc++11" . You can just add more pages to these versions:

```
matrix:
    - CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
```

**Comment by bilke** [comment]
Ah ok thanks!
