### ISSUE TITLE
ERROR: Remote recipe is newer than local recipe

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#192]
Getting this with Jenkins, I thought I remember seeing that CPT had a force built in to override this error but I guess not.  Should it?

```
conans.errors.ConanException: Remote recipe is newer than local recipe: 
 Remote date: 1524688506
 Local date: 1524688499
```

**Comment by solvingj** [comment]
Need to add `force=True` here: 

https://github.com/conan-io/conan-package-tools/blob/develop/cpt/uploader.py#L23

**Comment by lasote** [comment]
Yes, I will force it because it was forced before. but the real question is, why is it happening? do you have different times between slave machines?

**Comment by solvingj** [comment]
yes, it looks like about 7 seconds difference.  This is a wider gap than it should be, but I would not say it's terribly uncommon for them not to agree.  Is there a threshold baked into the comparison?  For example, I would say that if they are less than 1 second apart, they're probably equivalent.  I guess the MOST robust thing to do (although I don't THINK I would recommend it), is for the conan client to compare client and server times at the start of the transaction and identify the offset between them.  Then, the server could always factor in that offset in the calculation. Anyway, we can close if you want.

**Comment by bilke** [comment]
Is there a reason that `force=True` is missing for Conan >= 1.8:

https://github.com/conan-io/conan-package-tools/blob/develop/cpt/uploader.py#L41-L45

**Comment by lasote** [comment]
With the usage of Conan 1.8 (with new upload policies in place) it shouldn't be necessary if only the timestamp is changing it will upload it anyway. 
Is it breaking something on your side?

**Comment by bilke** [comment]
No thanks, I just ran into [these line ending issues](https://docs.conan.io/en/latest/faq/using.html#packages-got-outdated-when-uploading-an-unchanged-recipe-from-a-different-machine)...

**Comment by michaelmaguire** [comment]
I'm experiencing this error from my Jenkins:

```
----------------------------------------
ERROR: Remote recipe is newer than local recipe: 
 Remote date: 1544524100
 Local date: 1539161431
```

The upload seems to be proceeding, but it causes my Jenkins job to appear to have failed.

How would I make use of this ```force=True``` workaround?

**Comment by michaelmaguire** [comment]
This this ticket is closed, I've raised a new:

https://github.com/conan-io/conan-package-tools/issues/312 "ERROR: Remote recipe is newer than local recipe (cont.)"

**Comment by lasote** [comment]
I would try to explain what is this issue about and why we don't force the uploads by default.

Conan, when you upload a recipe or a package, check the manifest containing the checksums of the recipe files (usually just a conanfile.py). If the contents are the same, Conan doesn't care about the dates, because, actually will skip the real upload as it is already there.

But if the recipe is different, by default, we want to warn the user if you are trying to overwrite a newer recipe. How can it happen? well, if a slave takes less time to build a package than others, it could happen that the recipe uploaded is newer than the local one.

But why are they different? Usually, this is an issue with the CRLF characters. If you see some traces like the following you have the answer:

```
Local 'conanfile.py' using '\r\n' line-ends
Remote 'conanfile.py' using '\n' line-ends
```

Otherwise, if they are different, maybe you are mixing or overriding on purpose different recipes in the CI? Several consecutive pushes? Should it be happening? These are some questions to clarify before take the decission of forcing an upload. 
Please, shed some light about you use case and we could enable a configuration to opt-in the package overwritting.

@michaelmaguire you mentioned a promotion process, could you explain a bit more?

**Comment by michaelmaguire** [comment]
> you mentioned a promotion process, could you explain a bit more?

It's nothing too fancy -- we have a locked down Artifactory that only the official build user can published to.  Our Jenkinsfile for this 'promotion' project accepts as parameters repo and branch, and tries to run 

```
conan create .. -s build_type=Release
conan create .. -s build_type=Debug
conan upload --all
```

It's single Jenkins pipeline job, running one job at a time.

I use:

```
        node {
            label 'WINDOWSBUILDSERVERS'
        }
```

to select a single node that will be used for the whole job, so not sure where any concurrency issues would come from.

**Comment by michaelmaguire** [comment]
```
Package is up to date, upload skipped                                 

----------------------------------------
Remote manifest:
Time: 2018-12-11 10:28:20
conanfile.py, MD5: 611604d1f5e7629539c1935e83bc985a
export_source/CMakeLists.txt, MD5: 44393e04f71ac15b6d46280aaba7528a

Local manifest:
Time: 2018-10-10 08:50:31
conanfile.py, MD5: 762f77d5fde6a5421c4abe8c491ecfba
export_source/CMakeLists.txt, MD5: 44393e04f71ac15b6d46280aaba7528a

Local 'conanfile.py' using '\n' line-ends
Remote 'conanfile.py' using '\n' line-ends

----------------------------------------
ERROR: Remote recipe is newer than local recipe: 
 Remote date: 1544524100
 Local date: 1539161431
```

**Comment by lasote** [comment]
```
Local manifest:
Time: 2018-10-10 08:50:31
```

Looks like an old version of the package. The conanfile is changing. Maybe you should do a diff between the remote and the "local" and see which is the good one. You could always remove the remote one if it is not the correct one.

**Comment by michaelmaguire** [comment]
This is bizarre.  I only Conanized this library early this morning.  There have been no previous versions of it.

I've verified the actual build node that was used for this build and checked the date on that build server:

> C:\Users\mmaguir1>date
> The current date is: Fri 12/21/2018
> Enter the new date: (mm-dd-yy)

**Comment by michaelmaguire** [comment]
The only other machine I've ever built this on is my local dev server:

> E:\DevelopBp\mmaguir1\src\nx\AcquisitionSupport>date
> The current date is: Fri 12/21/2018

**Comment by lasote** [comment]
Very weird. That date is calculated in the "export" (also part of the "create")

**Comment by michaelmaguire** [comment]
Ahh.  Wait.  I think I've just discovered how I was mistaken.

The error in this cases wasn't coming from the package I tried to build for the first time.  It was from one of the other packages that was downloaded to enable the desired build.

I have this in my Jenkinsfile:

```
                    // Make sure we have nothing in our local cache as we push everything
                    // in our cache up.
                    // TODO: figure out how we can only upload exactly what we built below,
                    // so we don't have to nuke the cache each time.
                    conanClient.run(command: 'remove --force *')

                    // Old, manual way
                    //def buildInfo = conanClient.run(command: 'create . PORT/stable -s compiler="Visual Studio" -s compiler.version=14 -s compiler.toolset="v140_xp" -s build_type=Debug')
                    //conanClient.run(buildInfo: buildInfo, command: 'create . PORT/stable -s compiler="Visual Studio" -s compiler.version=14 -s compiler.toolset="v140_xp" -s build_type=Release')

                    // Nice way using configured profiles
                    def buildInfo = conanClient.run(command: 'create . PORT/stable --profile vs2015_14_v140_xp_Debug')
                    conanClient.run(buildInfo: buildInfo, command: 'create . PORT/stable --profile vs2015_14_v140_xp_Release')
               

                    // Upload everything we just build from our local cache.
                    String command = "upload * --all -r ${remoteNameConanNxStable} --confirm"
```

which I think is probably a bad shortcut.

**Comment by lasote** [comment]
The cache should be empty each time, I think the plugin creates a dedicated cache per build, so the remove might be unnecessary.

**Comment by michaelmaguire** [comment]
OK, I can remove the remove, but is there a better way to selectively upload only the built from source package?

**Comment by lasote** [comment]
Not directly but let me try a thing.

**Comment by lasote** [comment]
In this example I use the ``--json`` argument to ``conan create`` to get the created reference with an auxiliary function. I will add this to the Conan => integrations => jenkins:

```groovy
def created_ref(a_json){
    def ref
    a_json["installed"].each { item ->
        def exported = item['recipe']['exported']
        if(exported){
            ref = item["recipe"]["id"]
            return ref
        }
    }
    ref
}

node("Linux") {
    sh "docker pull conanio/gcc7"
    docker.image("conanio/gcc7").inside {
        def server = Artifactory.server "ArtifactoryConan"
        def client = Artifactory.newConanClient()
    
        stage("Get project"){
            git branch: "release/1.2.11", url: "https://github.com/conan-community/conan-zlib.git"
        }
    
        stage("Create"){
            client.run(command: "--version")
            client.run(command: 'create . PORT/stable --json create.json')
            def my_json = readJSON file: "create.json"
            def ref = created_ref(my_json)
            echo "REF INSTALLED => ${ref}"
            //client.run(command: 'upload ${ref} --all -r ${remoteNameConanNxStable} --confirm')
    
        }
    }
}
```

**Comment by lasote** [comment]
Note: It requires this plugin: https://plugins.jenkins.io/pipeline-utility-steps

**Comment by tonka3000** [comment]
So, my problem seems to be the same problem as from conan-io/conan#4001

**Comment by michaelmaguire** [comment]
@lasote thanks, this --json and created_ref worked like a treat!

**Comment by michaelmaguire** [comment]
Question:

Can I ask above why we used:

```
        def exported = item['recipe']['exported']
```

and not, e.g.:

```
        def built = item['recipe']['built']
```

?

**Comment by lasote** [comment]
Sure, if you are building more than one pick all you need.

**Comment by NealRame** [comment]
Hi, I have the same problem with **conan 1.27.1** and **conan_packages_tools 0.34.0** when uploading the package to our remote.

```
ERROR: Lame/3.100-34@****: Upload recipe to '****' failed: Remote recipe is newer than local recipe: 
 Remote date: 1594836302
 Local date: 1594836300
```

**Comment by uilianries** [comment]
Hi @NealRame, please, read https://docs.conan.io/en/latest/faq/using.html#packages-got-outdated-when-uploading-an-unchanged-recipe-from-a-different-machine

You are not alone, this problem is well known: https://github.com/conan-io/conan/issues/1400

Please, open a new issue in the future.

**Comment by NealRame** [comment]
@uilianries thank you :-)
