### ISSUE TITLE
cleanup conan_runner container on various failures

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#193]
CPT current exits after various failures surrounding the `conan_runner` docker container, leaving it dangling.  Then, subsequent runs of CPT will fail with the error:

`docker: Error response from daemon: Conflict. The container name "/conan_runner" is already in use by container`

We need to cleanup `conan_runner` reliably after every run.

**Comment by lasote** [comment]
conan_package_tools==0.17.0b4
Released
