### ISSUE TITLE
Expose keep-source

### ISSUE THREAD

**Issue by Lnk2past** [conan-io/conan-package-tools#207]
For debugging purposes this would be very useful to have. Is there a way to do this? I looked around but couldn't find anything.

Currently using:
```
conan               1.2.3
conan-package-tools 0.16.5
```

**Comment by lasote** [comment]
I think it could be done, but take into account, when using docker the builds are isolated, so the keep source would be useless. For builds run on the host, it could help. 
Please, update to the 0.17.1, there are big changes since 0.16.5

**Comment by Lnk2past** [comment]
hey @lasote, thanks for the tip, I'll work through the upgrade today =) 

As far as this is concerned, I didn't realize there is already the ability to forward args to the ```ConanMultiPackager```. Additionally, I didn't realize it would also pull from ```sys.argv``` automatically if none are provided to it.

I am writing a master builder script that uses ```argparse``` to configure my inputs for that script; I had run into an issue where ```ConanMultiPackager``` was trying to use my arguments from ```sys.argv``` and so early on I wiped it out after parsing my own arguments. Knowing this now, I have a pretty good work around for my script, so this is no longer an issue.
