### ISSUE TITLE
default apple-clang

### ISSUE THREAD

**Issue by lasote** [conan-io/conan-package-tools#214]
Update with 9.0 and 9.1 and Visual 15

**Comment by Croydon** [comment]
Visual 15 is pretty much https://github.com/conan-io/conan-package-tools/pull/56

Are the problems to find the path of Visual 15 solved in some way now?

**Comment by Croydon** [comment]
This is done via https://github.com/conan-io/conan-package-tools/pull/285/files

although I would still like to know how the problem with finding Visual 15 is resolved?

**Comment by lasote** [comment]
Yes, that shouldn't be an issue anymore
