### ISSUE TITLE
building package with requirements

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan-package-tools#226]
Hi,
I'm trying to build a package. When I add the function "requirements(self)" to the recipe with an dependency to e.g. zlib (conan/stable) then conan stopps processing with the following error:

conans.errors.ConanException: More than 1 conanfile in the file

exception origin: ...\conans\client\loader_parse.py", line 45, in _parse_module

I tested creating the package by using the "conan create" command and it worked without any problems.
But creating it with the conan-package-tools builder will result in a failure if I add any dependency in form of a requirement.

Best regards
Johannes

**Comment by lasote** [comment]
Hi, I would need some trace of the error.

**Comment by Johnnyxy** [comment]
The following is trace output.
I shortened the paths (cut leading parts) of ".conan" and replaced it with "..." and the python path and replaced it with "PYTHON".

> parse_module ({module: <module 'conanfile' from '...\\.conan\\data\\testpkg\\4.2.1\\rms\\testing\\export\\conanfile.py'>}, {filename: conanfile})
inspected ({name: testpkgConan}, {attr: <class 'conanfile.testpkgConan'>})
result was none
parse_module ({module: <module 'conanfile' from '...\\.conan\\data\\zlib\\1.2.11\\conan\\stable\\export\\conanfile.py'>}, {filename: conanfile})
inspected ({name: testpkgConan}, {attr: <class 'conanfile.testpkgConan'>})
result was none
inspected ({name: ZlibConan}, {attr: <class 'conanfile.ZlibConan'>})
result was already set ({result: <class 'conanfile.testpkgConan'>})
Traceback (most recent call last):
  File "PYTHON\lib\site-packages\conans\client\loader_parse.py", line 18, in load_conanfile_class
    return _parse_module(loaded, filename)
  File "PYTHON\lib\site-packages\conans\client\loader_parse.py", line 45, in _parse_module
    raise ConanException("More than 1 conanfile in the file")
conans.errors.ConanException: More than 1 conanfile in the file

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "build.py", line 12, in <module>
    builder.run()
  File "PYTHON\lib\site-packages\cpt\packager.py", line 335, in run
    self.run_builds(base_profile_name=base_profile_name)
  File "PYTHON\lib\site-packages\cpt\packager.py", line 411, in run_builds
    r.run()
  File "PYTHON\lib\site-packages\cpt\runner.py", line 72, in run
    profile_name=self._profile_abs_path)
  File "PYTHON\lib\site-packages\conans\client\conan_api.py", line 76, in wrapper
    return f(*args, **kwargs)
  File "PYTHON\lib\site-packages\conans\client\conan_api.py", line 328, in create
    test_build_folder, test_folder, conanfile_path)
  File "PYTHON\lib\site-packages\conans\client\cmd\create.py", line 51, in create
    keep_build=keep_build)
  File "PYTHON\lib\site-packages\conans\client\manager.py", line 357, in install
    deps_graph = graph_builder.load_graph(conanfile, False, update)
  File "PYTHON\lib\site-packages\conans\client\graph\graph_builder.py", line 44, in load_graph
    loop_ancestors, aliased, check_updates, update)
  File "PYTHON\lib\site-packages\conans\client\graph\graph_builder.py", line 110, in _load_deps
    new_options, new_loop_ancestors, aliased, check_updates, update)
  File "PYTHON\lib\site-packages\conans\client\graph\graph_builder.py", line 107, in _load_deps
    aliased, check_updates, update)
  File "PYTHON\lib\site-packages\conans\client\graph\graph_builder.py", line 213, in _create_new_node
    reference=requirement.conan_reference)
  File "PYTHON\lib\site-packages\conans\client\loader.py", line 37, in load_conan
    result = load_conanfile_class(conanfile_path)
  File "PYTHON\lib\site-packages\conans\client\loader_parse.py", line 20, in load_conanfile_class
    raise ConanException("%s: %s" % (conanfile_path, str(e)))
conans.errors.ConanException: ...\.conan\data\zlib\1.2.11\conan\stable\export\conanfile.py: More than 1 conanfile in the file

For debugging I inserted 3 print outputs into conan's _parse_module function:
```python
def _parse_module(conanfile_module, filename):
   print("parse_module ({module: %s}, {filename: %s})" % (conanfile_module, filename))    
   result = None
    for name, attr in conanfile_module.__dict__.items():        
        if name[0] == "_":
            continue
        if (inspect.isclass(attr) and issubclass(attr, ConanFile) and attr != ConanFile and
                attr.__dict__["__module__"] == filename):
            print("inspected ({name: %s}, {attr: %s})" % (name, attr))
            if result is None:
                print("result was none")
                result = attr
            else:
                print("result was already set ({result: %s})" % (result))
                raise ConanException("More than 1 conanfile in the file")
        if (inspect.isclass(attr) and issubclass(attr, Generator) and attr != Generator and
                attr.__dict__["__module__"] == filename):
            registered_generators.add(attr.__name__, attr)
    if result is None:
        raise ConanException("No subclass of ConanFile")
    return result
```

**Comment by lasote** [comment]
The OpenSSL recipe is using the `requirements` to zlib and it is working properly. I cannot reproduce the issue. Could you prepare a minimum example failing and share it?

**Comment by Johnnyxy** [comment]
I'll have to prepare one. Need some minutes.

**Comment by Johnnyxy** [comment]
Ah found the error.

The problem was, I have a function in the conanfile.py. In the build.py I use this function also.
So I had an import at the beginning von the build.py
```python
from conanfile import MYFUNCTION
```
When I remove this line everything runs fine. So it was a circular reference and the parsing function of conan parsed something it has already processed.



Thanks anyway :)
I'll close the topic as the problem was found has been "resolved".
