### ISSUE TITLE
add_common_builds for Windows assumes mingw

### ISSUE THREAD

**Issue by joeabbey** [conan-io/conan-package-tools#23]
After upgrading to 0.2.20, I'm getting:

```
Traceback (most recent call last):
  File "build.py", line 18, in <module>
     builder.add_common_builds(pure_c=False)
   File "C:\Users\Jenkins\AppData\Roaming\Python\Python27\site-packages\conan\packager.py", line 124, in add_common_builds
     if self.mingw_builds(pure_c):
   File "C:\Users\Jenkins\AppData\Roaming\Python\Python27\site-packages\conan\packager.py", line 95, in mingw_builds
    version, arch, exception, thread = config
    ValueError: need more than 1 value to unpack
```

Looks like mingw_builds needs to check if mingw_configurations is empty?

```
        for config in self.mingw_configurations:
            version, arch, exception, thread = config
```

**Comment by memsharded** [comment]
Yes, this is a bug, sorry for the inconvenience. I have just submitted a PR #24 that should fix it.
While a new release of conan-package-tools is done, you could try to install a previous version of conan-package-tools with pip. Or maybe, add just one mingw configuration to your build, that would also help to test this new feature. You could add to your build.py something like:

```python
builder = ConanMultiPackager(..., mingw_configurations=["4.9@x86_64@seh@posix"])
```

Thanks for reporting!

**Comment by memsharded** [comment]
I have had success reverting to 0.2.16 in my appveyor.yml:

```bash
install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools==0.2.16 # It install conan too
  - pip.exe install conan --upgrade
  - conan user # It creates the conan data directory
```

**Comment by joeabbey** [comment]
Thanks for fixing! Looking forward to 0.2.21 :-D

**Comment by memsharded** [comment]
Hi! I think we better keep this issue open, until 0.2.21 is released, so other users can easily see the status of this issue. We have a policy for the main conan repo, is to add a "fixed" label, but do not close the issue until it is released and tested in the release. Cheers!

**Comment by lasote** [comment]
0.2.21 is available. Sorry for the delay!
