### ISSUE TITLE
Trigger new test by Conan release

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-package-tools#233]
Hi!

I have used Gitlab triggers to start a new build for project B, when the project A have a new releases.

WDYT about start a new CI job for CPT when a Conan release is created?

My intention is to make sure that any new release will not break CPT (in the future). I saw this problem few times, but was for Conan 0.x.x.

**Comment by lasote** [comment]
Can be done in GitHub? I'm running this: https://github.com/conan-io/test/blob/master/conan_tests/external_tools/conan_package_tools_test.py for new conan releases, that more or less test the CPT but would be definitely nice to link both repos CI.

**Comment by uilianries** [comment]
Actually it could be used with the CI tool. Do you use Travis, Jenkins or Both?

For example, I use Gitlab CI, that is very similar to Travis. I use a rule on yaml file to trigger a job when the current build is over a tag.

Travis has the same feature: https://docs.travis-ci.com/user/triggering-builds/

So when Conan receives a new tag, a specific job on Travis could trigger a new job for CPT.

**Comment by danimtb** [comment]
Just followed conversation and I am curious to ask: Are you using this "trigger feature" in the Bincrafters org? Maybe it is an overkill but you know **"let's *continuous integrate* all the things!"** 🤣

**Comment by uilianries** [comment]
:joy: :joy: :joy: 

actually I use triggers with Gitlab: https://docs.gitlab.com/ce/ci/triggers/  
But I use at my job only

@solvingj had the great idea to use Github market to create an app that listen project changes and start a new build. This would be great to update Conan packages for every new project release.

**Comment by lasote** [comment]
So you can trigger builds with the API. The thing is if the builds from conan and cpt are not linked somehow, probably the cpt build ends with a fail and I forget to check it. Do you know what I mean?
I could keep querying travis from jenkinks until the cpt build ends, but this process have to be done manually, right?

**Comment by uilianries** [comment]
Well, you will receive an email when Travis breaks so you will be able to remember about any problem.

You could trigger a build even by Jenkins. You could set some rule to trigger the job for CPT when you create a new release for Conan, or when you start a new build manually.

To trigger a new build for CPT, you could run curl:

```
curl -v -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" -H "Authorization: token ${API_TOKEN}" -d '{"request": {"branch": "master"}}' https://api.travis-ci.org/repo/conan-io%2Fconan-package-tools/requests
```
Where `${API_TOKEN}` is the token on your Travis profile.

**Comment by lasote** [comment]
> you will receive an email

Unfortunately, I receive too many emails to be a valid automation for a release, on the other hand, it would be better than nothing.

The good approach for me is the conan release build waiting for the cpt build to end and gather the results, travis and appveyor. 
Sounds like a good idea, but sounds like something we would need to spend some time preparing.

**Comment by uilianries** [comment]
> I receive too many emails

I know how you feel :joy_cat: 

Understood. So I think will be better wait for the service that @solvingj illustrated some time ago. The service could what Conan release and start CPT build (automatically).

**Comment by uilianries** [comment]
Closing this issue since we prefer to manage CPT manually.
