### ISSUE TITLE
Incorrect warning

### ISSUE THREAD

**Issue by db4** [conan-io/conan-package-tools#238]
This warning
```
******* ITERATING THE CONAN_PACKAGE_TOOLS BUILDS WITH .builds is deprecated use .items() instead (unpack 5 elements: settings, options, env_vars, build_requires, reference  *********
```
is misleading: there is no method `.items()` in  `ConanMultiPackager` (`items` as a property), so it should be written as `use .items instead`

**Comment by lasote** [comment]
It will be included in the next release. Thanks
