### ISSUE TITLE
CONAN_STABLE_BRANCH_PATTERN misinformation

### ISSUE THREAD

**Issue by Artalus** [conan-io/conan-package-tools#245]
`stable_branch_pattern`'s description (both parameter and envvar) states

> if current git branch matches this pattern, the packages will be uploaded to *stable* channel. Default "master"

However in `packager.py _get_channel()` there is such code:

        if self.stable_branch_pattern:
            stable_patterns = [self.stable_branch_pattern]
        else:
            stable_patterns = ["master$", "release*", "stable*"]

meaning that by default the stable channel will be picked not only for `master` branch, but also for branches like `releasetest` or `stable-test`. Do you think it would be worth changing the description or  default patterns to check?

**Comment by lasote** [comment]
Sure, the description should be changed.
