### ISSUE TITLE
How to use cpt with cmake.install()

### ISSUE THREAD

**Issue by bryceschober** [conan-io/conan-package-tools#247]
I developing a conan package for an external project that is built using cmake. It builds & tests just fine locally, but not on gitlab ci. My package is using `cmake.install()` in the `build()` method and just `pass`-ing on the package method as documented [here](https://docs.conan.io/en/latest/howtos/cmake_install.html), and the output looks like it isn't getting anything in the package, with each configuration resulting in output like:
```
CppUTest/master@bryceschober/stable: Generating the package
CppUTest/master@bryceschober/stable: Package folder /home/bschober/.conan/data/CppUTest/master/bryceschober/stable/package/97fa2add7ff02bfbb82a5e5931d282250fb81a2a
CppUTest/master@bryceschober/stable: Calling package()
CppUTest/master@bryceschober/stable: WARN: No files copied from build folder!
CppUTest/master@bryceschober/stable: Package '97fa2add7ff02bfbb82a5e5931d282250fb81a2a' created
```

If I do a local non-cbt build+test along the lines of:
```
conan source .
conan install .
conan build .
conan package .
conan export-pkg -pf package . bryceschober/testing
conan test test_package CppUTest/master@bryceschober/testing
```
Then I get the files that I expect and the test works as expected.

It seems that cbt either doesn't support this "non-standard" but documented / recommended way of reusing the cmake install, or maybe that how do use it with cbt wasn't discoverable by me.

**Comment by lasote** [comment]
The cpt only allows `conan create` flow.

**Comment by uilianries** [comment]
Hi @bryceschober !

As @lasote said, the best option is using `conan create` command.

You could obtain more information about `create` [here](https://docs.conan.io/en/latest/reference/commands/creator/create.html).

Also you could [write a Conan recipe](https://docs.conan.io/en/latest/creating_packages/getting_started.html#creating-the-package-recipe) as well.

When running Conan Package Tools, it will call `conan create` automatically. But the best option for `cmake install` is running into `package` method. Package is the point where Conan copies all files to package folder.

Do you have any question?

Regards!

**Comment by bryceschober** [comment]
Nope, I'm OK and have moved on.
