### ISSUE TITLE
build_policy missunderstanding

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-package-tools#25]
Hi!

I'm building a package ([here](https://github.com/jgsogo/conan-portaudio)) that download the sources from a git repo. I want to maintain a version, `master`, that always grab the last revision from that repository. I supposed that this will be the behaviour of `build_policy='always'`, the client will get the sources and compile them each time conan install is invoked... but

```
ERROR: Conanfile has build_policy='always', no packages can be uploaded
Traceback (most recent call last):
  File "build.py", line 16, in <module>
    builder.run()
  File "C:\Python27-x64\lib\site-packages\conan\packager.py", line 261, in run
    self._upload_packages()
  File "C:\Python27-x64\lib\site-packages\conan\packager.py", line 367, in _upload_packages
    raise Exception("Error uploading")
Exception: Error uploading
Command exited with code 1
```

It's ok, it has no sense to upload the binaries, but I want to upload the recipe... is this behaviour possible?

Thanks!

**Comment by jgsogo** [comment]
I'm thinking that the client of the package can always invoke `conan install` with `--build portaudio` to update from the repository if that is what he wants... so current implementation covers this behaviour ;D

**Comment by memsharded** [comment]
Yes, of course you can upload just the package recipe, just do:

```bash
$ conan upload MyPackage/0.1@user/channel
```
instead of
```bash
$ conan upload MyPackage/0.1@user/channel --all
```
The latest instruct to upload both the recipe and all locally compiled binaries. Just skipping the ``--all`` will upload just the recipe. And no ``--build portaudio`` will be necessary for consumers. Is this the problem? Thanks!

**Comment by memsharded** [comment]
In any case, the ``build_policy`` is something related to conan, not really to ``conan-package-tools``, maybe next time can be reported in that repo. Cheers!

**Comment by jgsogo** [comment]
(Ok, `build_policy` is related to conan, but I questioning the default behaviour inside this packager)

So, if I have something like [this](https://github.com/conan-io/conan-package-tools/pull/26) to be able to do something like [this](https://github.com/jgsogo/conan-portaudio/pull/2), I would have my package recipe (with `build_policy='always' ) uploaded after a successful build in travis/appveyor, isn't it?

**Comment by uilianries** [comment]
Hi!

This one will be fixed by https://github.com/conan-io/conan-package-tools/pull/348
