### ISSUE TITLE
Feature Request: Add CONAN_CONFIG_URL parameter

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#262]
When added, CPT should run the following prior to the build: 
`conan config install <CONAN_CONFIG_URL>`

**Comment by uilianries** [comment]
That's an excellent idea IMO!

In my case, I need cross-building many projects so I need multiple custom profiles. Using CI tools we could write all profile info in .yaml file but for local build we need to create a dedicated profile.

Conan config could be the best option to use custom profiles and remotes, avoiding replication.

**Comment by solvingj** [comment]
Great, this seems like an extremely easy and un-controversial feature to implement.
