### ISSUE TITLE
Feature Request: New Environment Variable for "args"

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#263]
I'm not sure if there's a reason this was not created in the first place, but we want to pass Conan args from environment variables for CI. 

`CONAN_ARGS=<project_name>:shared=True, boost:shared=True`

We're implementing this on our own, but would like to see it land in CPT. 

We want this because it's not suitable for us to create conan profiles which go into as much detail as defining the options for projects and their dependencies.  I did try creating project-specific profiles in the project folder, which `include()` global profiles.  It wasn't terrible, but it added to the directory pollution problem, hides information from the person reading the Jenkinsfile, and becomes harder to maintain at scale. There are of course advantages to the project-specific-profiles, and maybe we end up going back to that.  However, it still seems like a reasonable feature to request.

**Comment by sourcedelica** [comment]
Should this be `CONAN_OPTIONS`?  Or are there other args that could be used?  Args is a generic term.

**Comment by lasote** [comment]
The problem is that `cpt` is not calling the command line anymore, but using the python api of conan (not published, not stable). So the "args" make no sense now.

**Comment by solvingj** [comment]
i see, didn't realize that was the case. Can you suggest a current alternative for defining `shared` for dependencies (and other options) from environment variables?

**Comment by lasote** [comment]
We can create one var only for options. I don't see an alternative.

**Comment by solvingj** [comment]
does this work:  `CONAN_OPTIONS="somepkg:shared=True,otherpkg:shared=True"`

**Comment by uilianries** [comment]
I'm checking CPT but looks CPT_ARGS reaches a dark spot. It's only used on unit tests.

I want to remove args from CPT, but I'm afraid of breaking some users.

**Comment by solvingj** [comment]
Oh, funny, it did exist and was removed.  that explains why i kinda thought i remembered it :)

**Comment by lasote** [comment]
Now that I see the @uilianries implementation I'm wondering if the options should be added directly iterating the builds in the `build.py`. Any reason to not doing that @solvingj ?

**Comment by solvingj** [comment]
One of the most brilliant parts of CPT is the flexibility in where users can specify. In CI web portal, CI specific files, or build.py (shared between CI). We have used all three for different things at different times.  Environment variables in CI files are more declarative and much more clear than reading through conditionals.
