### ISSUE TITLE
Upload package error

### ISSUE THREAD

**Issue by KoHcoJlb** [conan-io/conan-package-tools#264]
https://github.com/conan-io/conan-package-tools/blob/4b9e3acf9b4a569600aa305a490b2118ab1f311b/cpt/runner.py#L71
test_package dependencies come before created package itself in `r['installed']`
This results in trying to upload non existent package.

**Comment by lasote** [comment]
Do you mean the uploaded package should be the "last installed", right?

**Comment by lasote** [comment]
Released 0.19.3!
