### ISSUE TITLE
Support custom docker args for docker run command

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-package-tools#277]
For example: `CONAN_DOCKER_ARGS` and an equivalent constructor argument. 

We've discovered an issue in my company where the default settings for Windows Containers is to allocate 1GB of RAM.  When building particularly large visual studio projects, we get a very random and intermittant compiler error.  This occurs when using multiple versions of Visual Studio Build Tools 15.6.7, 15.7.6, and 15.8.6, and the error references a random C++ template parameter each time, from a variety of different libraries we use. 

```
error C1001: An internal error has occurred in the compiler. 
compiler file 'msc1.cpp', line 1511
```

There are many reports about this error, and Microsoft explains that it's a very generic error that tells them almost nothing.   For us, we've found that it doesn't happen unless we're in Docker, and only on one of our docker hosts, and only on this really big project.  So, we discovered a workaround to be to pass the following additional argument to Docker:   

`-m 2gb`

This doubles the RAM allocated to each container, and the problem seems to have gone away.  However, it's very likely that simply applying this to all builds as part of CPT would have unexpected consequences for other users or even our other projects.  Additionally, there are countless other docker flags which might be necessary to set under certain circumstances. 

As a result, this request is for a primitive catch all string variable that would give users some control over the docker process they are launching, without complicating CPT too much.

**Comment by uilianries** [comment]
There are two ways to fix this, one is using your approach, adding a new generic argument where you could put anything but it's hard to debug and validate. Another option is the gitlab idea, where each option has a specific argument, easy to debug and validate, but very limited when we need to fix a new problem. I would prefer the first one, it's not safe but any new problem detected could be fixed immediately, without a new patch from CPT.
