### ISSUE TITLE
Channel & upload configuration in appveyor

### ISSUE THREAD

**Issue by dimi309** [conan-io/conan-package-tools#28]
Hello,

I have a couple of questions with regard to the following commit of my package:

https://github.com/coding3d/conan-ogg/tree/a7d075f530520c28544a17eb39405681d4e37e01

The commit has produced the following build on appveyor:

https://ci.appveyor.com/project/coding3d/conan-ogg/build/1.0.11

My questions may be due to my own misunderstanding but I am mentioning them here, in case they are actually issues that have to do with the package tools:
- Should this build have led to an upload to conan.io, given the fact that I have set CONAN_UPLOAD to 0 in appveyor.yml? Does CONAN_UPLOAD control whether or not the packages will be uploaded, or does it do something else?
- Since I have set CONAN_CHANNEL to "ci" in appveyor.yml, why is the channel of uploaded packages "stable"? In general, can we control what the channel of uploaded packages is? (If the "stable" channel is a conan.io best practice, it sounds good, but it's still good to know).

Thanks!

**Comment by memsharded** [comment]
I think that the first one might be a bug, it shouldn't upload if CONAN_UPLOAD = 0

The second one, I think it has some relation to the branch. If you are in the master branch, that has precedence, and goes to "stable". I feel it a bit confusing, but it is the way it is defined now. Maybe @lasote could help with this

**Comment by lasote** [comment]
About the first, just no define the CONAN_UPLOAD variable, it's not using the value, just the definition (yeah, could be improved)
About the first, @memsharded is right, it is a little weird but it is the current implementation.

**Comment by coding3d** [comment]
Makes sense. Thanks!

**Comment by raulbocanegra** [comment]
Hi all,
The problem seems to be in line 43 of packager.py.
```python
self.upload = upload or os.getenv("CONAN_UPLOAD", None)
```
upload is a boolean but os.getenv("CONAN_UPLOAD", None) is a string if you set the environment variable, so self.upload under this circumstances is always a string if upload == False

Then in line 342 in method "_upload_packages" you can see:
```python
if not self.upload:
    return
```

As I said self.upload is a string so `not "some string"` always returns False and never enter in that if statement. That is the reason why it always uploads packages even if you set the environment variable to False.

As a solution changing the line 43 by:
 ```python
self.upload = upload or (os.getenv("CONAN_UPLOAD", None) in ["True", "true", "1"]
```
May fix this issue.

I can make a fork and a PR if you wish.

Thanks for your work! ;-)

**Comment by memsharded** [comment]
Hi Raul, yes sure, I think your solution will improve over the current behavior, so I encourage to submit a PR! Thanks to you for contributing :)

**Comment by dimi309** [comment]
Just a note: I'm pretty used to the way conan works now, so if you would like to close this issue, that's fine by me :D

**Comment by memsharded** [comment]
I still find the current behavior a bit confusing, I can live with it, but would prefer to have something more explicit.

**Comment by dimi309** [comment]
Of course, the more intuitive the better, especially for new users! I'm always mentioning new users lately. It's my new thing 😄
