### ISSUE TITLE
Don't re-download and re-compress downloaded packages

### ISSUE THREAD

**Issue by leugenea** [conan-io/conan-package-tools#280]
Sometimes there's a situation when part of packages that I wanted to build was build correctly, but something stopped the process (for example, an electricity issue).
Currently I just rerun `python ./build.py` and it downloads built packages and builds packages that are not built. It's much faster than rebuild all packages, but if package is already built, conan-package-tools will:
* download it,
* unpack in,
* compress it.
Looks like conan-package-tools can skip all of these steps because we know that we won't build package from the beginning.
It could save some "network transfers" (as packages won't be downloaded) and CPU time (as packages won't be re-compressed).

**Comment by lasote** [comment]
If I understood correctly, are you using some build_policy like "outdated" or "missing"?

Even though the package needs to be downloaded if it is in the server, a "conan create" is executed and that is the behavior it has, it "installs" the package by building it or retrieving it, then it will run the `test_package` against the downloaded binary.

But I think the "compress" and "re-upload" could be omitted if we only upload the "built" packages, not only the "installed" ones.

**Comment by lasote** [comment]
Everything is a `conan create`. And there is no other way to proceed without changing Conan because for knowing if the binary is available for the specified configuration you will install it.

**Comment by leugenea** [comment]
Why not try to use something like `conan search`?

**Comment by lasote** [comment]
well, you would need also to first download all the transitive recipes (can be done with a conan info command) to really be able to calculate the needed package id, then if you have the package ID you could perform a search, but still `conan info` doesn't return correctly the json containing the necessary data. Even though do a `conan info` + `conan search` to avoid downloading a package... I don't know I would try to keep it simple.

**Comment by leugenea** [comment]
But doesn't it look strange, that to check if package is outdated we **must** download it with all of dependencies. I believe that there should be a better way to do this. =(

**Comment by lasote** [comment]
Not the binary package but the recipes. You cannot calculate the package id without the recipes because a recipe can change the requires and the options (even upstream) depending on the input profile.

**Comment by leugenea** [comment]
Oh, no. I'm talking about downloading binary packages of all (build) dependencies, not just recipes.
