### ISSUE TITLE
Appveyor freezes and times out?

### ISSUE THREAD

**Issue by coding3d** [conan-io/conan-package-tools#29]
This is more a question about the use of the tools with appveyor rather than an issue with the tools themselves. I have this build: 

https://ci.appveyor.com/project/coding3d/conan-ogg

It freezes after setting up conaninfo.txt and then times out. Is this a known issue with appveyor or may there be something that I am doing wrong? It has happened to me before and then it just stopped happening without me doing anything special, at least as far as I understood.

**Comment by memsharded** [comment]
I see nothing that could be generating that behavior. Have you just tried to re-launch the appveyor build? Sometimes the appveyor instances freezes without reason, not often, but could happen. Please try and report if it freezes in the same point. Thanks!

**Comment by memsharded** [comment]
BTW, why are you trying to remove some folder in the build() method? It is supposed that the build() method will run in a clean folder, no need to remove.

**Comment by memsharded** [comment]
You may also want to use double &, instead of single one in multiple commands, to ensure that they are executed only if the previous command is successful, something might be failing there:

```bash
self.run("%s & devenv %s /upgrade" % (cd_build, vs_project))
//better?
self.run("%s && devenv %s /upgrade" % (cd_build, vs_project))
```

**Comment by coding3d** [comment]
I have relaunched it many times but it did not get unstuck. A few days ago,
another build did start working after a couple of tries though...
The folder I remove is useful for calling "conan build" locally for initial
debugging. It removes the source archive and I am catching the exception
when it does not exist. But I can remove this command if you think it's a
bad idea :)

**Comment by coding3d** [comment]
Nice catch about the & ! I totally overlooked that one! Maybe it's what's
causing the problem. Let's see...

**Comment by coding3d** [comment]
Still freezing... I'll try some other things too...

**Comment by coding3d** [comment]
Ok, I've figured it out. Some older versions of Visual Studio may freeze when devenv /upgrade is called. I suppose that this is what was happening on appveyor. I am only building for VS2015 for now and will investigate further, over time.
