### ISSUE TITLE
Error when specifying remote for uploading packages

### ISSUE THREAD

**Issue by SteffenL** [conan-io/conan-package-tools#3]
The documentation states that a remote can be specified, and shows an example on how to do it; however, the example gives me an error:

    Traceback (most recent call last):
    File "example.py", line 6, in <module>
        builder.upload_packages("mypackage/1.2.3@user/testing", "myconanserverpassword", remote="mycustomserver")
    TypeError: upload_packages() got an unexpected keyword argument 'remote'

Example:

    from conan.packager import ConanMultiPackager

    if __name__ == "__main__":
        builder = ConanMultiPackager([], "user", "testing")
        builder.upload_packages("mypackage/1.2.3@user/testing", "myconanserverpassword", remote="mycustomserver")

Versions:
- conan: 0.7.4
- conan-package-tools: 0.1.2
-  Python: 2.7.11

**Comment by lasote** [comment]
Hi, I've uploaded conan-package-tools 0.1.3 to pypi, the issue should be fixed, now you can specify the remote. Thanks!
