### ISSUE TITLE
CONAN_USE_DOCKER is incompatible with conanfile.py in a subdirectory

### ISSUE THREAD

**Issue by himikof** [conan-io/conan-package-tools#306]
Placing conanfile.py in a subdirectory of the project repository instead of the root is often desirable (see conan-io/conan#3635, for example). But the `build.py` currently makes these 2 assumptions:

1. The conanfile.py is in the current directory
2. The current directory is the docker build context root if CONAN_USE_DOCKER is set

So even if conan itself is capable of correctly building the package, there is no way to use the correct docker build context root and find the conanfile.py correctly at the same time.

Maybe an option to set the docker build context root, or an option to find conanfile.py in a subdirectory could be provided?

**Comment by Croydon** [comment]
That should be fixed with https://github.com/conan-io/conan-package-tools/pull/528

**Comment by uilianries** [comment]
Fixed by #528
