### ISSUE TITLE
Upload only from tags

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-package-tools#307]
Recipes in authors repositories will get benefited from having and `upload_only_if_tag`. CI will run always, but we usually want to upload only _tagged_ versions.

**Comment by uilianries** [comment]
this is a excellent feature, for now I need to validate ci env vars or run some regex.

**Comment by himikof** [comment]
For example, in Gitlab CI there is a single convenient variable to use (present only when building from a tag): [`CI_COMMIT_TAG`](https://docs.gitlab.com/ee/ci/variables/#predefined-variables-environment-variables). So the CI manager class could be extended with an `get_tag` method, probably?

I currently use hacks as `v*` branch wildcard (assuming tags of the form v0.1 and tag name is  taken as a branch name when building from tags).

**Comment by uilianries** [comment]
we could create `STABLE_TAG_PATTERN` for cases where there is no properly env var.

**Comment by uilianries** [comment]
never mind, `STABLE_BRANCH_PATTERN` is enough.
