### ISSUE TITLE
Libraries incompatibility when running build.py on linux

### ISSUE THREAD

**Issue by MojaveWastelander** [conan-io/conan-package-tools#32]
I've created a package for dlib and it worked in appveyor, but on local linux and travis I get an error at the [test_package step](https://travis-ci.org/MojaveWastelander/conan_dlib/jobs/161727448)

> home/conan/.conan/data/dlib/19.1.0/.../lib/libdlib.so when searching for -ldlib
> /usr/bin/ld: skipping incompatible /home/conan/.conan/data/dlib/19.1.0/.../lib/libdlib.a when searching for -ldlib

I've checked on local linux and the library and its dependencies are build with the same arch. Runnig just test_package works fine. What can be the problem?

**Comment by lasote** [comment]
Hi! 
I don't know exactly why is complaining, but I can see one thing you need to change.

In your build method you are invoking the dlib CMakelists.txt file, that right, but this CMakeLists doesn't know anything about your declared dependencies (the lib paths, flags etc). 

You can paste these lines before the `self.run("mkdir build")`:

```
conan_magic_lines = '''project(dlib)
include(../../conanbuildinfo.cmake)
CONAN_BASIC_SETUP()
'''
replace_in_file("dlib/dlib/CMakeLists.txt", "project(dlib)", conan_magic_lines)

```

But unhappily it couldn't be enough to let dlib cmake script to locate all your conan dependencies, it depends A LOT in every case. Make a package for a library with dependencies could be hard if you don't link with CONAN_LIBS directly.
Maybe the find_package just works and it locate all your conan dependencies, but maybe you will need to replace more things in the CMakeLists.txt like the `target_link_libraries` to link against $CONAN_LIBS etc. I recommend you to ensure that dlib CMakeLists.txt is finding correctly all your deps in the conan directories using MESSAGE for example.

Hope it helps! If don't please write me and I will try to reproduce the error. :+1:

**Comment by MojaveWastelander** [comment]
Yes, you're right, I knew I forgot about something, anyway now I get the similar [problem](https://travis-ci.org/MojaveWastelander/conan_dlib/jobs/162059249) as with [nana](https://travis-ci.org/MojaveWastelander/conan_nana/jobs/160099969) and [podofo](https://travis-ci.org/MojaveWastelander/conan_podofo/jobs/161347643) where the system packages are installed, but at build it doesn't see headers/libs.

**Comment by lasote** [comment]
With the system libraries the problem is about the arch. You need to install in the travis machine both x86 and x86_64 system libraries. If the linker is complaining maybe It is trying to make x86 conan packages but the linker only find the x86_64. 

But if some includes are not found it usually means you need to install the "-dev" package of the system library, for the [X11 headers](https://travis-ci.org/MojaveWastelander/conan_nana/jobs/160099969) it should be "libx11-dev".

To install system requirements you can use the `system_requirements` method. You can see an example here https://github.com/lasote/conan-sdl2/blob/master/conanfile.py

**Comment by sunxfancy** [comment]
I have the same error, but I have no system library require for this library. The test package can not link to the main library. I just didn't know why there is incompatible format when they are compiled with same args by conan.
I tested it in the local environment, it works well in x86_64, but same error in x86 without docker. 

Here are my travis-ci logs: https://travis-ci.org/sunxfancy/conan-libcharsetdetect/jobs/200215589

Thanks a lot, waiting for help.

**Comment by memsharded** [comment]
I am not sure what is happening in your case, but it would seem that the "magic lines" are not being properly replaced. I have run locally, and in the package building I can read:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    CONAN_EXPORTED
```

While in the output of your travis:
```
 Manually-specified variables were not used by the project:
    CONAN_COMPILER
    CONAN_COMPILER_VERSION
    CONAN_CXX_FLAGS
    CONAN_C_FLAGS
    CONAN_EXPORTED
    CONAN_LIBCXX
    CONAN_SHARED_LINKER_FLAGS
```

Which basically means that the ``-m32`` flags that are being defined, are actually not being used.

I also miss the line that ``conanbuildinfo.cmake`` is printing, it should be something like:

```
Conan: Using cmake global configuration
```

So for some reason your magic lines are not there. I would try to debug what is happening in your CI job, by adding some log/prints to ``source()`` even reading the final ``CMakeLists.txt`` and printing it to check what is there. Please try and report, thanks very much for your feedback!

**Comment by sunxfancy** [comment]
@memsharded Thanks for your reply. After printed the command line of conan build, I found the magic lines didn't replace the CMakeLists.txt, so now it is solved!
