### ISSUE TITLE
Add support for XCode8

### ISSUE THREAD

**Issue by shinichy** [conan-io/conan-package-tools#33]
XCode 8 was released in 9/13/2016.
It would be great if conan-packge-tools could support it.

https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Introduction.html

**Comment by shinichy** [comment]
I found that I just need to update .travis.yml.

**Comment by shinichy** [comment]
I added `osx_image: xcode8` in .travis.yml but nothing happened in Travis.

https://travis-ci.org/shinichy/conan-breakpad/jobs/168514967

Maybe do we need to add '8.0' to default_apple_clang_versions?

https://github.com/conan-io/conan-package-tools/blob/90a8e377dc69103a522c2855085210c30de0a4c2/conan/packager.py#L19

**Comment by memsharded** [comment]
Yes, definitely, for XCode 8, the toolchain is apple-clang 8, so it should be added to allowed settings.

**Comment by memsharded** [comment]
In any case @shinichy ,, I think you can explicitely provide ``apple_clang_versions`` to ``ConanMultiPackager`` constructor in your ``build.py`` to test it, until this is fixed and released

**Comment by lasote** [comment]
Fixed
