### ISSUE TITLE
Update README: login is no longer supported

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-package-tools#336]
Hi!

The section [method reference](https://github.com/conan-io/conan-package-tools/blob/develop/README.md#complete-conanmultipackager-methods-reference) contains **login** as `ConanMultiPackager` method, however it was moved to `AuthManager`.

We have two options, or re-add the login method again, or describe how to login using `AuthManager`.

/cc @spiderkeys

Regards!

**Comment by uilianries** [comment]
@lasote Do you think we should introduce the **login** method again?

I think yes, it's better for users, where it does not require internal elements from CPT, like accessing `self.auth_manager` from `ConanMultiPackager`

**Comment by lasote** [comment]
If someone requests it, yes, it can be propagated to the main class.

**Comment by uilianries** [comment]
Yes, @spiderkeys wishes the old `login` method. He needs to login on private remotes to be able to download, it sounds legitimate.

**Comment by lasote** [comment]
ok
