### ISSUE TITLE
gcc7-centos does not support system_requires: sudo -A fails

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-package-tools#338]
Installing system requirements using the `tools.SystemPackageTool` fails in the `gcc7-centos` docker
The error is:
```
Running: sudo -A yum update -y
/var/tmp/sclH4Ekle: line 8: -A: command not found
```
travis: https://travis-ci.com/madebr/conan-ps2_toolchain_installer/jobs/180446149#L596

This can be reproduced in interactive mode:
```
$ docker run -t -i --rm -v /tmp:/home/conan/project:Z conanio/gcc7-centos6 /bin/bash
[conan@e5b2b8cb2901 ~]$ sudo -A ls
/var/tmp/sclvoMvA6: line 8: -A: command not found
```
Original issue: https://github.com/conan-io/conan-docker-tools/issues/105

**Comment by uilianries** [comment]
Closing this one since it will fixed by  conan-io/conan-docker-tools#115
