### ISSUE TITLE
Docker bind mounts not working on selinux

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-package-tools#339]
On my local machine with SElinux enabled, building using docker and CPT does not work.
SElinux prevents the docker image to access the contents of the `project` folder.

See https://github.com/conan-io/conan-docker-tools/issues/104#issuecomment-467464786 for an example of this problem.

This can be fixed by adding `:z` or `:Z` to the -v option.
See `man docker run`

**Comment by madebr** [comment]
Tested on fedora 28 with enforcing selinux.

Imho, it would be a better user experience if selinux status would be detected automatically: https://howto.lintel.in/enable-disable-selinux-centos/

This is the output of `getenforce` on my machine:
```
$ getenforce
Enforcing
```
If I have disabled selinux, the output becomes:
```
$ getenforce
Permissive
```

**Comment by lasote** [comment]
0.25.0 released!

**Comment by lasote** [comment]
Oh, sorry it finally hasn't been merged to 0.25, we hadn't enough time.
