### ISSUE TITLE
MinGW builds not working with appveyor

### ISSUE THREAD

**Issue by osechet** [conan-io/conan-package-tools#34]
When running a mingw build in appveyor, I get the following error:
`ERROR: Conanfile: 'settings.compiler.libcxx' value not defined`

When `conan user` is called, conan set the default settings for Visual Studio and do not set the `libcxx` setting. Then when the conan-package-tools starts the mingw build, it does not provide the `libcxx` setting neither.

Is there a way for me to set this settings in the appveyor configuration?

A build log is available here: https://ci.appveyor.com/project/osechet/conan-icu/build/1.0-6/job/x5efdfydi1pq1q06

**Comment by lasote** [comment]
Try now. I've uploaded a new conan package tools version that sets libcxx for mingw.

**Comment by osechet** [comment]
OK, it's now working, the MinGW build starts. Thanks.
