### ISSUE TITLE
add new variable CONAN_CUSTOM_CONANFILE_NAME_OVERRIDE

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-package-tools#354]
currently, CPT always uses `conanfile.py` as name of conan file containing ConanFile class.
this works flawlessly for the most of use cases, however for the use case installer + library in the same repo (e.g. bison, flex, vulkan, ICU, etc) it's not enough, obviously.
I propose to add new variable named `CONAN_CUSTOM_CONANFILE_NAME_OVERRIDE` to override default.
related code is around here: https://github.com/conan-io/conan-package-tools/blob/14c86886eb556d746bef5c167689ee8aedaec810/cpt/runner.py#L89
as you can see, it just always invokes `conan create .` via conan API, and there is no way to use different file name.
in general, I prefer to leave my build scripts untouched (so they match templates), and just specify variable name in travis matrix, like:
```
CONAN_CUSTOM_CONANFILE_NAME_OVERRIDE=bison.py
CONAN_CUSTOM_CONANFILE_NAME_OVERRIDE=bison_installer.py
```
/cc @uilianries 

### Environment Details
* Conan Package Tools Version: **0.23.0**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 16.04**
* Compiler+version: **gcc-5.4**
* Docker image: **conanio/gcc7**
* Conan version: **conan 1.2.0**
* Python version: **python 3.7.0**

**Comment by uilianries** [comment]
I agree, but could we use `CONAN_CONANFILE` instead of `CONAN_CUSTOM_CONANFILE_NAME_OVERRIDE` ?

**Comment by SSE4** [comment]
ok
