### ISSUE TITLE
Build broken when updating to 0.25.1 version of cpt from 0.24.0

### ISSUE THREAD

**Issue by jcaden** [conan-io/conan-package-tools#368]
### Description of Problem, Request, or Question
My build is broken with the following error when updating  to CPT 0.25.1 from 0.24.0

```
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    builder = ConanMultiPackager()
  File "/usr/local/lib/python3.6/site-packages/cpt/packager.py", line 229, in __init__
    raise Exception("CONAN_PIP_COMMAND: '{}' is not a valid pip command.".format(self.pip_command))
Exception: CONAN_PIP_COMMAND: 'pip' is not a valid pip command.
```

My pip command is 

### Environment Details
* Conan Package Tools Version: **0.25.1**
* Operating System: **Linux**
* Operation System Version: **Amazon Linux**
* Compiler+version: **gcc-6**
* Docker image: **custom Amazon Linux image**
* Conan version: **conan 1.14.1**
* Python version: **python 3.6.2**

**Comment by uilianries** [comment]
Hi @jcaden !

Do you have `pip` installed in your system? 

I've added a new feature for 0.25 (https://github.com/conan-io/conan-package-tools/pull/347) which allows to configure a custom pip command e.g. pip3

Regards!

**Comment by jcaden** [comment]
I do. Actually when using previous versions of CPT pip is used to install Conan and CPT in the docker image before starting with the build process.

**Comment by uilianries** [comment]
Since CPT 0.25.0, we use the command `which` to check if `pip` is available. However, you can customize the pip commands by the env var `CONAN_PIP_COMMAND`

I think `which` is failing to find `pip`:

https://github.com/conan-io/conan-package-tools/pull/347/files#diff-d4b35028f096dfba5e51a62caf3200b9R223

You can try two things:

- Run `which pip` to check if pip is available
- set the env var `CONAN_PIP_COMMAND` to pip absolute path e.g /usr/bin/pip

You described Amazon Linux, where could I find this docker image? You error occurs before to run Docker.

**Comment by jcaden** [comment]
Sorry for the delay in reply.

You can find amazonlinux here https://hub.docker.com/_/amazonlinux on top of this I've installed some tools like compilers, autotools, cmake, etc and also python3.6 and pip3.6.

I've verified that using the docker image, `which pip` returns the proper pip command. I also tried defining `CONAN_PIP_COMMAND` and I get this error:

```
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    builder = ConanMultiPackager()
  File "/usr/local/lib/python3.6/site-packages/cpt/packager.py", line 229, in __init__
    raise Exception("CONAN_PIP_COMMAND: '{}' is not a valid pip command.".format(self.pip_command))
Exception: CONAN_PIP_COMMAND: '/usr/local/bin/pip' is not a valid pip command.
```

However, if I try running `/usr/local/bin/pip` in the docker image it runs correctly and also installs packages correctly.

**Comment by uilianries** [comment]
Thanks! I'll take a look.

BTW, Did you try Conan Docker images? Conan have a bunch of images, including many compiler versions. As you are using gcc6, you could try `conanio/gcc6`:

    docker run --rm -ti conanio/gcc6

Regards!

**Comment by uilianries** [comment]
> on top of this I've installed some tools like compilers, autotools, cmake, etc and also python3.6 and pip3.6.

Which commands did you use to install python and pip? I would like to reproduce the exactly same scenario.

**Comment by jcaden** [comment]
> BTW, Did you try Conan Docker images? Conan have a bunch of images, including many compiler versions. As you are using gcc6, you could try conanio/gcc6:

I wish I could, but those are based in ubuntu and the binaries generated by them don't link correctly with software compiled in the amazonlinux version I'm using.

> Which commands did you use to install python and pip? I would like to reproduce the exactly same scenario.

I'm trying to reproduce an environment that you can use, but it looks like the version of amazonlinux that my company is using diverges from the docker amazonlinux that I sent o you. I'll let you know if I can get an environment where you can reproduce.

**Comment by jcaden** [comment]
I see the problem, the proper image is `amazonlinux:1`. I'll send a Dockerfile to reproduce the environment.

**Comment by jcaden** [comment]
While I was preparing this image for you `jcaden/amazonlinux-conan:1` (still linking it just for your curiosity) I realized that the problem was that the host did not have `pip` but `pip3`. Creating the proper link to `pip`fixed the issue.

**Comment by uilianries** [comment]
Great! Thanks for sharing the solution!
