### ISSUE TITLE
Please add support for cppstd

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan-package-tools#370]
Please add support to `add_common_builds() ` to create builds for various cppstd flags. My recommendation is to provide a build for:
- the default cppstd of a current compiler version (i.e. C++14 for gcc-7 and gcc-8)
- the latest official standard supported by a current compiler version (i.e. C++17 for gcc-7 and gcc-8)
- the pre-release C++ standard if a compiler supports it (i.e. C++2a for gcc-8).

Otherwise, people will be forced to do that by their own in build.py. A short example below assumed the compiler is gcc-7 or gcc-8. It can get much messier when more compilers will be needed (older gcc, clang, VS, etc).

```python
    builder.add_common_builds(pure_c=False)
    new_builds = []
    for settings, options, env_vars, build_requires, reference in builder.items:
        for std in ["17", "20"]:
            if settings["compiler.version"] == "7" and std == "20":
                continue
            new_settings = copy.copy(settings)
            new_settings["cppstd"] = std
            new_builds.append([new_settings, options, env_vars, build_requires])
    builder.builds = new_builds
    builder.run()
```

**Comment by uilianries** [comment]
Hi @mpusz !

Your request sounds legitimate! We will implement this feature.

Regards!
