### ISSUE TITLE
run in docker build, wrong 'cmd' seleced.

### ISSUE THREAD

**Issue by Mingyiz** [conan-io/conan-package-tools#376]
### Description of Problem, Request, or Question
When I build [zlib](https://github.com/conan-community/conan-zlib) Linux lib on Windows 10 (With Widnows desktop docker), error happend on running command. from the log, the reason is becuase of **'cmd /C'** instead of **'bash -c'**

I want to know, what's the proper way to solve this issue.

### Environment Details
* Conan Package Tools Version: **0.26.0**
* Operating System: **Windows**
* Operation System Version: **Windows 10**
* Compiler+version: **gcc5**
* Docker image: **conanio/gcc5**
* Conan version: **conan 1.2.4**
* Python version: **python 3.7.0**

### Steps to reproduce (Include if Applicable)
git clone https://github.com/conan-community/conan-zlib
set CONAN_USERNAME=edgeos-oss
set CONAN_GCC_VERSIONS=5
set CONAN_DOCKER_IMAGE=conanio/gcc5

### Build logs (Include if Available)

conan_runner
Traceback (most recent call last):
  File "build.py", line 9, in <module>
    builder.run()
  File "C:\Python37\lib\site-packages\cpt\packager.py", line 475, in run
    self.run_builds(base_profile_name=base_profile_name)
  File "C:\Python37\lib\site-packages\cpt\packager.py", line 589, in run_builds
    docker_entry_script=self.docker_entry_script)
  File "C:\Python37\lib\site-packages\cpt\runner.py", line 236, in run
    raise Exception("Error updating the image: %s" % command)
Exception: Error updating the image:  docker run -e CONAN_DOCKER_IMAGE="conanio/gcc5" -e CONAN_GCC_VERSIONS="5" -e CONAN_USERNAME="edgeos-oss" -e CONAN_CHANNEL="stable" -e CONAN_LOGIN_USERNAME="edgeos-oss" -e CONAN_REFERENCE="zlib/1.2.11@edgeos-oss/stable" -e CPT_PROFILE="@@include(default)@@@@[settings]@@arch=x86@@build_type=Release@@compiler=gcc@@compiler.version=5@@[options]@@zlib:shared=True@@[env]@@@@[build_requires]@@@@" -e CONAN_TEMP_TEST_FOLDER="1" -e CPT_UPLOAD_RETRY="3" -e CPT_CONANFILE="conanfile.py" --name conan_runner   conanio/gcc5 cmd /C " pip install conan_package_tools==0.26.0 --upgrade --no-cache &&  pip install conan==1.14.5 --no-cache"

full logs see attached.
[cpt-zlib.log](https://github.com/conan-io/conan-package-tools/files/3145171/cpt-zlib.log)

**Comment by uilianries** [comment]
Hi @Mingyiz !

It's a bug. As you are running on Windows, CPT will use `cmd` automatically because you can run Docker over Windows with Windows docker images.

We need to check if the docker image is Linux based or not.

**Comment by Compiler** [comment]
Sup

**Comment by Compiler** [comment]
Reopened via #583

**Comment by bredej** [comment]
When using Linux Containers on Docker Desktop for Windows remember to set 
CONAN_DOCKER_PLATFORM=linux
and enable Docker daemon with experimental features in Docker Desktop settings.
If you don't want to enable experimental features you can try to set the following instead
CONAN_DOCKER_HOME=/home/conan
CONAN_DOCKER_SHELL=/bin/bash -c

Linux Containers are the default when installing Docker Desktop for Windows and maybe it should be the same for cpt.

**Comment by Compiler** [comment]
sounds good dude
