### ISSUE TITLE
broken python_requires with conan 1.15/CPT 0.27

### ISSUE THREAD

**Issue by sboehmann** [conan-io/conan-package-tools#378]
With conan 1.15 and CPT 0.27 all my CI builds are broken. If I downgrade to conan 1.14/CPT 0.26 everything is ok again. All CI build is executed in a new clean docker container and since there weren't that many changes in CPT, I think a change in Conan might cause this issue.

Broken build:
```
23:51:49  Version: 0.27.0
23:51:49   >> CI detected: Jenkins
23:51:49  
23:51:49   >> Branch detected
23:51:49     >> release/1.1.3
23:51:49  
23:51:49   >> Info
23:51:49     >> Redefined channel by CI branch matching with 'release/*', setting CONAN_CHANNEL to 'stable'
23:51:49  Traceback (most recent call last):
23:51:49    File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/conans/client/graph/python_requires.py", line 44, in _look_for_require
23:51:49      python_require = self._cached_requires[require]
23:51:49  KeyError: 'CommonConan/1.0.0@project_x/stable'
```

Fixed after downgrading:
```
23:58:29 Version: 0.26.0
23:58:29   >> CI detected: Jenkins
23:58:29  
23:58:29   >> Branch detected
23:58:29     >> release/1.1.3
23:58:29  
23:58:29   >> Info
23:58:29     >> Redefined channel by CI branch matching with 'release/*', setting CONAN_CHANNEL to 'stable'
23:58:29  CommonConan/1.0.0@project_x/stable: Not found in local cache, looking in remotes...
23:58:29  CommonConan/1.0.0@project_x/stable: Trying with 'conan-center'...
23:58:29  CommonConan/1.0.0@project_x/stable: Trying with 'upload_repo'...
23:58:29  Downloading conanmanifest.txt
23:58:29  
23:58:29  Downloading conanfile.py
23:58:29  
23:58:29  Downloading conan_export.tgz
23:58:29  
23:58:30  ....
23:58:30  CommonConan/1.0.0@project_x/stable: Downloaded recipe revision 0
```

**Comment by memsharded** [comment]
I have proposed a fix in #379 that I think could help, but being honest, I havent been able to reproduce the ``KeyError`` error, because that exception is captured, I still have no idea you are seeing this behavior, but I think that PR might fix it.

**Comment by sboehmann** [comment]
Thank you very much. I will try the fix. 

> Conan 1.15 has learned to manage python_requires from remotes too, automatically.
Does this mean that I don't need to call `conan remote add` anymore? Great!

**Comment by lasote** [comment]
@sboehmann did you manage to try the PR? thanks

**Comment by sboehmann** [comment]
Currently I have no access to the original system. As soon as I have access again, I will test it there.
But in the meantime I've tested it on another setup (unfortunately slightly different) and it seems to fix my problem.

**Comment by grisumbras** [comment]
I had the same error in CI (https://github.com/grisumbras/enum-flags/pull/22/checks?check_run_id=137675878). Tried the fix locally and it does solve the issue.

**Comment by sboehmann** [comment]
@lasote I tested it again and as far as I can tell the issue is fixed. Thank you very much for your quick solution!
