### ISSUE TITLE
Old version of CMake in the images in the Docker Hub

### ISSUE THREAD

**Issue by btolfa** [conan-io/conan-package-tools#38]
The following images in the Docker Hub have CMake 3.4 instead of CMake 3.7 which is expected according to [Dockerfile](https://github.com/lasote/conan-docker-tools)
* [lasote/conangcc62](https://hub.docker.com/r/lasote/conangcc62)
* [lasote/conangcc49](https://hub.docker.com/r/lasote/conangcc49)

Please also add links to Dockerfile to Docker Hub image's pages.

**Comment by lasote** [comment]
Hi @btolfa I've created a README in the [conan docker tools repo](https://github.com/lasote/conan-docker-tools) with the link to Dockerhub.
I've also pushed to 6.2 and 4.9 images.

Thanks!
