### ISSUE TITLE
Prepare for Conan 1.16

### ISSUE THREAD

**Issue by lasote** [conan-io/conan-package-tools#383]
### Environment Details
* Conan Package Tools Version: **0.23.0**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 16.04**
* Compiler+version: **gcc-5.4**
* Docker image: **conanio/gcc7**
* Conan version: **conan 1.2.0**
* Python version: **python 3.7.0**

**Comment by uilianries** [comment]
I can take care of this.

**Comment by uilianries** [comment]
Closed by #384
