### ISSUE TITLE
CONAN_OPTIONS not working on Windows

### ISSUE THREAD

**Issue by bredej** [conan-io/conan-package-tools#386]
### Description of Problem, Request, or Question
I try to disable shared versions of a library by setting the environment variable 
CONAN_OPTIONS to foobar.core:shared=False

### Environment Details
* Conan Package Tools Version: **0.28.0**
* Operating System: **Windows 10**
* Operation System Version: **64-bit**
* Compiler+version: **VS 2017 - 15.9.12**
* Docker image: **NA**
* Conan version: **conan 1.16.0**
* Python version: **python 3.7.3**

### Steps to reproduce (Include if Applicable)
set CONAN_VISUAL_RUNTIMES=MD,MDd
set CONAN_BUILD_TYPES=Release,Debug
**set CONAN_OPTIONS=foobar.core:shared=False**
python build.py

### Build logs (Include if Available)
+--------------------+--------------+--------+--------------------+---------------+-------------------+
| compiler.runtime   | build_type   | arch   |   compiler.version | compiler      | foobar.core:shared   |
|--------------------+--------------+--------+--------------------+---------------+-------------------|
| MD                 | Release      | x86_64 |                 15 | Visual Studio | False             |
| MD                 | Release      | x86_64 |                 15 | Visual Studio | True              |
| MDd                | Debug        | x86_64 |                 15 | Visual Studio | False             |
| MDd                | Debug        | x86_64 |                 15 | Visual Studio | True              |
+--------------------+--------------+--------+--------------------+---------------+-------------------+

**Comment by uilianries** [comment]
Hi @bredej !

I'm curious, why does the name of your package contain a '.'? Is the name "foobar.core"?

**Comment by uilianries** [comment]
`shared` is an special option, you can disable it by:

```python
from cpt.packager import ConanMultiPackager

if __name__ == "__main__":
    builder = ConanMultiPackager()
    builder.add_common_builds(shared_option_name=False)
    builder.run()
```

Is it enough for you, or you really need the env var?

**Comment by bredej** [comment]
It's possible to have multiple '.' in a filename.
I suspected the dot to be the cause so I tried to replace it with an underscore with the same result.

I want to temporarily disable shared libraries to reduce the build time (Jenkins) so a program argument or environment variable is preferred.  I can probably modify build.py to accomplish this.

**Comment by uilianries** [comment]
anyway, looks like a bug, but modifying build.py will be faster for you

**Comment by bredej** [comment]
Thanks I'll do that.

**Comment by csguth** [comment]
> `shared` is an special option, you can disable it by:
> 
> ```python
> from cpt.packager import ConanMultiPackager
> 
> if __name__ == "__main__":
>     builder = ConanMultiPackager()
>     builder.add_common_builds(shared_option_name=False)
>     builder.run()
> ```
> 
> Is it enough for you, or you really need the env var?

I'd like to have a `CONAN_SHARED_OPTION_NAME` env var :(

**Comment by uilianries** [comment]
@csguth Please, open another issue, your case is feature request, otherwise, will be difficult manage both cases at same PR.

**Comment by uilianries** [comment]
Thinking again and checking the code, it's not a bug. The parameter `shared_option_name` is pretty old, and `CONAN_OPTIONS` was not designed to replace it. I would say @csguth request is the best choice, adding an env var.
