### ISSUE TITLE
[bug] package does not get built if already exists in repository

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan-package-tools#388]
Hi there,
I am using the current CPT (0.28.0) and Conan (1.16.0).

My question regards the possibility to force a build even if a package with the same ```packageId``` exists and is ```not outdated```.

The reason behind this is that I have a CI system with build nodes which do not necessarily clear the Conan repository. This means they will always find a "current" recipe and corresponding packages for it.

If I execute the build manually with ```conan create``` or ```conan build``` I can force a build and export of recipe/packages.

Is it possible to force CPT to export and build a recipe regardless if it exists and in what state the existing recipe/packages are (missing/current/outdated)?

EDIT: This relates to another issue I had with CPT and CI build system/nodes: https://github.com/conan-io/conan-package-tools/issues/239

**Comment by uilianries** [comment]
CPT uses conan create to build all packages, so even if you have a built package in your cache, CPT will be build it again. Only the upload is skipped when the same package id is not outdated from remote.

**Comment by Johnnyxy** [comment]
Hm, I saw some output recently that indicated otherwise. That is the reason why I asked. 
I will check next week as I do not have the build logs at the moment and close this issue then if possible.

**Comment by Johnnyxy** [comment]
I tested it again and it I cannot definetly pinpoint it as CPT standalone problem.
I have a test library and a test programm that uses test library. And I want to built the programm regardless if the code or the built binary has changed. But CPT/Conan says:
> testlibrary/2.4.0@test/testing: Already installed!
testprog/2.4.0@test/testing: Already installed!

> \>\> Skipping upload for HASH, it hasn't been built


resulting CPT output
---------------------
> Exporting package recipe
testprog/2.4.0@test/testing: Repo origin deduced by 'auto': URL
testprog/2.4.0@test/testing: WARN: Repo status is not pristine: there might be modified files
testprog/2.4.0@test/testing: Revision deduced by 'auto': cf27a822f7b81d86f2e24bdd2bfb4b44018df6e6
testprog/2.4.0@test/testing: The stored package has not changed
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=14
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

> testlibrary/2.4.0@test/testing: Package is up to date
testprog/2.4.0@test/testing: Package is up to date
Version ranges solved
    Version range '=2.4.0' required by 'testprog/2.4.0@test/testing' resolved to 'testlibrary/2.4.0@test/testing'

> Installing package: testprog/2.4.0@test/testing
Requirements
    testprog/2.4.0@test/testing from local cache - Cache
    testlibrary/2.4.0@test/testing from local cache - Cache
Packages
    testprog/2.4.0@test/testing:4b949be265100b48432e003cc888d62c89ea45c3 - Cache
    testlibrary/2.4.0@test/testing:f8944634cf2c1d8862cdf0b0fe5ffff1860346c8 - Cache

> testlibrary/2.4.0@test/testing: Already installed!
testprog/2.4.0@test/testing: Already installed!

> \>\> Skipping upload for 4b949be265100b48432e003cc888d62c89ea45c3, it hasn't been built

**Comment by Johnnyxy** [comment]
I found out what caused this behaviour. I did set the environment variable ```CONAN_BUILD_POLICY``` to ```outdated```.
I thought by that Conan would build my recipe and build ```missing``` as well as ```outdated``` dependencies too. But in fact it did not build my recipe as the package in the repository was already "up-to-date".
