### ISSUE TITLE
LD does not search lib32 in docker images

### ISSUE THREAD

**Issue by Outurnate** [conan-io/conan-package-tools#39]
It would appear that ld is not searching the correct paths when building for 32 bit linux.  See the build log below

https://travis-ci.org/Outurnate/conan-FLAC/jobs/187063573

**Comment by lasote** [comment]
Are you sure there is a crti library for 32 bits installed in the system? It should be searching in the 32bits paths.

**Comment by Outurnate** [comment]
I downloaded the docker image myself and found crti in lib32 (which is on the search path)

**Comment by lasote** [comment]
We enabled some versions ago the ``CONAN_DOCKER_32_IMAGES`` env variable to use "native" 32 bits docker images. All this issues with the libraries are now solved. 
Please report if you still have any problem.
