### ISSUE TITLE
Question: Is there a way to force updating all dependencies ?

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan-package-tools#393]
Is there a way to force updating all dependencies from remote even if package exists in local cache.

Something like passing **--update** to the conan install command.

Thanks

**Comment by boussaffawalid** [comment]
Any updates ?

**Comment by uilianries** [comment]
CPT uses `conan create` to build the target package, but it supports update argument too. Why do you need this feature?

Usually CPT is used for CI environments, where most time only temporary folders are created, because you should be able to reproduce the same build every time.

**Comment by boussaffawalid** [comment]
conan create support the update option, however I didn't find a way to pass this option to CPT.

We use CPT in CI, and since we have a lot of conan dependencies we try to avoid re-downloading these deps from artifactory for every build. that is why we dont clean local conan cache.

Currently, CPT does not check the remote for updates if the package exist locally (as far as know), and this is problematic.
That is way we need to pass the --update option in order to check the remote for updates even thought a dependency with the same version exist in the local cache.

The question now is: how to pass the *update* argument to CPT ?

**Comment by uilianries** [comment]
You can't, actually not with the current version. We would need to add such feature.

**Comment by boussaffawalid** [comment]
looking forward for that.
Thanks!
