### ISSUE TITLE
[suggestion] Use numbered jobs

### ISSUE THREAD

**Issue by theirix** [conan-io/conan-package-tools#395]
For a large build, it's very hard to determine which build is running now because options and configurations could be very similar. Using job numbers simplify log analysis and estimating how much builds has been done currently.

A proposed solution is to use numbered jobs:
- print job numbers at the summary table at CPT start
- print "Build 1/4" before each build

Code for this idea is ready, I can make a PR. Currently it is opt-out via init parameter.

**Comment by uilianries** [comment]
Sounds good
