### ISSUE TITLE
Question: how to set an env var for just one package

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan-package-tools#400]
Hello,

Conan offer the ability to specify an env variable for just one package.

For example:
```
conan install . -e MyPackage:PATH=/other/path
```

This will set the PATH env var for  MyPackage and **only** MyPackage

Is there a way to achieve the same behaviour with conan-package-tools?

Best,
Walid

**Comment by uilianries** [comment]
Hi @boussaffawalid !

No, CPT does not have such argument. But why do you need this? If your package is not available in PATH, you can customize its PATH through `cpp_info`.

**Comment by boussaffawalid** [comment]
well, let me be more precise. 
I have an env var called MY_ENV_VAR shared across multiple conan packages.

For some CI build, I want to set  MY_ENV_VAR for my main package but not in the dependencies.

**Comment by uilianries** [comment]
Looking again I found a way to do what you want:

```python
from cpt.packager import ConanMultiPackager

if __name__ == "__main__":
    builder = ConanMultiPackager()
    builder.add(settings={"arch": "x86", "build_type": "Debug"},
                options={}, env_vars={"MyPackage:PATH": "/other/path"},
                build_requires={})
    builder.run()
```

As you can see, `build` is able to accept custom environment variables. But you will need to add all builds manually. Other option is updating all common builds:

```python
from cpt.packager import ConanMultiPackager

if __name__ == "__main__":
    builder = ConanMultiPackager()
    builder.add_common_builds()
    builder.update_build_if(lambda placeholder: True, new_env_vars={"MyPackage:PATH": "/other/path"})
    builder.run()
```

I think the second option much better. Regards

**Comment by boussaffawalid** [comment]
@uilianries that is helpfull, thanks :)
