### ISSUE TITLE
Travis CI: Linker error after updating cpt

### ISSUE THREAD

**Issue by Linux13524** [conan-io/conan-package-tools#403]
### Description of Problem, Request, or Question
Recent changes to my project ([YoutubeListDownloader](https://github.com/Linux13524/YoutubeListDownloader)) made Travis-CI to fail: undefined reference for sqlite3. But only for the test package. Since I didn't change anything that could make the linker fail I searched for what has changed since the last CI job and I could only find cpt and conan itself. So I tried the exact same revision that was working in the past (cpt version 0.25.1) again it it failed with cpt version 0.29.1. When I run the build locally with recent conan version 1.18.2 it works fine so I guess the problem comes from cpt.
Logs of both builds (old and new) are attached.

### Environment Details
* Conan Package Tools Version: **0.29.1**
* Compiler+version: **gcc-7.2** and **gcc-8.0.1**
* Docker image: **lasote/conangcc7** and  **lasote/conangcc8**
* Conan version: **conan 1.18.2**
* Python version: **python 3.6.7**

### Build logs (Include if Available)
[old.txt](https://github.com/conan-io/conan-package-tools/files/3563521/old.txt)
[new.txt](https://github.com/conan-io/conan-package-tools/files/3563522/new.txt)

**Comment by uilianries** [comment]
Hi @Linux13524 !

Lasote's docker images are deprecated. Please, update them to conanio/gcc7 and conanio/gcc8

**Comment by Linux13524** [comment]
Hi @uilianries 
Thanks for the tip! I tried with conanio images, too. Same linker error...

**Comment by uilianries** [comment]
@Linux13524  Okay, i'll take a look, thanks for reporting!

**Comment by uilianries** [comment]
Hi @Linux13524 !

Your sqlite3 was built with an incompatible libc version.

From your log:

`    sqlite3/3.27.2@bincrafters/stable from 'upload_repo' - Downloaded`

It's been downloaded from your repo, not from Bincrafters repository. You need to rebuild with a compatible version, you can use Conan Docker images, OR you can we Bincrafters version.

Regards!

**Comment by Linux13524** [comment]
Hi @uilianries 
Thanks! I deleted the incompatible packages and now it works again.
I cannot download from Bincrafters since I need packages for android and they are not provided by Bincrafters. 
Can you tell me what the correct way is to keep the packages up-to-date with conan? 
Why is the libc version not stored in the package if it can break builds when changed?

**Comment by uilianries** [comment]
> I cannot download from Bincrafters since I need packages for android and they are not provided by Bincrafters.

You need to use some compatible distribution based on Ubuntu to build your package, or re-build ALL package.

>  Can you tell me what the correct way is to keep the packages up-to-date with conan?

You can use the `update` argument:

    conan install -u

https://docs.conan.io/en/latest/reference/commands/consumer/install.html

> Why is the libc version not stored in the package if it can break builds when changed?

This topic is but in summary, it's complex to be done. You can follow some related discussions and put your ideas there, it will be appreciated:

https://github.com/conan-io/conan/issues/3972
https://github.com/conan-io/conan/issues/796

Anyway, you can customize your package settings, adding glibc there if you want. Here you can find more info how to do it:

https://docs.conan.io/en/latest/extending/custom_settings.html

**Comment by Linux13524** [comment]
@uilianries Thanks a lot for explanation!
