### ISSUE TITLE
[suggestion] Build policy to build all `requirements`

### ISSUE THREAD

**Issue by Morheit** [conan-io/conan-package-tools#436]
Hello!

According to [Conan documentation](https://docs.conan.io/en/latest/reference/commands/creator/create.html) - there is a possibility to build dependencies from sources with avoidance of the binary packages usage.

Currently, the Conan Package Tools propose the three options for the **CONAN_BUILD_POLICY**: **never**, **missing** and **outdated**.

It would be great to have an additional option (e.g: **all**) to build all package dependencies. Such option will add more flexibility during the CI, specially for the cases when the existing binary packages are not suitable for some reason.

**Comment by uilianries** [comment]
Hi @Morheit !

Interesting idea, but this is a Conan's feature, not a CPT feature. CPT (conan package tools) only uses Conan's API to run any command, so any behavior that you see here, or most of them, came from Conan. I would say move this feature request to https://github.com/conan-io/conan/issues instead. Once accepted and implemented, it should be available for CPT too.

Happy holidays!

**Comment by Morheit** [comment]
Hello @uilianries !

Thank you for the feedback!

The Conan's API already provides the feature to build dependencies from sources. It could be done by passing the **--build** argument without specifying of (never, missed, outdated) to one of the following command: `conan install`, `conan test`, `conan create`.
An example: `conan create . --build`

According to [Conan documentation](https://docs.conan.io/en/latest/reference/commands/creator/create.html):

> -b [BUILD], --build [BUILD]

> --build Build all from sources, do not use
                        binary packages.

> --build=never Never build, use binary
                        packages or fail if a binary package is not found.

> --build=missing Build from code if a binary package is
                        not found.

> --build=outdated Build from code if
                        the binary is not built with the current recipe or
                        when missing binary package.

Sorry for misunderstanding.

Happy holidays!

**Comment by uilianries** [comment]
I completely forgot about `--build` alone will build all packages. So, yes, we can add this feature.

**Comment by ericLemanissier** [comment]
It would be great if `CONAN_BUILD_POLICY` could support a list of package reference patterns too

**Comment by uilianries** [comment]
Good idea @ericLemanissier

**Comment by uilianries** [comment]
@ericLemanissier I suggest you opening a new issue for that request, because it requires extra implementation.
