### ISSUE TITLE
ConanMultiPackager is not compatible with Conanfile's set_name or set_version methods

### ISSUE THREAD

**Issue by detwiler** [conan-io/conan-package-tools#442]
If either of a Conanfile's `name` or `version` fields are replaced with their [corresponding `set_name` or `set_version` methods](https://docs.conan.io/en/latest/reference/conanfile/methods.html?highlight=set_version#set-name-set-version), `ConanMultiPackager` throws an exception. A workaround is to set the environment variable `CONAN_REFERENCE`,  but this is usually not convenient and defeats the purpose of these methods which is to dynamically compute the `name` and `version`.

### Environment Details
* Conan Package Tools Version: **0.30.4**
* Operating System: **Linux**
* Operation System Version: **Fedora 31**
* Conan version: **conan 1.21.1**
* Python version: **python 3.7.6**

### Steps to reproduce

1. Replace the `name` and/or `version` fields of a `Conanfile` with `set_name` and/or `set_version` methods.

```
def set_name(self):
    self.name = "myname"

def set_version(self):
    self.version = "myversion"
```

2. Call `ConanMultiPackager.add_common_builds`.

### Build logs

```
Traceback (most recent call last):
  File "build.py", line 15, in <module>
    builder.add_common_builds(pure_c=False)
  File "/usr/local/lib/python3.7/site-packages/cpt/packager.py", line 446, in add_common_builds
    raise Exception("Specify a CONAN_REFERENCE or name and version fields in the recipe")
Exception: Specify a CONAN_REFERENCE or name and version fields in the recipe
```

**Comment by uilianries** [comment]
Hi @detwiler Thanks for reporting it!
