### ISSUE TITLE
os.getcwd() is used in DockerCreateRunner

### ISSUE THREAD

**Issue by gomons** [conan-io/conan-package-tools#447]
* Conan Package Tools Version: **0.30.4**
* Operating System: **Linux**

### Additional info
Class DockerCreateRunner uses os.getcwd():
````
command = ('%s docker run --rm -v "%s:%s/project%s" %s %s %s %s %s '
            '"%s cd project && '
            '%s run_create_in_docker "' % (self._sudo_docker_command,
                                            os.getcwd(),
                                            self._docker_conan_home,
                                            volume_options,
                                            env_vars_text,
                                            self._docker_run_options,
                                            self._docker_platform_param,
                                            self._docker_image,
                                            self._docker_shell,
                                            self._lcow_user_workaround,
                                            update_command))
````
I think it should use cwd parameter from ConanMultiPackager class

**Comment by uilianries** [comment]
Not actually. The idea behind is loading a conanfile according cwd, which is executed before to run DockerCreateRunner.

https://github.com/conan-io/conan-package-tools/blob/develop/cpt/packager.py#L212

`self.cwd` also is used with [chdir](https://github.com/conan-io/conan-package-tools/blob/2f7a5ac5b65c611a337829b39d0803eaed19411e/cpt/runner.py#L99), before calling Conan API. But it is useless on Docker context, because we use Docker volume before mounting:

https://github.com/conan-io/conan-package-tools/blob/2f7a5ac5b65c611a337829b39d0803eaed19411e/cpt/runner.py#L277

**Comment by gomons** [comment]
@uilianries Thanks for the quick response!

Maybe I'm doing something wrong. Is it possible to run build.py from a directory where there is no recipe? My configuration:
```
foo/build.py
bar/conanfile.py
```

And I run build.py from foo directory. This is why I use the cwd argument for ConanMultiPackager, which is bar in this case, and it works without docker. But with docker os.getcwd() returns foo directory. Therefore, the foo folder is mounted to docker but I expect bar folder.

**Comment by theirix** [comment]
Has been hit this issue too. This really makes sense when you have multiple directories with recipes (like in CCI with `recipes/libfoo/all`, `recipes/libbar/1.0`). If conanfile is loaded from `self.cwd` for introspection, then mounted Docker volume should be at `self.cwd` too. For now non-flat directory structure does not work with Docker.

A possible fix is to pass cwd to `DockerCreateRunner` and replace `os.getcwd()` with `self.cwd`.

**Comment by theirix** [comment]
@uilianries what do you think? I can make a PR so new behaviour can be checked for typical scenarios.

**Comment by uilianries** [comment]
@theirix Go ahead, let's see if is possible adding it without breaking the current behavior.

**Comment by uilianries** [comment]
fixed by https://github.com/conan-io/conan-package-tools/pull/528
