### ISSUE TITLE
AttributeError: 'PyRequireLoader' object has no attribute '_update'

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-package-tools#448]
### Description of Problem, Request, or Question

This error was reported by @grafikrobot 

### Environment Details
* Conan Package Tools Version: **0.30.4**
* Operating System: **Linux**
* Compiler+version: **clang 9**
* Docker image: **conanio/clang9**
* Conan version: **1.21.1**
* Python version: **python 3.7.0**

### Build logs (Include if Available)

https://dev.azure.com/grafikrobot/Boost%20Packages/_build/results?buildId=512&view=logs&j=d818e662-7181-5ce9-b265-50d03742b7af&t=b0499d19-2277-542f-081d-184ad1129b90&l=430

**Comment by memsharded** [comment]
It is necessary to call ``PyRequireLoader`` ``enable_remotes()`` method to initialize the behavior of the python-requires loader, before using it. Something like this:

```python
        conan_api.app.python_requires.enable_remotes(remotes=remotes)
        conan_api.app.pyreq_loader.enable_remotes(remotes=remotes)
        if Version(client_version) < Version("1.20.0"):
            return conan_api.app.loader.load_class(path)
        else:
            return conan_api.app.loader.load_basic(path)
```

**Comment by uilianries** [comment]
Thanks a lot @memsharded!
