### ISSUE TITLE
Update recommended travis.yml

### ISSUE THREAD

**Issue by theirix** [conan-io/conan-package-tools#45]
README.md suggests a slightly outdated versions of xcode.
Travis [stopped supporting](https://docs.travis-ci.com/user/osx-ci-environment/) xcode7.1 and xcode 6.2 recently so they are silently dispatched to the xcode 7.3 instead:

> This job was configured to run on an OS X image that was retired on November 28, 2016. It was routed to our Xcode 7.3.1 infrastructure.

Xcode 8.1 and 8.2 should be added.

There is a more generic question about a lifecycle of package's .travis.yml - how can it be updated? Should it be updated automatically or should the repository owner be notified about change?

**Comment by lasote** [comment]
> There is a more generic question about a lifecycle of package's .travis.yml - how can it be updated? Should it be updated automatically or should the repository owner be notified about change?

I don't understand what you mean. updated?

**Comment by theirix** [comment]
Every package built on Travis has a .travis.yml file. It came to the repository by copying from the other package or from the README. Once it added it rarely changed by the maintainer so it only lists old compilers until maintainer manually adds them. Surely it can be updated only by the maintainer because he is the owner of the repository.
So I meant how can it be improved? Is there any tool or online service that traverse all repositories and check whether .travis.yml is outdated?

**Comment by lasote** [comment]
No, there is not. I as a package creator will need to review all the .travis.yml by hand.

**Comment by lasote** [comment]
I've uploaded a new conan package tools version to pypi and fixed the README. Thanks for your help!
