### ISSUE TITLE
CONAN_PIP_COMMAND has no effect in docker conteiner

### ISSUE THREAD

**Issue by gomons** [conan-io/conan-package-tools#451]
* Conan Package Tools Version: **0.30.4**
* Operating System: **Linux**

### Steps to reproduce

1. Set the following environment variables:
CONAN_USE_DOCKER=True
CONAN_DOCKER_IMAGE_SKIP_UPDATE=False
CONAN_PIP_COMMAND=pip3
CONAN_DOCKER_IMAGE=_image where only pip3 is available_
1. Start CPT on Linux

**Actual result:**
CPT fails with the "pip: not found" error

**Expected result:**
pip command specified in CONAN_PIP_COMMAND variable is used

### Additional info
"pip install" command is hard-coded in this method: 
https://github.com/conan-io/conan-package-tools/blob/1699024a011b479d12c854c947b86e55e0aff0c2/cpt/runner.py#L212

**Comment by uilianries** [comment]
Why do you need it? All Conan docker images are configured to run `pip` as default, also it's used pyenv to install any python/pip version.

**Comment by gomons** [comment]
I need it because I use my own containers and I don't want to change them. I'm trying to configure CPT instead. But, unfortunately, some CPT settings have no effect inside the container.

The documentation says about support of specific set of containers. So it's probably not a bug. But it would be great to have additional build configuration tools supported in Docker.

**Comment by uilianries** [comment]
The problem is that I can't change CONAN_PIP_COMMAND to be executed in the container, otherwise, it will break most users which run a custom pip oh host, and the regular one in the container. Why don't you use conan docker images instead? You can create you docker images based on conan images too. Otherwise, I recommend using `alias` command to reach pip as your custom pip command.

**Comment by uilianries** [comment]
BTW the CONAN_PIP_COMMAND has been created only to solve problem under the host: https://github.com/conan-io/conan-package-tools/issues/147

**Comment by gomons** [comment]
I see that backward compatibility can be an issue. If you decide to add this feature in the future, probably you can add bool variable CONAN_DOCKER_USE_PIP_COMMAND to control this behavior.
