### ISSUE TITLE
Question: pkg:shared=true for transitive dependencies?

### ISSUE THREAD

**Issue by mbodmer** [conan-io/conan-package-tools#456]
Hi I am using conan-package-tools to build multiple packages, depending on each other. I would like to build both static and shared versions.

When building a package with shared option, the package itself is built shared, but it is looking for static dependencies to link with. This might be OK in a special case, but for me when I build a shared library package I would like it to also depend on shared transitive dependencies.

e.g. for building shared openssl depending on shared zlib, I would set zlib:shared=True, openssl:shared=True to make openssl depend on shared zlib.

When I set these options in the environment variable CONAN_OPTIONS while building a package with conan-package-tools these options are also used for building static libs. So I would now get the correct linkage for shared libs, but not for static libs anymore.

I would simply like static libs depend on static libs and shared libs depend on shared libs.

How can I achieve this with package-tools/ConanMultiPackager? This seems to be the common case for me, so there sure is a way for it.

Thanks for any hints

**Comment by uilianries** [comment]
Hi @mbodmer !

You need to customize your CPT matrix: https://github.com/conan-io/conan-package-tools#filtering-or-modifying-the-configurations

As you can see on that example, you will need to check the shared option, and when true, change it to `*:shared=True`

**Comment by mbodmer** [comment]
@uilianries Thank you very much, you are very fast answering my questions!

With your help I've came up with this as a solution, documenting it here.

This is a generic script being used for multiple packages:

```python
from cpt.packager import ConanMultiPackager

def findSharedOptionRemoveIf(opts, value):
    for key in opts.keys():
        if 'shared' in key and opts[key] == value:
            opts.pop(key)
            return True
        return False

if __name__ == "__main__":
    builder = ConanMultiPackager()
    builder.add_common_builds(dll_with_static_runtime=True)
    builder.update_build_if(lambda build : findSharedOptionRemoveIf(build.options, True),
                        new_options={'*:shared': True})
    builder.update_build_if(lambda build : findSharedOptionRemoveIf(build.options, False),
                        new_options={'*:shared': False})
    builder.run()
```

**Comment by uilianries** [comment]
@mbodmer Thanks for sharing your solution! :clap: 

It can be helpful for more people!
