### ISSUE TITLE
update_build_if ( new_options )

### ISSUE THREAD

**Issue by jeremy-coulon** [conan-io/conan-package-tools#458]
### Description of Problem, Request, or Question
I am trying to add an option to my gtest packages only for Debug builds.
However it seems that the option is added to all my builds.

### Environment Details
* Conan Package Tools Version: **0.31.0**
* Conan version: **conan 1.22.2**
* Python version: **python 3.6**

### Steps to reproduce (Include if Applicable)

```python
builder = ConanMultiPackager(reference="gtest/1.8.1",
            gcc_versions=["7"],
            archs=["x86_64"],
            build_types=["Debug", "Release"],
            options=["gtest:build_gmock=False"])
builder.add_common_builds(pure_c=False)
builder.update_build_if(lambda build: build.settings["build_type"] == "Debug", 
    new_options={ 
        "gtest:debug_postfix": "test" 
    })
builder.run()
```

### Build logs (Include if Available)
 N | compiler | arch   | build_type | compiler.version | compiler.libcxx | gtest:build_gmock | gtest:debug_postfix
--|--------|-------|--------|-------|-------|-------------|--------
 1 | gcc      | x86_64 | Debug      |                7 | libstdc++       | False             | test                
 2 | gcc      | x86_64 | Release    |                7 | libstdc++       | False             | test

**Comment by uilianries** [comment]
Hi @jeremy-coulon Thanks for reporting that problem. Indeed it's a bug.

**Comment by uilianries** [comment]
@jeremy-coulon A new patch (0.31.1) will be available with a fix on the next week. Regards!

**Comment by uilianries** [comment]
Hi @jeremy-coulon ! The version 0.31.1 has been released. Please, update your CPT copy. I gonna close this issue, but you can re-open if you find any problem related to that bug. Regards!
