### ISSUE TITLE
Priority of visual_versions ConanMultiPackager's parameter vs CONAN_VISUAL_VERSIONS

### ISSUE THREAD

**Issue by lhcorralo** [conan-io/conan-package-tools#46]
_Disclaimer:_ I am a newbie using Conan and GitHub, so probably what I am proposing here is completely wrong, or the style is not correct... Sorry for that.

I am creating a package for a library that, under Windows, is only compilable using Visual Studio 2013 (12) and 2015 (14). I am trying to show this restriction in the build.py file, so looks like this:

```python
from conan.packager import ConanMultiPackager
if __name__ == "__main__":
    builder = ConanMultiPackager(username="demo")
    builder.add_common_builds(visual_versions = ["12", "14"])
    builder.run()
```

In my machine, I only have VS 2013 installed so, in order to build the packages, I tried this:

```cmd
set CONAN_VISUAL_VERSIONS="12" 
python build.py
```

However, the script tried to build the package using both VS 2013 and 2015 which caused a build error. Checking the code of [packager.py](https://github.com/conan-io/conan-package-tools/blob/0233c70780398db777780f7b0e39d7b1e125707d/conan/packager.py) I found:

```python
if visual_versions is not None:
    self.visual_versions = visual_versions
else:
    env_visual_versions = list(filter(None, os.getenv("CONAN_VISUAL_VERSIONS", "").split(",")))
    self.visual_versions = env_visual_versions or self.default_visual_versions
```

That is, the ConanMultiPackager's parameter has priority over the environment variable. However, in my opinion, the environment variable should have a higher priority, as it would allow to cover cases like this (a machine with only a VS environment installed) without having to modify the script.

Thanks in advance.

**Comment by memsharded** [comment]
> Disclaimer: I am a newbie using Conan and GitHub, so probably what I am proposing here is completely wrong, or the style is not correct... Sorry for that.
No worries! Don't be afraid of asking, all questions and feedback are always welcome.

I think you are right, the hardcoded stuff have priority over the environment variables. I think it is not easy to change that behavior without affecting many packages that are already using it assuming that; lets @lasote have a look.

In the meantime, I think you could override that behavior yourself:

```python
from conan.packager import ConanMultiPackager

visual_versions =  os.getenv("CONAN_VISUAL_VERSIONS", "12,14")
visual_versions = list(filter(None, visual_versions.split(",")))

if __name__ == "__main__":
    builder = ConanMultiPackager(username="demo")
    builder.add_common_builds(visual_versions=visual_versions )
    builder.run()
```

**Comment by lhcorralo** [comment]
Thank you!

@memsharded, Following your code, it is working now. For future references, the final build.py scrpt is:

```python
from conan.packager import ConanMultiPackager
import os

visual_versions =  os.getenv("CONAN_VISUAL_VERSIONS", "12,14")
visual_versions = list(filter(None, visual_versions.split(",")))

if __name__ == "__main__":
    builder = ConanMultiPackager(username="demo")
    builder.add_common_builds(visual_versions = visual_versions)
    builder.run()
```

And, for running it, from the cmd.exe

```cmd
set CONAN_VISUAL_VERSIONS=12
python build.py
```

Note that in my bug report I was setting `set CONAN_VISUAL_VERSIONS="12"` instead (my fault, sorry).
