### ISSUE TITLE
[suggestion] add support of conan lockfiles

### ISSUE THREAD

**Issue by k1rk** [conan-io/conan-package-tools#466]
We are trying to implement lockfiles and realized that cpt doesn't support it
More details on lockfiles [here](https://docs.conan.io/en/latest/versioning/lockfiles.html?highlight=lockfiles)

I will be happy to help with the implementation of this feature.

**Comment by uilianries** [comment]
Hi @k1rk ! Yes, indeed lockfiles is an excellent feature for CI.
