### ISSUE TITLE
Wrong password when using special characters

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-package-tools#49]
**Short explanation:**
When I try to upload some package, by conan_package_tools, I receive:

> ERROR: Wrong user or password.

**Full explanation:**
My user and password work well when I execute by conan's client:
```
$ conan user -r conan.io -p '<password-with-special-characters>' uilianries
Change 'conan.io' user from None (anonymous) to uilianries
```
However, when I use conan package tools, the authentication fails:
```
CONAN_USERNAME=uilianries CONAN_CHANNEL=ci CONAN_REFERENCE=libusb/1.0.21 CONAN_PASSWORD='<password-with-special-characters>' CONAN_UPLOAD=1 python build.py
```
At the end, all my builds pass, but the upload fails:

> ############## CONAN PACKAGE TOOLS ######################
> 
> INFO: ******** RUNNING UPLOAD COMMAND ********** 
> conan upload libusb/1.0.21@uilianries/ci --all --force 
> 
> #########################################################
> 
> ERROR: Wrong user or password. [Remote: conan.io]
> Traceback (most recent call last):
>   File "build.py", line 13, in <module>
>     builder.run()
>   File "/usr/local/lib/python2.7/dist-packages/conan/packager.py", line 273, in run
>     self._upload_packages()
>   File "/usr/local/lib/python2.7/dist-packages/conan/packager.py", line 375, in _upload_packages
>     raise Exception("Error with user credentials")
> Exception: Error with user credentials

I tried escape the special characters by '\\' (e.g. '1234\\&\\$foobar'), but didn't work.  

I read [packager.py](https://github.com/conan-io/conan-package-tools/blob/develop/conan/packager.py) and I just found a replace for double quotes. Another point is that, the password is forwarded to conan user command, by python os.system.

To simplify the analysis, I wrote the follow code:

```python
from os import getenv
from os import system
 
if __name__ == "__main__":
    env = getenv("CONAN_PASSWORD")
    env =  env.replace('"', '\\"')
    system("echo %s" % env)
    system("conan user -c")
    system("conan user -r conan.io -p %s uilianries" % env)
```

This piece works well when I export my password in quotes.

I'm using conan at version 0.20.2 and conan_package_tools 0.2.35 (both are latest).

I have no more ideas how to use the automatic upload with my password.

**Comment by memsharded** [comment]
So you mean, if you do:

```bash
$ export CONAN_PASSWORD="passwd w special"  # works
$ export CONAN_PASSWORD=passwd w special # it doesn't work
```
Is that right?

**Comment by uilianries** [comment]
Actually, it just work with this simple script, but two rules are required:
* single quoted
* escape special characters

For example, suppose that my password is *Con@N&$ilV$R*, so  if I try:
```shell
$ export CONAN_PASSWORD=Con@N&$ilV$R # it doesn't work
$ export CONAN_PASSWORD="Con@N&$ilV$R"  # it doesn't work
$ export CONAN_PASSWORD='Con@N&$ilV$R' # it doesn't work
$ export CONAN_PASSWORD='Con@N\&\$ilV\$R' # work well with the example only
```
The second and third statement doesn't works, because python doesn't preserve the single quote.  

I tried some new flavors, to preserve the quotes, but didn't work.
```shell
 export CONAN_PASSWORD="'"'Con@N&$ilV$R'"'"
 export CONAN_PASSWORD="'"'Con@N\\\&\\\$ilV\\\$R'"'"
```
All my attempts failed.

**Comment by lasote** [comment]
The escaping of quotes are done in the `ConanMultiPackager` constructor, so you can instance it and then override the `self.password` with the value that you want, Maybe it helps:

```
builder = ConanMultiPackager()
builder.password = os.getenv("CONAN_PASSWORD")

```

**Comment by uilianries** [comment]
Great! Worked as magic!

I added your statement at build.py file:
```python
 if __name__ == "__main__":
     builder = ConanMultiPackager()
     builder.password = getenv("CONAN_PASSWORD")
     builder.add_common_builds(pure_c=True)
     builder.run()
```

And I exported the password (e.g. _Con@N&$ilV$R_):
```shell
export CONAN_PASSWORD=\"Con@N\\\&\\\$ilV\\\$R\"    # works well
export CONAN_PASSWORD='"'Con@N\\\&\\\$ilV\\\$R'"'  # works well
```
The quotes were preserved and the special characters were escaped.  

Thanks guys!
