### ISSUE TITLE
The latest CPT is broken?

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan-package-tools#499]
In the latest Travis CI run I got the following errors:

```
Traceback (most recent call last):
  File "build.py", line 26, in <module>
    builder.run()
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/cpt/packager.py", line 599, in run
    self.run_builds(base_profile_name=base_profile_name)
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/cpt/packager.py", line 728, in run_builds
    r.run(pull_image=not pulled_docker_images[docker_image],
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/cpt/runner.py", line 251, in run
    envs = self.get_env_vars()
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/cpt/runner.py", line 338, in get_env_vars
    ret["CPT_BUILD_POLICY"] = escape_env(self._build_policy.join(",")) if self._build_policy else escape_env(self._build_policy)
AttributeError: 'list' object has no attribute 'join'
The command "./.travis/run.sh" exited with 1.
```

See more here: https://travis-ci.com/github/mpusz/units/jobs/349892743#L352-L364.

**Comment by ericLemanissier** [comment]
it looks like https://github.com/conan-io/conan-package-tools/pull/497#issuecomment-642828179

**Comment by uilianries** [comment]
@mpusz please update your script to use `list`, because we can have multiple build policies listed.

**Comment by mpusz** [comment]
I did (https://github.com/mpusz/units/blob/master/build.py#L12) but it didn't help (https://travis-ci.com/github/mpusz/units/jobs/349975659) 😢

**Comment by uilianries** [comment]
@mpusz Thanks for your feedback! I'll check it further.

**Comment by ericLemanissier** [comment]
the same issue is happening here https://github.com/bincrafters/conan-qt/runs/779773713#step:5:85

**Comment by uilianries** [comment]
Hi everyone! We should release a new version today (0.33.1) which contains a fix.

**Comment by ericLemanissier** [comment]
And we're back on track, thanks !

**Comment by uilianries** [comment]
![back on the rails](https://media.giphy.com/media/NGSbD5vI6lUvC/giphy.gif)

**Comment by mpusz** [comment]
Thank you!

**Comment by ericLemanissier** [comment]
@uilianries  I'm wondering if by re-railing the case where build_policy is explictely defined, we did not de-railed the case where build_policy is not explictely defined: https://ci.appveyor.com/project/bincrafters/conan-qt/build/job/lgfr57i3el6aqxw4#L354 All the requirements now have `Forced build from source`

**Comment by uilianries** [comment]
@ericLemanissier that's weird, because Bincrafters package tools don't change the build policy, it's None by default, which is the same value for Conan package tools. I need to investigate further

**Comment by uilianries** [comment]
@ericLemanissier The PR #507 contains a fix for that problem. Thanks for reporting. We should release a new version today or monday (depending of CI time).

**Comment by ericLemanissier** [comment]
once again, thanks!
I'm crossing fingers for CI to finish early

**Comment by uilianries** [comment]
Hello again! New release available for download (no more bug I hope)!

https://pypi.org/project/conan-package-tools/0.33.2/
