### ISSUE TITLE
[bug] Dependencies are now forced to be built from source

### ISSUE THREAD

**Issue by maxime-uavia** [conan-io/conan-package-tools#505]
Hello,

Thank you for taking the time to read my issue.

### Context

We have been using Conan to build packages for our CPP projects (with GitHub Actions), and since today, we had no problem.

We have implemented a CI with Conan and GitHub Actions, in order to trigger a build every time a commit is pushed on our main branches.

Yesterday, we merged a pull request that triggered a build for one of our project, and the build lasted for around 1 minute. We have added a cache for dependencies, so 1 minute is a normal time for this project.

### Problem

Today, we decided to re-run the build on GitHub Actions manually for the same commit, and this time it took around 4 minutes. By reading the logs, we found out that our dependencies were forced to be built from source.

After running other projects that use the Conan and GitHub Actions integration, all of our builds are taking way too much time, because they are forced to build our dependencies from source (from 3 minutes to 25 minutes).

### Additional test to confirm the problem

We decided to run a new docker container with an Ubuntu 18.04 image, and tried to build one of our projects.

Here is a part of the log we got:

```
protobuf/3.9.1@bincrafters/stable: Forced build from source
srp/0.19@uavia/stable: Forced build from source
boost/1.69.0@conan/stable: Forced build from source
```

Dependencies are also forced to be built from source, even if they are in the `./conan/data`.

### Environment Details
  * Operating System+version: Ubuntu 18.04 (under GitHub Actions)
  * Compiler+version: GCC 7
  * Conan version: 1.26
  * Python version: 3.7.7

### Logs

(1) The build from yesterday on GitHub Actions printed this:

```
srp/0.19@uavia/stable: Forced build from source
Installing package: srp/0.19@uavia/stable
Requirements
    protobuf/3.9.1@bincrafters/stable from 'bincrafters' - Cache
    srp/0.19@uavia/stable from local cache - Cache
Packages
    protobuf/3.9.1@bincrafters/stable:d351525cc53ebe68279edf1978846402420066e7 - Cache
    srp/0.19@uavia/stable:ef98836af63d5f06c8561fdb9e7f89b1f6472869 - Build
Build requirements
    protobuf/3.9.1@bincrafters/stable from 'bincrafters' - Cache
    protoc_installer/3.9.1@bincrafters/stable from 'bincrafters' - Cache
Build requirements packages
    protobuf/3.9.1@bincrafters/stable:d351525cc53ebe68279edf1978846402420066e7 - Skip
    protoc_installer/3.9.1@bincrafters/stable:c0c1ef10e3d0ded44179e28b669d6aed0277ca6a - Cache

Installing (downloading, building) binaries...
protobuf/3.9.1@bincrafters/stable: Already installed!
protoc_installer/3.9.1@bincrafters/stable: Already installed!
```

(2) And the build today:

```
protobuf/3.9.1@bincrafters/stable: Forced build from source
srp/0.19@uavia/stable: Forced build from source
protoc_installer/3.9.1@bincrafters/stable: Forced build from source
Installing package: srp/0.19@uavia/stable
Requirements
    protobuf/3.9.1@bincrafters/stable from 'bincrafters' - Cache
    srp/0.19@uavia/stable from local cache - Cache
Packages
    protobuf/3.9.1@bincrafters/stable:d351525cc53ebe68279edf1978846402420066e7 - Build
    srp/0.19@uavia/stable:ef98836af63d5f06c8561fdb9e7f89b1f6472869 - Build
Build requirements
    protobuf/3.9.1@bincrafters/stable from 'bincrafters' - Cache
    protoc_installer/3.9.1@bincrafters/stable from 'bincrafters' - Cache
Build requirements packages
    protobuf/3.9.1@bincrafters/stable:d351525cc53ebe68279edf1978846402420066e7 - Build
    protoc_installer/3.9.1@bincrafters/stable:c0c1ef10e3d0ded44179e28b669d6aed0277ca6a - Build

Installing (downloading, building) binaries...
Downloading conan_sources.tgz
protobuf/3.9.1@bincrafters/stable: Configuring sources in /home/runner/.conan/data/protobuf/3.9.1/bincrafters/stable/source

protobuf/3.9.1@bincrafters/stable: Copying sources to build folder
protobuf/3.9.1@bincrafters/stable: Building your package in /home/runner/.conan/data/protobuf/3.9.1/bincrafters/stable/build/d351525cc53ebe68279edf1978846402420066e7
protobuf/3.9.1@bincrafters/stable: Generator cmake created conanbuildinfo.cmake
protobuf/3.9.1@bincrafters/stable: Calling build()
```

### Question

Why our dependencies are now forced to be built from source, instead of using the already installed versions ?

**Comment by uilianries** [comment]
@patpir I've created a PR with a fix: #507 

We should provide a new version on next few days (maybe today)

**Comment by maxime-uavia** [comment]
First of all, thank you for the answers.

@jgsogo I was hoping that it could be a change in our .conf files, or anything related to a human modification.
But as I mentioned in my second message, I have been building the same commit from 16 days ago, when everything was working correctly, and I got the `Forced build from source` problem.

@patpir Indeed, we are using `conan_package_tools`, installed with the command `pip install conan_package_tools` in the script to install Conan in GitHub Actions. I am not in office today, but I could try to change the version on Monday and give the output.

In the GitHub Actions process, I am installing Conan Package Tools as shown below:
```
pip install conan --upgrade
pip install conan_package_tools
```

By not fixing the Conan Package Tools version, it makes me use the latest version. So my first test will be to switch back to Conan Package Tools 0.33.0, and keep you guys updated on the issue.

**Comment by maxime-uavia** [comment]
@uilianries  I just saw your commit about the build policy.

The python script to create the `ConanMultiPackager` looks like:
```
#!/usr/bin/env python3

from cpt.packager import ConanMultiPackager

if __name__ == "__main__":
    builder = ConanMultiPackager()
    builder.add({"arch": "x86_64", "build_type": "Release"}, {"helloworld-bin:shared": True})
    builder.run()
```

Would it fix the problem to replace this line:
```
    builder = ConanMultiPackager()
```

With this line:
```
    builder = ConanMultiPackager(build_policy="missing")
```

I remember setting one project `build_policy` to `missing`, but not for the rest of our projects.

**Comment by uilianries** [comment]
@maxime-uavia Please, update your CPT copy, the new release https://pypi.org/project/conan-package-tools/0.33.2/ is ready for download.

**Comment by maxime-uavia** [comment]
I updated the CPT package to `0.33.2` and it works like a charm, thank you !

**Comment by uilianries** [comment]
@maxime-uavia Thanks for your feedback!
