### ISSUE TITLE
[bug] VS compiler autodetection doesn't work

### ISSUE THREAD

**Issue by Ri0n** [conan-io/conan-package-tools#511]
### Environment Details (include every applicable attribute)
  * Operating System+version: Win10
  * Compiler+version: VS2019
  * Conan version: 1.26
  * Python version: 3.8

### Steps to reproduce (Include if Applicable)
Write a simple build.py
```
from conan.packager import ConanMultiPackager


if __name__ == "__main__":
    builder = ConanMultiPackager(visual_runtimes=["MD", "MDd"])
    builder.add_common_builds(shared_option_name=False, pure_c=False)
    builder.run()
```
Run it. 
It tries to use not installed VS versions 14 and 15. When I have 16 installed.

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
conans.errors.ConanException: VS non-existing installation: Visual Studio 14
```

**Comment by uilianries** [comment]
Hello @Ri0n !

CPT doesn't check compiler/build system, it runs a matrix with all possible combinations by default. This is well explained here: https://github.com/conan-io/conan-package-tools#generating-the-build-configurations-automatically

If you have only a version installed, you should set the environment variable `CONAN_VISUAL_VERSIONS=16` as described on the README file.

Regards

**Comment by Ri0n** [comment]
Thanks.
Is there any configuration file for such things to not mix with system env?
I tried to limit VS versions via conan settings files. but package tools ignore them. That's weird.
