### ISSUE TITLE
Disable test package build

### ISSUE THREAD

**Issue by Linux13524** [conan-io/conan-package-tools#515]
### Description of Problem, Request, or Question

I just tried to disable the test packages build in a GitLab-CI pipeline by setting `CPT_TEST_FOLDER` to "False". Unfortunately it is recognized as string instead of boolean, so CPT is searching for the "False" test package directory. 
I also tried by setting the `test_folder` parameter to the actual boolean `False`, but then CPT tries to get the value from `CPT_TEST_FOLDER` (and if not there, sets `test_folder` to `None`).

Is there a valid way to disable the test package build with conan package tools?

### Environment Details
* Conan Package Tools Version: **0.34.0**
* Conan version: **conan 1.27.1**

**Comment by uilianries** [comment]
Did you pass `CPT_TEST_FOLDER="False"` or `CPT_TEST_FOLDER=False`? The second one is the correct and should work.

**Comment by Linux13524** [comment]
For testing, I set `os.environ["CPT_TEST_FOLDER"] = "False"` in `build.py` and tried locally, so that I don't have to push. Setting `os.environ["CPT_TEST_FOLDER"] = False` was not possible. 

I just tried to set `CPT_TEST_FOLDER` in the `.gitlab-ci.yml` but I get a linter error when leaving out the quotation marks.

Do environment variables even differe between types?

**Comment by uilianries** [comment]
@Linux13524 checking again, I confirm your behavior, it's a bug. I'll try to push to the next release (today probably).

**Comment by Linux13524** [comment]
Thanks a lot!

**Comment by uilianries** [comment]
@Linux13524 The PR #518 contains the fix for your problem and will be available on CPT 0.34.1.

I'm closing this issue now, but feel free to re-open if you find any related problem with 0.34.1.

Regards!
