### ISSUE TITLE
Stable username option

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-package-tools#52]
Hi!

The conventional behavior using conan is, each user provides some channel with it packages, for example, I created libusb package at conan.io, so, who wants this package, will look at uilianries/stable. Okay, this works and everybody goes happy to home.

However, if you use conan at your company and want to create some main stable channel, this approach will not fit very well. For example, the developers Foo, Qux and Baz, use the same package in some project, but no one wants to keep searching who is the maintainer of package and where is the real stable package, so, the solution is create a main user name: Company. After this point, all developers know the stable channel will be at Company/version. But, I new problem comes, who is Company user maintainer and who submits in it channel? Any one could submit, since the package was validate (build, tests ...).

The Conan package tools switch to stable channel when it found some pattern in branch name. But, consider the situation where my package will be the main package for all developers, so I'll need bring this package to Company user. To do this, I need to change the user name and password to upload at stable channel. This works, but is a quite manual.

To turn this process more automatic, the user name could be switched by stable pattern, some like this:
```python
# packager.py:490

if channel:
    self.logger.warning("Redefined channel by CI branch matching with '%s', "
"setting CONAN_CHANNEL to '%s'" % (pattern, channel))
	self.username = getenv("CONAN_STABLE_USERNAME", self.username)
	self.password = getenv("CONAN_STABLE_PASSWORD", self.password)
```
This piece will change the current user name to a stable user name, when the stable channel is used. If a stable user name was not defined, so, the current user name is maintained as before. The same behavior is applied to password.

The stable switch for user name allows an automatic switch not just for channel. So, when I need some package, by default, I'll search at Company user, instead to ask who is the real maintainer.

**Comment by lasote** [comment]
0.2.37 released with those lines and updated README.md
