### ISSUE TITLE
Allow for custom package root path

### ISSUE THREAD

**Issue by mikedld** [conan-io/conan-package-tools#53]
Currently, `ConanMultiPackager._docker_pack` method has path to "project" directory hard-coded:
```python
command = "sudo docker run --rm -v %s:/home/conan/project -v " \
          "~/.conan/data:/home/conan/.conan/data -it %s %s /bin/sh -c \"" \
          "cd project && sudo pip install conan_package_tools --upgrade %s && " \
          "conan_json_packager\"" % (curdir, env_vars, image_name, specific_conan_package)
```

I would like to be able to use custom path (e.g. subdirectory of "project"), maybe via another `CONAN_...` environment variable. This would allow for multiple packages to be stored within a single repository.

**Comment by mikedld** [comment]
Sorry, somehow I missed that it's already supported: one just needs to change the working directory before packaging.

**Comment by memsharded** [comment]
No worries. Great you were fast at finding the solution.
