### ISSUE TITLE
Wrong Docker run command is printed if the build profile uses Carriage Return/Line Feed line endings

### ISSUE THREAD

**Issue by sbannier** [conan-io/conan-package-tools#543]
### Description of Problem, Request, or Question

The printed Docker run command is missing the **CPT_BASE_PROFILE** environment variable argument and in some cases **CPT_PROFILE** includes invalid string fragments from the build profile (which is not the case in the example below as I could not really reproduce that behaviour). 
The execution of the Docker run command from within the Conan Package Tools seems to be unaffected, i.e. Docker will be started with the correct argument. Only the printed command is wrong.

### Environment Details
* Conan Package Tools Version: **0.35.0**
* Operating System: **Windows**
* Operation System Version: **Windows 10 (also if using WSL2 with Ubuntu 20.04)**
* Docker image: **ubuntu:18.04**
* Conan version: **conan 1.31.4**
* Python version: **python 3.8.3**

### Steps to reproduce
This archive includes the conanfile + build.py script
[project.zip](https://github.com/conan-io/conan-package-tools/files/5886538/project.zip)
This archive contains the profile with CR/LF line endings
[profile.zip](https://github.com/conan-io/conan-package-tools/files/5886560/profile.zip)

* Unzip both, copy profile in .../.conan/profiles
* Run **python build.py**
* Observe the printed docker run command following the Docker whale ASCII art image

### Build logs (Include if Available)
Correct output with 'Unix' style line endings:
` >> sudo -E docker run --rm -v "/home/bannier/work/temp/cpt:/home/conan/project" -e CONAN_REFERENCE="cpt-bug/1.0" -e CPT_PROFILE="@@include(crlf)@@@@[settings]@@@@[options]@@@@[env]@@@@[build_requires]@@@@" -e CPT_BASE_PROFILE="[settings]@@os=Linux@@os_build=Linux@@arch=x86_64@@arch_build=x86_64@@compiler=gcc@@compiler.version=9@@compiler.libcxx=libstdc++@@build_type=Release@@" -e CPT_BASE_PROFILE_NAME="crlf" -e CONAN_TEMP_TEST_FOLDER="1" -e CPT_UPLOAD_RETRY="3" -e CPT_CONANFILE="conanfile.py"   ubuntu:18.04 -c " cd project &&  run_create_in_docker "`

Wrong output with Carriage Return + Line Feed line endings (**CPT_BASE_PROFILE** is missing):
` >> sudo -E docker run --rm -v "/home/bannier/work/temp/cpt:/home/conan/project" -e CONAN_REFERENCE="cpt-bug/1.0" -e CPT_PROFILE="@@include(crlf)@@@@[settings]@@@@[options]@@@@[env]@@@@[build_requires]@@" -e CPT_BASE_PROFILE_NAME="crlf" -e CONAN_TEMP_TEST_FOLDER="1" -e CPT_UPLOAD_RETRY="3" -e CPT_CONANFILE="conanfile.py"   ubuntu:18.04 -c " cd project &&  run_create_in_docker "`

**Comment by uilianries** [comment]
Fixed by #545

It should be available on CPT 0.35.1
