### ISSUE TITLE
Add support for Build Profile and Host Profile

### ISSUE THREAD

**Issue by mymichu** [conan-io/conan-package-tools#550]
### Description of Problem

Hi we are using conan for building applications on ARM devices. This requires sometimes to set a Host- and Build-Profile for the package build. It would be nice if this feature is supported by the conan-package-tools.

### Environment Details
* Conan Package Tools Version: **0.23.0**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 20.04**
* Compiler+version: **arm-noneabi-gcc-10**
* Conan version: **conan 1.33.0**
* Python version: **python 3.7.0**

**Comment by ghost** [comment]
We had the same issue at my company and a colleague implemented a quick hack that we are using. I can try to clean that up a little and maybe create a pull request in the next days.

**Comment by uilianries** [comment]
@smartSBA It would be great!

**Comment by uilianries** [comment]
Implemented by #555 and should be available on next release 0.36
