### ISSUE TITLE
[Question] How can I set a remote to use for downloading dependencies?

### ISSUE THREAD

**Issue by italiks** [conan-io/conan-package-tools#568]
### Question
I have a package which depends on another package hosted on our private server and build fails due to not finding appropriate configuration.
I've tried to pass `ConanMultiPackager(remotes='path/to/private/server')` but it did not work.
Is it possible to set remote to download dependencies in **CPT**?
Or somehow set default remote in Conan itself?

### Environment Details
* Conan Package Tools Version: **0.35.1**
* Operating System: **Windows**
* Operation System Version: **10**
* Compiler+version: **MSVC16**
* Conan version: **conan 1.37.0**
* Python version: **python 3.8.0**

Thanks in advance!

**Comment by italiks** [comment]
Any ideas @uilianries ?

**Comment by uilianries** [comment]
What do you mean by "private server"? Artifactory or Conan Server? 

As listed [here](https://github.com/conan-io/conan-package-tools#working-with-bintray-configuring-repositories), the remote should be an URL, not folder path. Also, it accepts more than one remote, so I think is totally possible to solve you case, just need to pass the correct address.

In case you are running Artifactory (recommended), you can a look [here](https://www.jfrog.com/confluence/display/RTF5X/Conan+Repositories) how to obtain the URL for remote.

However, if you are running the old Conan Server, take a look [here](https://docs.conan.io/en/latest/uploading_packages/running_your_server.html)

**Comment by italiks** [comment]
Yeh, I have an Artifactory private server. 
I did everything according to the tutorial you gave. 

Here is a sample and error I got:

```
for package in packages:
        conanfile = os.path.join(os.getcwd(), package, 'conanfile.py')
        builder = ConanMultiPackager(
                                    conanfile=conanfile,
                                    username='tfs-build',
                                    password='bot-P@ssw0rd',
                                    remotes='http://10.150.10.7:8081/artifactory/api/conan/avq-repo',
                                    upload='http://10.150.10.7:8081/artifactory/api/conan/avq-repo',
                                    upload_dependencies='all',
                                    visual_runtimes=['MD', 'MDd'],
                                    visual_versions=['16'],
                                    visual_toolsets={'16':['v142']},
                                    archs=['x86', 'x86_64'],
                                    build_types=['Release', 'Debug']
                                    )
        builder.add_common_builds()
        builder.run()
```

```
Installing package: pkcs11-helper/1.27@tfs-build/stable
Requirements
    openssl/1.1.1k from 'conancenter' - Downloaded
    pkcs11-helper/1.27@tfs-build/stable from local cache - Cache
Packages
    openssl/1.1.1k:29d1f4003b3f7143826ef1988625574513d526ce - Missing
    pkcs11-helper/1.27@tfs-build/stable:dda70aa88f96e2cc7cd146e03424a0cbb3913f16 - Build

Cross-build from 'Windows:x86_64' to 'Windows:x86'
Installing (downloading, building) binaries...
ERROR: Missing binary: openssl/1.1.1k:29d1f4003b3f7143826ef1988625574513d526ce
...
Try to build from sources with '--build=openssl'
Use 'conan search <reference> --table table.html'
```

As you can see it still refers to 'conancenter', not to a provided remote

**Comment by uilianries** [comment]
It's curious your remote name for Conan center, because the default one should be `conan-center` not, `conancenter`

Anyway, you have two options:

- Disable `conan-center` before building and enabling again after all CPT execution:

```python
from conans.client.conan_api import Conan

...
conan_api, _, _ = Conan.factory()
try:
    conan_api.remote_set_disabled_state("conancenter", True)
    <Conan Package Tools Code here>
finally:
    conan_api.remote_set_disabled_state("conancenter", False)
```

- Forcing your remote as first on the list, before building all packages:

```python
conan_api, _, _ = Conan.factory()
builder = ConanMultiPackager(...)
conan_api.remote_update("upload_repo", "http://10.150.10.7:8081/artifactory/api/conan/avq-repo", verify_ssl=False, insert=0)
builder.add_common_builds()
builder.run()
```

Here, the remote name is `upload_repo`, because CPT renames your custom remotes to `remote<index-number>`, but as your upload url is the same, CPT uses the name `upload_repo`.


As feature request for the future (won't be implemented right now), could be considered an option to enforce all CPT remotes first, like "CPT_REMOTES_FIRST_INDEX".

**Comment by uilianries** [comment]
@danimtb told me `conancenter` is correct too. So probably you have both:

```
conancenter: https://center.conan.io [Verify SSL: True]
conan-center: https://conan.bintray.com [Verify SSL: True]
```

Regards

**Comment by italiks** [comment]
@uilianries Thanks for your answer but it didn't help.

Here is an error
```
Traceback (most recent call last):
  File ".\build.py", line 119, in <module>
    build_packages(packages, conan_api)
  File ".\build.py", line 100, in build_packages
    conan_api.remote_update("upload_repo", "http://10.150.10.7:8081/artifactory/api/conan/avq-repo", verify_ssl=False, insert=0)     
  File "...\site-packages\conans\client\conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "...\site-packages\conans\client\conan_api.py", line 1021, in remote_update
    return self.app.cache.registry.update(remote_name, url, verify_ssl, insert)
  File "...\site-packages\conans\client\cache\remote_registry.py", line 351, in update
    remotes.update(remote_name, url, verify_ssl, insert)
  File "...\site-packages\conans\client\cache\remote_registry.py", line 273, in update
    raise ConanException("Remote '%s' not found in remotes" % remote_name)
conans.errors.ConanException: Remote 'upload_repo' not found in remotes
```

**Comment by italiks** [comment]
> @danimtb told me `conancenter` is correct too. So probably you have both:
> 
> ```
> conancenter: https://center.conan.io [Verify SSL: True]
> conan-center: https://conan.bintray.com [Verify SSL: True]
> ```
> 
> Regards

Yes, I have both of them.
Here is my remote list:

- conan-avq: http://10.150.10.7:8081/artifactory/api/conan/avq-repo [Verify SSL: False]
- conancenter: https://center.conan.io [Verify SSL: True]
- conan-center: https://conan.bintray.com [Verify SSL: True]

**Comment by italiks** [comment]
> It's curious your remote name for Conan center, because the default one should be `conan-center` not, `conancenter`
> 
> Anyway, you have two options:
> 
> * Disable `conan-center` before building and enabling again after all CPT execution:
> 
> ```python
> from conans.client.conan_api import Conan
> 
> ...
> conan_api, _, _ = Conan.factory()
> try:
>     conan_api.remote_set_disabled_state("conancenter", True)
>     <Conan Package Tools Code here>
> finally:
>     conan_api.remote_set_disabled_state("conancenter", False)
> ```
> 
> * Forcing your remote as first on the list, before building all packages:
> 
> ```python
> conan_api, _, _ = Conan.factory()
> builder = ConanMultiPackager(...)
> conan_api.remote_update("upload_repo", "http://10.150.10.7:8081/artifactory/api/conan/avq-repo", verify_ssl=False, insert=0)
> builder.add_common_builds()
> builder.run()
> ```
> 
> Here, the remote name is `upload_repo`, because CPT renames your custom remotes to `remote<index-number>`, but as your upload url is the same, CPT uses the name `upload_repo`.
> 
> As feature request for the future (won't be implemented right now), could be considered an option to enforce all CPT remotes first, like "CPT_REMOTES_FIRST_INDEX".

Seems like I've found a solution.
I've removed conan-avq from remote list and this solution worked.
Thanks @uilianries !

**Comment by uilianries** [comment]
@italiks Thank you for sharing your solution! Glad is working now!
