### ISSUE TITLE
Unit tests fail with conan >= 1.37.0

### ISSUE THREAD

**Issue by ghost** [conan-io/conan-package-tools#570]
### Unit tests fail

From 1.37.0 Conan adds two default remotes. The remotes list looks like this:

    [Remote(name='conancenter', url='https://center.conan.io', verify_ssl=True, disabled=False), 
     Remote(name='conan-center', url='https://conan.bintray.com', verify_ssl=True, disabled=False)]

The new `conancenter` remote has been added in 1.37.0.

The tests `cpt/test/integration/remotes_test.py` only remove the ´conan-center´ remote but not the new `conancenter`, which results in the remotes list not being empty.

### Environment Details
* Conan Package Tools Version: **0.35.1**
* Operating System: **Any**
* Operation System Version: **Any**
* Compiler+version: ****
* Docker image: **conanio/gcc7**
* Conan version: **conan 1.37.0**
* Python version: **python 3.6.9**

### Steps to reproduce (Include if Applicable)
Run unit tests

**Comment by ghost** [comment]
I think this has been solved by PR  https://github.com/conan-io/conan-package-tools/pull/578 and can be closed.

**Comment by uilianries** [comment]
Thank you!
