### ISSUE TITLE
Add MSVC compiler support throughout CPT

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-package-tools#580]
CPT should start supporting the new MSVC compiler model from the Conan client.

Thankfully, the current support for the MS compiler was named `VISUAL` in most places (except one internal test as fast as a very quick search showed), so the term `MSVC` can be used for environment variables like `CONAN_MSVC_VERSIONS`

**Comment by jwillikers** [comment]
This would make CPT way more useful.
