### ISSUE TITLE
Regression on 0.3.1: ValueError: too many values to unpack

### ISSUE THREAD

**Issue by nunojpg** [conan-io/conan-package-tools#59]
This build now fails:

https://travis-ci.org/nunojpg/conan-restbed/jobs/222866566

+python build.py
############## CONAN PACKAGE TOOLS ######################
WARNING: Redefined channel by CI branch matching with 'master', setting CONAN_CHANNEL to 'stable' 
#########################################################
Traceback (most recent call last):
  File "build.py", line 7, in <module>
    for settings, options in builder.builds:
ValueError: too many values to unpack
The command "./.travis/run.sh" exited with 1.

**Comment by memsharded** [comment]
Sorry for this regression. Please use previous version of conan-package-tools until we have a look.
Thanks very much for reporting.

**Comment by nunojpg** [comment]
It was failing because I needed to update build.py with:

for settings, options, env_vars, build_requires in builder.builds:

It was in fact a regression, as the previous scripts always try to use the newest version, but then fail to work.

Maybe you should implement some semantic version in the scripts, for example the current ones should only try to install the latest 3.x...

**Comment by memsharded** [comment]
Sure, the new version changes are huge, so regressions are likely.
I see you already fixed your build (https://travis-ci.org/nunojpg/conan-restbed/jobs/224599124, despite an upload error). Your idea about versioning the scripts is a possibility, but not sure about the complexity/value ratio, the fix of build.py is simple. Lets wait for @lasote feedback.

**Comment by nunojpg** [comment]
Just to be clear, the problem is that the conan_package_tools API is not stable, so it breaks the user side scripts when it is updated, like in this case.

I.e., at .travis/install.sh it executes "pip install conan_package_tools".

If conan_package_tools doesn't have a stable or semantic version stable API, then it should be locked down to a specific version, and allowing it to be updated to a potentially incompatible version, by design.

Of course this is user managed code, but your .travis/install.sh example is the gold standard, and it will be largely used like this, and every time you break API, people will have their builds failing and come here to report that as a bug.

So I suggest:

- Lock down to a specific version
- Print a message warning if version is not the latest, telling the developer that he needs to consider upgrading manually.

**Comment by lasote** [comment]
The API changing was never happened before and  probably won't happen in the future, but the 0.3 version is still a beta, so it can happen. To iterate the builds you will need to change your build.py script. For future veraiona I'll try to implement a way to pin the version also using docker. So you will need to pin the version  in the Travis install file and then run `pip list --outdated` if you can want to know if a new version is available.

**Comment by nunojpg** [comment]
Ok if it's beta. Thanks to consider the issue.
