### ISSUE TITLE
builder.builds = filtered_builds not filtering?

### ISSUE THREAD

**Issue by nunojpg** [conan-io/conan-package-tools#60]
I'm using a script similiar to the example to filter x86 builds, but the x86 builds were still present, so I added some debug prints:

```
    builder = ConanMultiPackager(username="nunojpg")
    builder.add_common_builds(shared_option_name="restbed:shared", pure_c=False)
    filtered_builds = []
    for settings, options, env_vars, build_requires in builder.builds:
        if settings["arch"] != "x86":
            filtered_builds.append([settings, dict(options.items() + [('restbed:ssl', False)]), env_vars, build_requires])
            filtered_builds.append([settings, dict(options.items() + [('restbed:ssl', True)]), env_vars, build_requires])
    print "filtered_builds="
    print filtered_builds
    builder.builds = filtered_builds
    print "builder.builds="
    print builder.builds
    builder.run()
```

The output is like this:

filtered_builds=
[[{'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Debug', 'compiler': 'gcc'}, {'restbed:shared': True, 'restbed:ssl': False}, {}, {}], [{'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Debug', 'compiler': 'gcc'}, {'restbed:shared': True, 'restbed:ssl': True}, {}, {}], [{'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Release', 'compiler': 'gcc'}, {'restbed:shared': True, 'restbed:ssl': False}, {}, {}], [{'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Release', 'compiler': 'gcc'}, {'restbed:shared': True, 'restbed:ssl': True}, {}, {}], [{'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Debug', 'compiler': 'gcc'}, {'restbed:shared': False, 'restbed:ssl': False}, {}, {}], [{'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Debug', 'compiler': 'gcc'}, {'restbed:shared': False, 'restbed:ssl': True}, {}, {}], [{'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Release', 'compiler': 'gcc'}, {'restbed:shared': False, 'restbed:ssl': False}, {}, {}], [{'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Release', 'compiler': 'gcc'}, {'restbed:shared': False, 'restbed:ssl': True}, {}, {}]]
builder.builds=
[BuildConf(settings={'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86', 'build_type': 'Debug', 'compiler': 'gcc'}, options={'restbed:shared': True}, env_vars={}, build_requires={}), BuildConf(settings={'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86', 'build_type': 'Release', 'compiler': 'gcc'}, options={'restbed:shared': True}, env_vars={}, build_requires={}), BuildConf(settings={'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86', 'build_type': 'Debug', 'compiler': 'gcc'}, options={'restbed:shared': False}, env_vars={}, build_requires={}), BuildConf(settings={'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86', 'build_type': 'Release', 'compiler': 'gcc'}, options={'restbed:shared': False}, env_vars={}, build_requires={}), BuildConf(settings={'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Debug', 'compiler': 'gcc'}, options={'restbed:shared': True}, env_vars={}, build_requires={}), BuildConf(settings={'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Release', 'compiler': 'gcc'}, options={'restbed:shared': True}, env_vars={}, build_requires={}), BuildConf(settings={'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Debug', 'compiler': 'gcc'}, options={'restbed:shared': False}, env_vars={}, build_requires={}), BuildConf(settings={'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Release', 'compiler': 'gcc'}, options={'restbed:shared': False}, env_vars={}, build_requires={}), BuildConf(settings={'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Debug', 'compiler': 'gcc'}, options={'restbed:shared': True, 'restbed:ssl': False}, env_vars={}, build_requires={}), BuildConf(settings={'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Debug', 'compiler': 'gcc'}, options={'restbed:shared': True, 'restbed:ssl': True}, env_vars={}, build_requires={}), BuildConf(settings={'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Release', 'compiler': 'gcc'}, options={'restbed:shared': True, 'restbed:ssl': False}, env_vars={}, build_requires={}), BuildConf(settings={'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Release', 'compiler': 'gcc'}, options={'restbed:shared': True, 'restbed:ssl': True}, env_vars={}, build_requires={}), BuildConf(settings={'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Debug', 'compiler': 'gcc'}, options={'restbed:shared': False, 'restbed:ssl': False}, env_vars={}, build_requires={}), BuildConf(settings={'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Debug', 'compiler': 'gcc'}, options={'restbed:shared': False, 'restbed:ssl': True}, env_vars={}, build_requires={}), BuildConf(settings={'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Release', 'compiler': 'gcc'}, options={'restbed:shared': False, 'restbed:ssl': False}, env_vars={}, build_requires={}), BuildConf(settings={'compiler.version': '4.9', 'compiler.libcxx': 'libstdc++', 'arch': 'x86_64', 'build_type': 'Release', 'compiler': 'gcc'}, options={'restbed:shared': False, 'restbed:ssl': True}, env_vars={}, build_requires={})]

So the filtered_builds array doesn't have any x86 as expected, but the builder.builds has.

Am I doing something wrong?

Actual execution at: https://travis-ci.org/nunojpg/conan-restbed/jobs/224929589

**Comment by lasote** [comment]
Hi, I'm checking it right now. If the bug is confirmed will release 0.3.2 in a hurry.

**Comment by lasote** [comment]
Confirmed. 0.3.2 will be available in few minutes also with the possibility of "pin" a conan_package_tools version (not using latest in docker containers)

**Comment by lasote** [comment]
Released!
