### ISSUE TITLE
Support modern package_manager mode

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-package-tools#607]
### Description of Problem, Request, or Question

So far, [CONAN_SYSREQUIRES_MODE](https://docs.conan.io/en/latest/reference/env_vars.html#conan-sysrequires-mode) is the environment variable which rules the legacy [SystemPackageTool](https://docs.conan.io/en/latest/reference/conanfile/methods.html#systempackagetool), however, with the migration of recipe and modernization of package manager support, the [conan.tools.system.package_manager](https://docs.conan.io/en/latest/reference/conanfile/tools/system/package_manager.html#conan-tools-system-package-manager) uses [config](https://docs.conan.io/en/latest/reference/conanfile/tools/system/package_manager.html#conan-tools-system-package-manager-config) to enable installing by default.

As current workaround, need to [run script before to build on Docker](https://github.com/conan-io/conan-package-tools#running-scripts-and-executing-commands-before-to-build-on-docker) to enable it, updating the global config file.

The feature consists updating it automatically, by adding a new cpt option, which will update both legacy and modern version. For instance:

```
CPT_SYSREQUIRES_MODE=[install, check, disable]
```

* `install`: equivalent to `CONAN_SYSREQUIRES_MODE=enabled` + `tools.system.package_manager:mode=install`
* `check`: equivalent to `CONAN_SYSREQUIRES_MODE=verify` + `tools.system.package_manager:mode=check`
* `disabled`: equivalent to `CONAN_SYSREQUIRES_MODE=disabled` + `tools.system.package_manager:mode=None` (It should accept `False` and `None` too)

```
CONAN_SYSREQUIRES_SUDO=[true,false]
```

* `true`, `1`, `yes`: Uses `sudo` command to execute the system package manager tool
* `false`, `0`, `no`: Do not use `sudo` command to execute the system package manager tool

```
CONAN_SYSREQUIRES_TOOL=[apt-get, yum, dnf, brew, pacman, choco, zypper, pkg, pkgutil]
```

It follows those supported tools listed on [modern system package](https://docs.conan.io/en/latest/reference/conanfile/tools/system/package_manager.html#configuration-properties-that-affect-how-system-package-managers-are-invoked)

**Comment by SSE4** [comment]
I would prefer some generic feature allowing to set arbitrary conf variables on command line. then, build `tools.system.package_manager:mode` on top of it.

**Comment by uilianries** [comment]
@SSE4 Yes, it sounds even better.
