### ISSUE TITLE
AppVeyor integration working?

### ISSUE THREAD

**Issue by nunojpg** [conan-io/conan-package-tools#61]
I'm getting this failure: https://ci.appveyor.com/project/nunojpg/conan-restbed/build/1.0.3

WARN: Remotes registry file missing, creating default one in C:\Users\appveyor\.conan\registry.txt
Current 'conan.io' user: None (anonymous)
C:\Python27-x64\python build.py
Traceback (most recent call last):
  File "build.py", line 1, in <module>
    from conan.packager import ConanMultiPackager
ImportError: No module named conan.packager
Command exited with code 1

I've searched for any recent builds succeeding on AppVeyor, but don't know of any repositories with CI going.

**Comment by lasote** [comment]
I think the problem could be invoking python like that, maybe the installed requirements are not in that python "environment", could you try to run like this:

```
test_script:
  - python build.py
```

You can see a working example here: https://github.com/lasote/conan-zlib

**Comment by nunojpg** [comment]
Looks to be the case. Thanks.

I copied it from the example at README.md. Maybe it should be fixed...
