### ISSUE TITLE
Conan 2.0

### ISSUE THREAD

**Issue by soerengustenhoff** [conan-io/conan-package-tools#616]
What does it require to migrate this to conan 2.0 ?

We use conan package tools to easily upload dependency packages which are build via conan.

what is the reasoning behind not supporting conan 2.0 ?

**Comment by memsharded** [comment]
Hi @soerengustenhoff 

Conan 2.0 has a new framework for creating custom commands, and it is already getting some utilities to incubate in: https://github.com/conan-io/conan-extensions. These custom commands can be adapted, shared and installed via ``conan config install``, and build on top of a public, documented API.

The plan is to potentially convert the utility from this repo to custom commands. The truth is that this project was born to create combinations of configurations when we didn't have ``conan-center-index`` github repo. We no longer use this repo at all, and we think most of the functionality in this repo has already better approaches.

Please report the detailed use cases you need, in this repo or in the https://github.com/conan-io/conan-extensions, and we can discuss there the use cases. It is important to describe the specifics of the use case, like ``easily upload dependency packages which are build via conan.`` is a bit too vague, as ``conan upload * -r=remote -c`` will upload packages too, so a bit more detailed will be necessary.

**Comment by soerengustenhoff** [comment]
Hi @memsharded 

Thank you for your swift response and sorry for my delayed respons now.

We build via a build server, and these build agents can possibly build many different dependencies.
So when we build our main project, we cannot be sure that all dependencies in conan cache should be uploaded.

What we would like is to upload only the dependencies build by our projects requirements.
Are we the only ones with this need ? it seems a bit weird :)

**Comment by memsharded** [comment]
Hi @soerengustenhoff 

No prob! We are all very busy :)  Same reason, don't hesitate to do reminders to resurface tickets or comments that we didn't respond, sometimes it happens they fall through the cracks.

For that specific goal, this ticket is open for Conan 2.X roadmap: https://github.com/conan-io/conan/issues/12885. This means that we will consider a built-in mechanism to upload the packages that resulted from a specific build (most likely based on the output json graph of a ``conan install`` or ``conan create`` command). I think you want to track that ticket for this feature.

**Comment by soerengustenhoff** [comment]
@memsharded  Consider me subscribed :)

That sounds very very good, i will continue the discussion in that issue.

Thank you for your responses James. i will close this as "duplicate" of https://github.com/conan-io/conan/issues/12885

**Comment by memsharded** [comment]
Great, thanks!
