### ISSUE TITLE
Git branch detection not working anymore for Gitlab

### ISSUE THREAD

**Issue by Linux13524** [conan-io/conan-package-tools#617]
The predefined CI variables for GitLab pipelines changed and some variable were removed including `CI_BUILD_REF_NAME` as of version 16.0, see [CI_BUILD_* predefined variables removed](https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/update/removals.md#ci_build_-predefined-variables-removed). The replacement for `CI_BUILD_REF_NAME` is `CI_COMMIT_REF_NAME`. Not sure if other affected variables are also in use by cpt.

**Comment by uilianries** [comment]
@Linux13524 Thank you for your report!

**Comment by uilianries** [comment]
@Linux13524 a hotfix is available on the version 0.39.1

**Comment by Linux13524** [comment]
Thanks for the fast fix!
