### ISSUE TITLE
Modify readme to describe why CPT is not supported in conan 2.0

### ISSUE THREAD

**Issue by aborzunov** [conan-io/conan-package-tools#619]
Maybe conan 2.0 provides some core-features that deprecates this project or there is some fundamental incompatibilities or it is just work-in-progress or did it became obvious over time that it was easier to use native CI/CD tools to produce massive package builds?

The readme asks us to "open an issue explaining your current case with more details", but it is not the case for new user is introduced to the project for the first time.

Thanks!

**Comment by memsharded** [comment]
Thanks for the feedback @aborzunov 

There are no plans to maintain this project, all the similar extensions for Conan 2 has been moved to ``conan-extensions`` repo.

I agree it is time to deprecate clearly this repo, and document it clearly in its README.

**Comment by memsharded** [comment]
> Conan 2.0 support ⚠️
The project Conan Package Tools does not support Conan 2.x and there is no current planned support.

Well, this is clear, isn't it?

New users shouldn't be introduced to this repo anymore, it is not even linked in the Conan 2 documentation.

> The readme asks us to "open an issue explaining your current case with more details", but it is not the case for new user is introduced to the project for the first time.

This means if you were a CPT user in Conan 1 and have some need for Conan 2, please comment, and we will try to help and redirect to other approaches in Conan 2.
