### ISSUE TITLE
Pages behaviour

### ISSUE THREAD

**Issue by nunojpg** [conan-io/conan-package-tools#63]
It is somehow not specified on the documentation how the builds are split by pages.

I've tested it and it seems that page N gets the builds with array index i mod N == 0, that is for example for 4 pages:

builder.builds[0] - > Page 1
builder.builds[1] - > Page 2
builder.builds[2] - > Page 3
builder.builds[3] - > Page 4
builder.builds[4] - > Page 1
builder.builds[5] - > Page 2

Please confirm and I can pull request a docs clarification.

Also, is there a way to have any control over this? For example, if I have 2 pages, I might want to split the builds in Page 1 for x86 and Page 2 for x86_64 so they take about the same time, as I also might want to keep variations of Debug or Shared in the same page, to reuse builds that just do different packaging.

Would I have to construct my builds array with x86 on even indexes and x86_64 on odd indexes?

Thanks,
Nuno

**Comment by lasote** [comment]
Hi, it works exactly like that. About controlling the pages and the configurations, currently is not possible. 
If you can submit a PR will be great.

Thanks!

**Comment by nunojpg** [comment]
My python knowledge probably will not allow me, but I'll give it a look. Thanks.
