### ISSUE TITLE
Python3 doesn't work on OSX

### ISSUE THREAD

**Issue by nunojpg** [conan-io/conan-package-tools#68]
https://travis-ci.org/nunojpg/conan-botan/jobs/232949741

```
Traceback (most recent call last):
  File "/Users/travis/.pyenv/versions/3.6.1/envs/conan/lib/python3.6/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "/Users/travis/.pyenv/versions/3.6.1/envs/conan/lib/python3.6/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/travis/.pyenv/versions/3.6.1/envs/conan/lib/python3.6/site-packages/pkg_resources/__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyOpenSSL 17.0.0 (/Users/travis/.pyenv/versions/3.6.1/envs/conan/lib/python3.6/site-packages), Requirement.parse('pyOpenSSL<16.1.0,>=16.0.0'), {'conan'})
```

Tested it failing for Python 3.5 and 3.6.

In Linux it works fine.

**Comment by lasote** [comment]
Hi, could you try to manually install these requirements and see if it works? (for me it's working):

cryptography>=1.3.4, <1.9
pyOpenSSL>=16.0.0, <17
ndg-httpsclient>=0.4.1, <0.5.0
pyasn>=1.5.0b7, <1.6.0

We will need to add them to ``conan`` project.

**Comment by nunojpg** [comment]
I don't have OSX (I'm using it only on Travis), and I am having some difficulty to try to bump this versions in Travis. Will give it a additional try tomorrow. Thanks

**Comment by nunojpg** [comment]
Tested. Your commit fixes it.

BTW, problem also breaks OSX builds with Python 2.7 since TODAY. For example this repo Travis CI is failing for OSX because of that.

So this should be released on conan when possible to resume OSX builds.

**Comment by lasote** [comment]
@nunojpg Thanks, yes, other user reported the same problem today. Thanks so much, we are going to release it in the current 0.23.0 (today, I hope)

**Comment by nunojpg** [comment]
There is still a problem.

Currently conan-package-tools requirements are:

```
six>=1.10.0
requests[security]<2.14.0,>=2.7.0
conan>=0.22.0
```

requests[security] causes pyOpenSSL-17.0.0 to be installed:

```
Collecting pyOpenSSL>=0.14; extra == "security" (from requests[security]<2.14.0,>=2.7.0->conan_package_tools)
  Downloading pyOpenSSL-17.0.0-py2.py3-none-any.whl (51kB)
```

But then conan requires pyOpenSSL<17.0.0.

I don't know much about python or pip, but I think the options are to relax conan requirements for pyOpenSSL further, or to just move conan before requests[security] on requirements.txt.

**Comment by lasote** [comment]
I see, So, installing first `conan` works, right?  I agree we should relax the pyOpenSSL dependency but not sure to which version, it doesn't follow any logic version scheme...

**Comment by nunojpg** [comment]
Yes.

For example I'm working around it by changing the sample .travis/install.sh to:

```
(...)
pip install conan
pip install conan_package_tools # It install conan too
conan user
```

I also have no idea how to handle this multiple dependencies on pip/python, that is why I'm not providing a pull request :/

**Comment by lasote** [comment]
We are going to release the minor 0.23.1 (I think today) and we will relax it to <18.

**Comment by lasote** [comment]
We've released the 0.23.1. Should be fixed now, If don't reopen (again ;) ) the issue

**Comment by nunojpg** [comment]
All solved :)

**Comment by theodelrieu** [comment]
Hi!

I have an issue with Python 3.6 on macOS too, the following code `builder = ConanMultiPackager()` fails with:

>Traceback (most recent call last):
  File "build.py", line 19, in <module>
    builder = ConanMultiPackager()
  File "/Users/theo/Library/Python/3.6/lib/python/site-packages/conan/packager.py", line 217, in __init__
    _, client_cache, _ = Conan.factory()
TypeError: 'ConanAPIV1' object is not iterable

Python 2.7 works fine, and everything works on Linux/Windows.

**Comment by memsharded** [comment]
NP! :)
