### ISSUE TITLE
Verbose option for print build list

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-package-tools#77]
Conan Package Tools introduced the print build list that helps to identify all builds to be performed.

```python
# packager.py:225
print("Page       : ", curpage)
print("Builds list:")
for p in builds_in_current_page: print(list(p._asdict().items()))
```

Today I'm working with Gcc and Clang, so, I got a bunch of builds in my CI log for each job. It's not a problem, but could be selected by verbose option:

```python
# packager.py:205
def run_builds(self, curpage=None, total_pages=None, verbose=False):
  ...
    if verbose:
        print("Page       : ", curpage)
        print("Builds list:")
        for p in builds_in_current_page: print(list(p._asdict().items()))
```

Another approach, could be using python logging, putting this message on DEBUG level.

**Comment by lasote** [comment]
I really like the list hahaha, very helpful to know what's going on. About the logging, yes, probably is the best choice, but I would say that these are not debug traces, are info traces.

**Comment by memsharded** [comment]
I also like them by default, very useful, please don't silent them, or I'll end up adding "verbose" to all my packages :)

**Comment by uilianries** [comment]
Okay, and about `quiet` option? :smile:

**Comment by lasote** [comment]
Yes, probably the best is opt out ;)
