### ISSUE TITLE
More flexible handling of `upload_repo`

### ISSUE THREAD

**Issue by kolis** [conan-io/conan-package-tools#82]
I have some problems with running the new upload handling in `ConanMultiPackager` using our private conan registry.

First problem, I already have a `conan remote` entry with the same address as the one specified in the `upload` parameter. Which then gives the following error:
```
ERROR: Remote 'foo' already exists with same URL
```
Maybe the `upload` parameter should be able to specify an existing remote entry if the build environment already has this set up?

If I remove this entry this entry before running the builder I can upload the package. But, if I run the build script a second time the `packager.py` tries to add the `upload_repo`again, even though it already exist.
```
ERROR: Remote 'upload_repo' already exists in remotes (use update to modify)
```

I do not see where this is removed from the list of remotes?

**Comment by uilianries** [comment]
I found the same problem. As temporary workaround, I added `$ conan remote remove upload_repo || true` in my build script, before to call `python build.py`.

**Comment by dimi309** [comment]
Same problem here. Also, I have a script that creates multiple ConanMultiPackagers for multiple packages. Uploading works for the first .run() and then crashes with the above mentioned error for the rest.

**Comment by lasote** [comment]
Hi all, the correct way to proceed is to use the ``REMOTES`` variable to specify the needed remotes and the ``UPLOAD`` (it could be repeated from REMOTES, but it ignores it).

The idea is to avoid the ``conan remote add`` execution in the scripts, for something more declarative and uniform. 

What do you think?

**Comment by uilianries** [comment]
Avoid to add `conan remote add` is very good, however, if I using some VM for all builds and it has my conan remote address, so conan_package_tools will conflict with this name.  
My opinion is, when CONAN_UPLOAD is present, before to set `upload_repo`, the script might scan if the address already exist in `conan remote list`. If yes, then, use that remote instead to create `upload_repo`. 

e.g.

```python
    upload = os.getenv("CONAN_UPLOAD", False)
    if upload:
        upload_remote_name = False
        # conan.remotes = {"conan.io": "http://server.conan.io", "bintray": "https://api.bintray.com/conan"}
        for repo_name, repo_address in conan.remotes.items():
            # CONAN_UPLOAD is in conan remote list
            if  repo_address == upload:
                # reuse the same remote name
                upload_remote_name = repo_name
                break
         if not upload_remote_name:
             # CONAN_UPLOAD should be add in remote list
             upload_remote_name = "upload_repo"
             conan.remotes[upload_remote_name] = upload
```

The same should be applied for `CONAN_REMOTES`, to avoid errors from "ERROR: Remote 'foobar' already exists with same URL."

**Comment by dimi309** [comment]
Hi @lasote,
Thanks for the feedback.
I am sorry but I did not understand if you are suggesting a change in the conan package tools or if you are trying to indicate that we should not be writing `conan remote add` ourselves.
Just to explain the problem I have encountered better, I would like to show you this build:

https://travis-ci.org/dimi309/conan-packages/jobs/243921564

I am not executing `conan remote add` myself. I am just using the REMOTES and UPLOAD variables in the .yml scripts. However, I am creating multiple ConanMultiPackagers and I am running them for multiple packages from the same script. This used to work some days ago, but now it crashes saying that a remote has already been added. So it seems to me that each ConanMultiPackager tries to do a conan remote add. If that is the case, I think that the problem would be solved if the multipackager would check if a remote or upload repository exists by the same name each time it tries to add one, and if so, just update it instead of trying to add it.

**Comment by dimi309** [comment]
(I seem to have reached the same conclusion with the previous commentator :smile: ) We were writing at the same time it seems...

**Comment by dimi309** [comment]
The other difference I've noticed is that now, if no CONAN_PASSWORD is provided on travis or appveyor, the upload crashes (I've mentioned this in another issue that I think is closed now). 
It used to be that it was just getting ignored before. I don't know if it you planned it to be like this now, but having the upload be ignored when there was no password was pretty convenient in my humble opinion. I am just mentioning this here in case it is something that could be considered at the same time.

**Comment by lasote** [comment]
Ok, I understand your concerns, will back soon with a fix

**Comment by dimi309** [comment]
Many thanks!

**Comment by lasote** [comment]
I've released conan_package_tools 0.4.6, now it checks if a remote exist. About the CONAN_PASSWORD Issue, please confirm first that the remotes issue is solved and then we can improve it.

**Comment by uilianries** [comment]
Great!

Thanks @lasote and @dimi309

**Comment by dimi309** [comment]
Thanks @lasote 

I don't know if it's temporary (I'll try again later), but I seem to be getting a lot less output and an error I'm not sure I've seen before in this exact form on travis:

https://travis-ci.org/dimi309/conan-packages/jobs/244561842

**Comment by dimi309** [comment]
On appveyor one of the builds seems to have completed but, again, I don't see much output regarding the results of each command...

https://ci.appveyor.com/project/coding3d/conan-packages/build/job/bli5o8txtyaohi46

**Comment by lasote** [comment]
About the less output, no, I didn't change anything about it, about the error I'm on it

**Comment by uilianries** [comment]
About the output, I saw the same behavior in FreeBSD shell.

**Comment by lasote** [comment]
Ah, yes, now I see. My fault.

**Comment by dimi309** [comment]
At least it's not my fault for once :rofl:

**Comment by lasote** [comment]
Try again, please!

**Comment by dimi309** [comment]
Re-launched...

**Comment by dimi309** [comment]
Output is back.

This is a small thingy but there is nothing saying "upload successful" or like it used to "uploaded 2/2 pacakges". That was kind of nice. But I guess that if there is no error it means that the upload succeeded..

```
############## CONAN PACKAGE TOOLS ######################
WARNING: Redefined channel by CI branch matching with 'master', setting CONAN_CHANNEL to 'stable' 
#########################################################
############## CONAN PACKAGE TOOLS ######################
INFO: ******** RUNNING BUILD ********** 
call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\../../VC/vcvarsall.bat" amd64 && conan test_package . --profile c:\users\appveyor\appdata\local\temp\1\tmpipkbmrconan_package_tools_profiles\profile --build missing
[build_requires]
[settings]
arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MT
compiler.version=12
[options]
[scopes]
[env]
```

**Comment by uilianries** [comment]
For me too! Tks!

**Comment by dimi309** [comment]
All the builds seem to be proceeding nicely and uploading. Thanks @lasote ! I'll check again later and see how they went.

**Comment by dimi309** [comment]
(Please disregard my upload indication comment. I misunderstood what I was looking at. My bad :frowning_face: )

**Comment by lasote** [comment]
The issue with the missing password should be ok too. I'm closing the issue, reopen if something is not good! and thanks for the feedback! :)

**Comment by dimi309** [comment]
After fixing a bug introduced by myself recently, all my builds now work well with the latest package tools. Thanks again @lasote! 

The only thing is that the upload still doesn't get ignored if there is no password:

https://travis-ci.org/dimi309/conan-packages/jobs/244790536

But if this is a design decision, just let us know. I am not re-opening the issue because I don't see a button to do that 😄

**Comment by lasote** [comment]
Mhh, I prefer to raise an error first because if you've specified the CONAN_UPLOAD variable maybe you expect to upload the packages, right?

**Comment by dimi309** [comment]
It's true that now it's more straightforward and can help avoid mistakes
(no publishing when you think you're publishing) Maybe I just got used to
the implicit switching off of uploads when removing the password but I can
live without it. :)

**Comment by lasote** [comment]
I detected an error with the package tools released yesterday, something capturing the output is generating that very long builds in windows are getting hung. I remembered that is an old issue with python and pipes. So, will release again in some minutes and any help to test it would be appreciated.

**Comment by lasote** [comment]
Ready, 0.4.9, please try the remote thing and report if something is failing again.

**Comment by dimi309** [comment]
I can test tonight.

**Comment by dimi309** [comment]
Launched the build (I just can't change code for now)

**Comment by dimi309** [comment]
I think it's still doing it https://travis-ci.org/dimi309/conan-packages/jobs/244790536

**Comment by lasote** [comment]
About the CONAN_UPLOAD not crashing without a password you are right, it's the only way to make PRs to the author without a crash. So I'm fixing it

**Comment by lasote** [comment]
0.4.10

**Comment by dimi309** [comment]
Yes!!!!!!!!!!!!!!!!! 
https://travis-ci.org/dimi309/conan-packages/jobs/244790536

Thanks a lot!
