### ISSUE TITLE
Easier way to use pages?

### ISSUE THREAD

**Issue by osechet** [conan-io/conan-package-tools#83]
My Qt package is very long to build and I need to be sure only one build is executed in one CI executor.  This can be achieve using pages but it can be quite complicated to evaluate the number of pages to set and which executor will build what.
For example, to build with 2 versions of msvc, in debug and release, I have to configure appveyor as follow:
```
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_TOTAL_PAGES: 4
          CONAN_CURRENT_PAGE: 1
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_TOTAL_PAGES: 4
          CONAN_CURRENT_PAGE: 2
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_TOTAL_PAGES: 4
          CONAN_CURRENT_PAGE: 3
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_TOTAL_PAGES: 4
          CONAN_CURRENT_PAGE: 4
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_TOTAL_PAGES: 4
          CONAN_CURRENT_PAGE: 1
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_TOTAL_PAGES: 4
          CONAN_CURRENT_PAGE: 2
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_TOTAL_PAGES: 4
          CONAN_CURRENT_PAGE: 3
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_TOTAL_PAGES: 4
          CONAN_CURRENT_PAGE: 4
```
But to reach this result I have to understand how the package tools work internally and next time I will read the script, there is a high chance I will need time to understand what is done. And if I want to add mingw configurations, it becomes even more unclear.

Is there an easier way to work with pages? Or maybe is there a way to directly say what should be build by the executor?

**Comment by lasote** [comment]
Yes, you can use [`named pages`](https://github.com/conan-io/conan-package-tools#pagination). Named pages are totally configurable, you can create in your build_py a page for every build and then in the CI matrix just assign: CONAN_CURRENT_PAGE="p1", other with CONAN_CURRENT_PATH="p2" and so on.

**Comment by osechet** [comment]
Looks good for me. I'll have a try.

> In your example you could extract the CONAN_TOTAL_PAGES: 4 to the global scope to avoid repeating it.
No I can't because I also have mingw builds and the number of pages is different for them.
