### ISSUE TITLE
Wildcard upload requires confirmation

### ISSUE THREAD

**Issue by sixten-hilborn** [conan-io/conan-package-tools#84]
Conan will ask for confirmation (yes/no) if the upload reference is a pattern.
The packager should probably pass `--confirm` to `conan upload` since it's purpose is mostly for CI/automation. Without `--confirm` my CI job creates an infinite large log when it hangs at:

    Are you sure you want to upload '...'? (yes/no): ERROR:  is not a valid answer
    Are you sure you want to upload '...'? (yes/no): ERROR:  is not a valid answer
    ...

**Comment by lasote** [comment]
Fixed in 0.4.31
