### ISSUE TITLE
Automatic test requires does not work with CI

### ISSUE THREAD

**Issue by theirix** [conan-io/conan-package-tools#87]
[Official documentation](https://conanio.readthedocs.io/en/latest/packaging/getting_started.html) and `conan new -t` suggest using a conanfile in a test package without `requires` directive. I tried to use this.

Travis uses `CONAN_USERNAME`, `CONAN_PASSWORD` and maybe `CONAN_REFERENCE` and others that should be passed to the conan-package-tools and then to the conan API. But it says "Please specify user and channel" when running on Travis, running `build.py`. Running `test_package` with a reference on command line works fine. Running `test_package` without a reference obviously fails.

I tried to debug a problem - user variables is lost between c-p-t and conan API.

conan (0.25.1)
conan-package-tools (0.4.35)

**Comment by memsharded** [comment]
Yes, it is very possible that conan-package-tools need to pass the user/channel to the ``test_package`` (actually better to update it to the new ``create`` command).

**Comment by lasote** [comment]
Released 0.5.0 using conan create. Now it works.

**Comment by theirix** [comment]
Thanks!
