### ISSUE TITLE
Priority of user defined remotes

### ISSUE THREAD

**Issue by bilke** [conan-io/conan-package-tools#88]
I am building a package with Travis and it requires another package which is hosted on my own artifactory Conan repo. I add this remote in `ConanMultiPackager` with the `remotes`-argument. The problem is that an outdated version of the required package is also in `conan-transit` which is found first. Is there a way to prioritise my remote over the default remotes? As I am using Docker I guess this has to happen inside the `ConanMultiPackager` and not for example in `run.sh`, right?

**Comment by lasote** [comment]
With conan >= 0.24, the specified remotes should be placed in the first positions, prioritized to the default ones. Do you have some trace to take a look?

**Comment by bilke** [comment]
Here is my package: https://github.com/bilke/conan-geotiff/tree/release/1.4.2

And here a failing Travis run: https://travis-ci.org/bilke/conan-geotiff/jobs/255945917

**Comment by uilianries** [comment]
@lasote I see the same behavior.

* I'm using the default template to conan project + conan-package-tools (.travis/ + build.py  + travis.yml)
* My upload repository and remote are the same
* I used CONAN_UPLOAD and CONAN_REMOTES as environment variable

Conan-packge-tools looks first on conan-center, followed by conan-transit and upload-repo.

I expected that upload-repo (my repo) would be the first.

You can see the log [here](https://travis-ci.org/uilianries/conan-cpprestsdk/jobs/255854432), that is about a [recipe](https://github.com/uilianries/conan-cpprestsdk/tree/testing/2.9.1) for cpprestsdk

Regards.

**Comment by lasote** [comment]
Ok guys, thanks for the info, will check it ASAP.

**Comment by uilianries** [comment]
Now I see:

```
# packager.py:90
if remote == self.upload:  # Already added
    continue
```

So, if CONAN_UPLOAD is in CONAN_REMOTES, it won't be reordered.

**Comment by lasote** [comment]
Hi! Try now, I've released 0.5.1.
If you want to specify an order for your upload repository just fill the upload server in both parameters, upload and remotes. If the remotes contain the upload repository too, it will add it granting the order of the "remotes" parameter.

**Comment by uilianries** [comment]
Hey @lasote, we a problem! 

Now we the same behavior in Travis related on #89 

![train](https://media.giphy.com/media/P2Zluyghl1AWY/giphy.gif)

**Comment by memsharded** [comment]
Thanks for telling. I think this PR may fix it: https://github.com/conan-io/conan-package-tools/pull/90

We'll try to release a new version asap.

**Comment by uilianries** [comment]
Thanks @memsharded! You was too fast!

I just commented about that issue here: https://github.com/conan-io/conan/issues/1534

Regards!

**Comment by bilke** [comment]
Thanks, in principal now it works as expected but now it hangs on running `conan user`-command. It seems that the login information is not passed to the docker container:

https://travis-ci.org/bilke/conan-geotiff/builds/256766724

`CONAN_USERNAME`, `CONAN_LOGIN_USERNAME` and `CONAN_PASSWORD` environment variables are all defined.

**Comment by lasote** [comment]
That is very very strange.v Do you have private conan repositories? Conan shouldn't ask the password, only for the upload, but in your traces are requesting the password for retrieve from your remote.

**Comment by bilke** [comment]
The repo is hosted on Artifactory but the `anonymous`-user has read permissions. I guess this should be enough?

**Comment by lasote** [comment]
@bilke probably artifactory/conan is requesting authentication. Have you tried to read from the repository locally without a logged user?

**Comment by bilke** [comment]
@lasote Yes that seems to be the problem: When running `conan search -r artifactory ...` it wants to login:

```bash
$ conan search -r artifactory foo
Please log in to "artifactory" to perform this action. Execute "conan user" command.
Remote 'artifactory' username:
```

**Comment by lasote** [comment]
I'm taking a look to the Artifactory permissions, I've never tried to allow anonymous reads to a repository. In case it doesn't work, we would need to model in package tools a set of USERS/PASSWORDS for each remote :S

**Comment by bilke** [comment]
Thank you for having a look!

**Comment by lasote** [comment]
It's working for me, actually, I have the opposite problem, can't limit the read access...

**Comment by lasote** [comment]
I will close this issue and open a new open.

**Comment by bilke** [comment]
@lasote Can you share your repository permission settings?

**Comment by lasote** [comment]
I think it won't be very helpful because as I said, I'm not able to limit the anonymous read access.
The only special thing I have is the:
`General Security Settings => Allow Anonymous Access`. But it doesn't care if I limit the capabilities to anonymous user to only read one repository... it looks like global.
