### ISSUE TITLE
migrate mingw handling to conanfile

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan-package-tools#92]
Currently, mingw  configuration is performed via environment variable in packager.py and builds_generator.py.
It could be removed to use only standard build dependencies and options because mingw installer can also be handled in each conanfile, using for example
```python
    def requirements(self):
        if self.settings.os == "Windows":
            if self.settings.compiler == "gcc":
                self.requires("mingw_installer/0.1@lasote/testing")
    def configure(self):
        if self.settings.os == "Windows":
            if self.settings.compiler == "gcc":
                self.options["mingw_installer"].version = self.settings.compiler.version
```
I am ready to work on this if you find it to be an interesting direction.

**Comment by memsharded** [comment]
I think the right approach to use mingw from conan recipes would be using ``build_requires``. Also, you have to consider that your suggested approach would require the default package option which would be version 4.8 (IIRC), and that is not probably what you want.

For build_requires such as this one, also the normal approach is to manage them in profiles, so you don't couple the package recipe with the compiler, as many users would already have a working MinGW compiler installed in their machines, and they won't be interested in installing another copy.

This is what conan-package-tools is doing right now. Please tell me if it makes sense, or you have further questions regarding this. Thanks!

**Comment by ericLemanissier** [comment]
Ok, I was missing the profiles part, and the fact that profile can be located next to the conan recipe. Thanks !

**Comment by memsharded** [comment]
Yes, profiles are very, very recommended for serious usage and working in teams. Thanks to you!
