### ISSUE TITLE
Easy way to fire CI for new compilers

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan-package-tools#98]
When a new compiler (like gcc 7.2) is out, it is not evident how to set the CI to build only for that new compiler, without doing a big mess with the scripts. I know it is not simple, but that would be very nice.

**Comment by lasote** [comment]
The problem is that it is barely related with the package_tools.  You need first a docker image. Then, what is the mess? CONAN_GCC_VERSIONS=7.2 should be enough. What are the steps you needed or thought you needed?

**Comment by lasote** [comment]
https://github.com/conan-io/conan-docker-tools

**Comment by lasote** [comment]
commit with the message:  "Any other message [build=outdated] any trailing message". It will build only the missing packages.
